### ISSUE TITLE
HTTP model for response StatusCode

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#1]
Create representation for all HTTP response status codes defined in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6).

Put them inside `zio.http.StatusCode`.

Aggregate issue to track progress. Please leave a comment which ones you take:
- [ ] 100 Continue
- [ ] 101 Switching Protocols
- [ ] 200 OK
- [ ] 201 Created
- [ ] 202 Accepted
- [ ] 203 Non-Authoritative Information
- [ ] 204 No Content
- [ ] 205 Reset Content
- [ ] 206 Partial Content
- [ ] 300 Multiple Choices
- [ ] 301 Moved Permanently
- [ ] 302 Found
- [ ] 303 See Other
- [ ] 304 Not Modified
- [ ] 305 Use Proxy
- [ ] 307 Temporary Redirect
- [ ] 400 Bad Request
- [ ] 401 Unauthorized
- [ ] 402 Payment Required
- [ ] 403 Forbidden
- [ ] 404 Not Found
- [ ] 405 Method Not Allowed
- [ ] 406 Not Acceptable
- [ ] 407 Proxy Authentication Required
- [ ] 408 Request Timeout
- [ ] 409 Conflict
- [ ] 410 Gone
- [ ] 411 Length Required
- [ ] 412 Precondition Failed
- [ ] 413 Payload Too Large
- [ ] 414 URI Too Long
- [ ] 415 Unsupported Media Type
- [ ] 416 Range Not Satisfiable
- [ ] 417 Expectation Failed
- [ ] 426 Upgrade Required
- [ ] 500 Internal Server Error
- [ ] 501 Not Implemented
- [ ] 502 Bad Gateway
- [ ] 503 Service Unavailable
- [ ] 504 Gateway Timeout
- [ ] 505 HTTP Version Not Supported

**Comment by unclebob418** [comment]
You're missing 418!

**Comment by vitaly-pushkar** [comment]
on it
