### ISSUE TITLE
Convert Headers from `case class` to `sealed` `trait`

### ISSUE THREAD

**Issue by amitksingh1490** [zio/zio-http#1007]
Headers currently is a **case class**, convert it to sealed trait with subtype `FromChunk` and `FromJHeaders`. This could help us get better perfomance

**Comment by adrianfilip** [comment]
Picked it up

**Comment by adrianfilip** [comment]
Would it be preferable to have more case classes?
```
sealed trait Headers extends HeaderExtension[Headers]

final case class FromChunk(toChunk: Chunk[Header]) extends Headers
final case class FromJHeaders(toJHeaders: HttpHeaders) extends Headers
final case class FromAll(toChunk: Chunk[Header], toJHeaders: HttpHeaders) extends Headers
case object EmptyHeaders extends Headers
```
Otherwise everytime we combine FromChunk and FromJHeaders we would have to convert one on the spot.

**Comment by jdegoes** [comment]
@adrianfilip Yes. Just be sure those constructors are package-private, because they are a performance-oriented implementation detail and should not leak into the interface. 

You could also consider:

```scala
abstract class SingleHeader extends Headers
```

then making `Header` extend `Headers` to avoid "singleton chunk" wrapping overhead.

**Comment by adrianfilip** [comment]
This was merged and can be closed. https://github.com/zio/zio-http/pull/1463
