### ISSUE TITLE
IO-oriented `HttpApp`s should expose expected exceptions in error channel

### ISSUE THREAD

**Issue by nartamonov** [zio/zio-http#1021]
**Is your feature request related to a problem? Please describe.**
zio-http provides a few of http-apps (instances of `HttpApp`) that perform some IO in order to respond to a client request. For example, `Http.fromFile`, `Http.fromStream`, `Http.fromData(Http.fromFile(/*..*/))`, `Http.fromData(Http.fromStream(/*..*/)`, maybe others.

Any such http-app may fail with some exception. From the point of view of zio-http library those exceptions are domain errors. They can be (and should be) handled by user code just like we handle other domain errors:

* They can be catched and handled properly to recover from errors (`catchAll`)
* They can be refined to upper-level exceptions of our domains (`refine`, currently unimplemented);
* They can be converted to fatal errors if we can't handle it properly (`.orDie`, `.refineOrDie`, etc, currently unimplemented).

Currently those IO-oriented http-apps don't expose possible IO-exceptions at all. They all have the type of `HttpApp[Any,Nothing]`. So in the case of the following app we have no ways to recover from `IOException`s while reading the content of the requested file:

```scala
object TestApp extends zio.App {
  val app =
    Http.fromFile(new File("/non-existent.file"))

  def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    Server.start(8080, app).orDie
  }
}
```

The app just fails with `NullPointerException` when received http request. I'm not sure there are any ways to recover from that error and return `500 Internal Server Error` or something else.

At my work we have an application that considers IO-exceptions (file was not found, file is not accessible, disk IO error and so on) as so called "system-wide failures": in such cases the application generates some unique identifier, build JSON response with the identifier and other details about a failure and sends it to a client. 

**Describe the solution you'd like**
I suggest we refactor IO-oriented http apps (and other apps that could fails with expected exceptions) to expose expected exceptions in their error-channels, something like:

```scala
object Http {
  def fromFile(file: File): HttpApp[Any, IOException] = /* ... */
  def fromStream[R](stream: ZStream[R, Throwable, Byte]): HttpApp[R, Throwable] = /* ... */
  // and so on
}
```

Besides I think it worth to implement methods `refine`, `orDie`, `refineOrDie` for `Http` objects. I think this approach is familiar to any ZIO user.

**Additional context**
I considered the design of zio-http 1.0.0.0-RC24.

**Comment by tusharmath** [comment]
@nartamonov The issue has been fixed in #1061. `Http.fromFile` now returns a `HttpApp[Any, Throwable]`

That being said I think we should add the above operators `orDie` `refineOrDie` `refine` `catchSome` etc. It would be great if you could create a PR for this :) 

`orDie` should convert the error into an `InternalServerError`
