### ISSUE TITLE
setCookiesDecode uses wrong date format

### ISSUE THREAD

**Issue by onsoup42** [zio/zio-http#1093]
Ran into this when trying to use `Response.setCookiesDecode`.  It always returned `None`.

Turns out currently it expects a date on this format for the `expires` value :
`2022-02-24T17:10:10.682151Z`
The Set-Cookie I was trying decode had an expires value on this format:
`Fri, 25 Feb 2022 04:49:46 GMT`
This also seems to be the format that the [HTTP specification](https://httpwg.org/specs/rfc7231.html#header.date) calls for. I belive zhttp is not following the specification here

**Comment by tusharmath** [comment]
Thanks @onsoup42. This seems like a easy fix, want to give it a try?

**Comment by dhyanpatel** [comment]
Hi! I'm new to contributing to open source. I'm taking a shot at this if that's fine. Any feedback is helpful! You can also reach me on discord at Aethen#8828 (I'm on the ZIO discord server)

**Comment by tusharmath** [comment]
Awesome @dhyanpatel we are all available on Discord, you can post your questions there if you get stuck. All the best :)

**Comment by Dennis4b** [comment]
Based on the discussion at `https://stackoverflow.com/questions/7707555/getting-date-in-http-format-in-java` the following patch works for me:

```
diff --git a/zio-http/src/main/scala/zhttp/http/Cookie.scala b/zio-http/src/main/scala/zhttp/http/Cookie.scala
index 4d7dc61b..e18a5f66 100644
--- a/zio-http/src/main/scala/zhttp/http/Cookie.scala
+++ b/zio-http/src/main/scala/zhttp/http/Cookie.scala
@@ -3,11 +3,13 @@ package zhttp.http
 import zio.duration._
 
 import java.security.MessageDigest
-import java.time.Instant
+import java.time.{Instant,ZoneOffset}
 import java.util.Base64.getEncoder
+import java.util.Locale
 import javax.crypto.Mac
 import javax.crypto.spec.SecretKeySpec
 import scala.util.Try
+import java.time.format.DateTimeFormatter
 
 final case class Cookie(
   name: String,
@@ -130,7 +132,7 @@ final case class Cookie(
 
     val cookie = List(
       Some(s"$name=$c"),
-      expires.map(e => s"Expires=$e"),
+      expires.map(e => s"Expires=${Cookie.dateTimeFormatter.format(e)}"),
       maxAge.map(a => s"Max-Age=${a.toString}"),
       domain.map(d => s"Domain=$d"),
       path.map(p => s"Path=${p.encode}"),
@@ -174,6 +176,13 @@ object Cookie {
   private val sameSiteStrict = "strict"
   private val sameSiteNone   = "none"
 
+  /* RFC_1123_DATE_TIME uses a single digit for the day of the month, whereas RFC 7231 specifies
+   * 2 digits. We therefore use this custom formatter, and set the locale to English for the month
+   * names (Jan, Feb, ...)
+   */
+  private val dateTimeFormatter = DateTimeFormatter.ofPattern("EEE, dd MMM yyyy HH:mm:ss O", Locale.ENGLISH)
+                                                   .withZone(ZoneOffset.UTC)
+
   sealed trait SameSite {
     def asString: String
   }
```

I can make a PR if the above looks OK (not sure about test/style requirements).
