### ISSUE TITLE
Cookie encode throw exception in case of empty secret

### ISSUE THREAD

**Issue by kaushik143** [zio/zio-http#1114]
**Describe the bug**
Cookie encode throw exception in case of empty secret

**To Reproduce**
1. Go to 'CookieSpec'
2. Change the `cookies` gen function to have only an empty secret

  ```
def cookies: Gen[Random with Sized, Cookie] = for {
    name     <- Gen.anyString
    content  <- Gen.anyString
    expires  <- Gen.option(Gen.anyInstant)
    domain   <- Gen.option(Gen.anyString)
    path     <- Gen.option(path)
    secure   <- Gen.boolean
    httpOnly <- Gen.boolean
    maxAge   <- Gen.option(Gen.anyLong)
    sameSite <- Gen.option(Gen.fromIterable(List(Cookie.SameSite.Strict, Cookie.SameSite.Lax)))
    secret   <- Gen.option(Gen.fromIterable(List("")))
  } yield Cookie(name, content, expires, domain, path, secure, httpOnly, maxAge, sameSite, secret)
```
3. Run `CookieSpec`
4. See an error

> java.lang.IllegalArgumentException: Empty key
  	at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:110)

**Expected behaviour**
Encode shouldn't throw an exception

**Comment by dhyanpatel** [comment]
I'd like to take a shot at this!
