### ISSUE TITLE
Adding missing status codes (451)

### ISSUE THREAD

**Issue by brodin** [zio/zio-http#1116]
**Is your feature request related to a problem? Please describe.**
It is very hard to extend status codes and I would love to use 451

**Describe the solution you'd like**
Let users extend the status code trait (can be tricky since it can't be sealed trait)

**Describe alternatives you've considered**
Simply just add more common status codes, like 451.

**Additional context**

Thanks for a great repo!

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451

**Comment by amitksingh1490** [comment]
duplicate #1117.  @brodin  thanks for reporting this. Instead of only adding **451** we could add a custom type where user should be able to create any status code. Just as `netty` handles it.
