### ISSUE TITLE
How to set option and channelOption for ServerBootstrap

### ISSUE THREAD

**Issue by rajcspsg** [zio/zio-http#1170]
**Is your feature request related to a problem? Please describe.**
I want to set custom  values for option and channelOption for serverBootstrap. I looked into the code seems like there is no way to customize those values. I want to confirm the same.

**Describe the solution you'd like**
Please provide options to set option and channelOption for ServerBootstrap

**Additional context**
See example [here](https://github.com/rajcspsg/netty-mem-detect-demo/blob/master/core/src/main/java/com/myorg/netty/HttpServer.java#L39-L42) to set option and channelOption set for ServerBootstrap.

**Comment by zsfVishnu-d11** [comment]
Picking this up.
