### ISSUE TITLE
Streaming request body stalls, if consumer is too slow

### ISSUE THREAD

**Issue by gregor-rayman** [zio/zio-http#1187]
**Describe the bug**

When the request's `bodyAsStream` is run to a slower sink, the whole process stalls and no response is generated. Adding buffering `bodyAsStream.bufferUnlimited` solves the issue, but increases memory consumption and turns off backpressure.

**To Reproduce**
Steps to reproduce the behaviour:

Try the following application: 

```scala
object Main extends ZIOAppDefault {

  private val app = Http.collectZIO[Request] {
    case req @ Method.POST -> !! / "store" => ZIO.scoped (
      for {
        byteCount <- req.bodyAsStream.run(ZSink.fromOutputStreamScoped(
          ZIO.attemptBlockingIO(new BufferedOutputStream(new FileOutputStream("target/test")))
        ))

      } yield Response.text(s"$byteCount stored")
    )
  }

  override def run =
    Server.start(8090, app).exitCode
}
```

Then post some larger file to the server `curl -X POST http://localhost:8090/store --data-binary @somelargerfile` 

The request will be correctly processed for small files, but for larger files the response is never received.

**Expected behaviour**

The request should be processed and a response should be generated. If the server cannot process the data fast enough, it should slow down receiving the data from the client.  (Or, if not possible, at least an error response should be generated)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro, Linux Ubuntu 20.04 , Windows 11
 - Version: 2.0.0-RC6 with ZIO 2.0.0-RC4 (also 2.0.0-RC5 with ZIO 2.0.0-RC3)

**Comment by gciuloaica** [comment]
Issue is present also in  main branch.
