### ISSUE TITLE
Unable to get websocket client to connect to server using examples

### ISSUE THREAD

**Issue by djaygu** [zio/zio-http#1211]
I've been trying to run the websocket server and client examples locally - I expected the client to establish a connection and print a heartbeat from the server but all I get is a close message. 

The server/client code is essentially the [WebSocketAdvanced](https://github.com/dream11/zio-http/blob/main/example/src/main/scala/example/WebSocketAdvanced.scala) and [WebSocketSimpleClient](https://github.com/dream11/zio-http/blob/main/example/src/main/scala/example/WebSocketSimpleClient.scala). Both sockets have been modified to print received messages to console and the server sends out a heartbeat text. 
Server code snippet: https://pastebin.com/uBQUGWWV
Client code snippet: https://pastebin.com/WTyMTBGb

I expected the client to connect to the server, initiate a connection and start printing out the heart beat. 

I expected the console for each respective socket would look like the following. 
```
//Server
Server started on port: 8090
Message Received: Greetings from client!

//Client
Message Received: Greetings from server!
Message Received: HEARTBEAT
Message Received: Received: Greetings from client!
Message Received: HEARTBEAT
Message Received: Received: Greetings from client!
Message Received: HEARTBEAT
Message Received: Received: Greetings from client!
Message Received: HEARTBEAT
Message Received: HEARTBEAT
```

However when running code I get the following 

```
//Server
Server started on port: 8090
Message Received: Greetings from client!

//Client
Connection closed: localhost/127.0.0.1:8090

Process finished with exit code 0
```

When I connect to the server using a websocket tester I get the following log - which is what I expected. 
```
>Greetings from websocket tester
Greetings from server!
HEARTBEAT
Received: Greetings from websocket tester
HEARTBEAT
Received: Greetings from websocket tester
HEARTBEAT
Received: Greetings from websocket tester
HEARTBEAT
HEARTBEAT
HEARTBEAT
```

**Comment by tusharmath** [comment]
This is expected behaviour. 

Socket is built on top of ZStream. So for every incoming WebSocketFrame you can produce a ZStream of WebSocketFrame. This is applicable on both the client and the server. However, one important capability that users typically want is the ability to close a socket connection once the stream is complete. And that's exactly what is happening over here. `ZStream.empty` is closing the connection automatically.

Feel free to reopen the issue or continue the discussion on the discord channel :)

**Comment by gurghet** [comment]
I have a similar issue with an echo server:
```scala
import zio._
import zhttp.socket._
import zhttp.service._
import zio.stream.ZStream

object Main extends ZIOAppDefault {
    val app = Socket
    .collect[WebSocketFrame] {
      case WebSocketFrame.Text("BAZ") => ZStream.succeed(WebSocketFrame.close(1000))
      case frame                      => ZStream.succeed(frame)
    }
    .toSocketApp
    .connect("ws://ws.vi-server.org/mirror")

  def run = app.exitCode.provide(ChannelFactory.auto,EventLoopGroup.auto())
}
```
When I connect with a regular web socket client the connection remains open. But the above client immediately shuts down. This is very similar to the example, so I don't get why it should not work.
