### ISSUE TITLE
Release using zio 2.0.0-RC5

### ISSUE THREAD

**Issue by adamw** [zio/zio-http#1217]
We're hitting bin compat problems when trying to update tapir.

Thanks! :)

**Comment by amitksingh1490** [comment]
We will make a RC release tomorrow. 
A snapshot version could be found here
https://s01.oss.sonatype.org/content/repositories/snapshots/io/d11/zhttp_2.13/2.0.0-RC6+2-a50397fc-SNAPSHOT/

**Comment by adamw** [comment]
Great, thanks :)

**Comment by adamw** [comment]
And released :)
