### ISSUE TITLE
Consider removing a wild `println` from `Server.start`

### ISSUE THREAD

**Issue by aartigao** [zio/zio-http#1222]
One of the `Server.start` methods have what I guess is some local development logging that reached productive code:

https://github.com/dream11/zio-http/blob/a50397fc11743b32ed95ec350178437da8405ce1/zio-http/src/main/scala/zhttp/service/Server.scala#L218

As one peer suggested, it has the following issues:

- Having that log only for a very specific overloaded method of Server.start
- Using `println`
- Not considering that `println` is an effect, and could eventually throw `=> Task`

Please, consider removing it 🙏🏽

**Comment by tusharmath** [comment]
It's a valid concern. Would you be willing to open a pr?
