### ISSUE TITLE
URL parsing loses a `/` from the original string - causing infinite loops on client side

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio-http#1225]
**Describe the bug**
URL parsing loses a `/` from the original string

**To Reproduce**
Steps to reproduce the behaviour:
```scala
val original = "https://www.company.com/log/?verbose=true"
println(original)
val parsed = URL.fromString(original).toOption.get
val encoded = URL.encode(parsed)
println(encoded)
```

**Expected behaviour**
Should have printed `https://www.company.com/log/?verbose=true` two times

**Actual behaviour**
Prints two different urls

```
https://www.company.com/log/?verbose=true
https://www.company.com/log?verbose=true
```

the second one is missing a `/` 

**Additional context**
Some servers return a 302 when request url does not contain a `/` in the end. It's not possible to follow that redirect since the url parsing of `location` header again results in losing `/` and hence it goes into infinite loop of redirects.

URL parsing should not lose anything from original url string if parsing is successful.

`assert(original == encoded)` should be successful

**Comment by adamw** [comment]
I think it's the same problem as in https://github.com/dream11/zio-http/issues/919
