### ISSUE TITLE
Increase default maxRequestSize?

### ISSUE THREAD

**Issue by asavelyev01** [zio/zio-http#1227]
The default `maxRequestSize` of 4KB feels like rather a small volume. In our service, which is a Caliban + zio-http setup, this limit has hit us rather unexpectedly and we started failing failed on a more or less trivial query.

Should it be bigger at least an order of magnitude ~512KB? In our app I set it as `Int.MaxValue` as I don't really see the use of that limit at all :)

**Comment by alphaho** [comment]
@asavelyev01 May I know which version you are using? I think the default 4KB maxRequestSize has been removed in the recent versions after this PR: #1048

> MaxRequestSize server setting deprecated and enableObjectAggregator takes maxRequestSize as argument.(Breaking Change)

**Comment by tusharmath** [comment]
Yes, @alphaho is right. At by default there is no limit set. 
However you can always use `objectAggregator` setting to configure the server to use an object aggregator and set the value to any `Int`

Note that increasing the value to very high values can make the system vulnerable to attacks.

**Comment by asavelyev01** [comment]
Thanks so much for the insight @alphaho & @tusharmath.
The version we were using was the one coming from the latest Caliban [release](https://github.com/ghostdogpr/caliban/releases/tag/v1.4.0) and that was [1.0.0.0-RC25](https://github.com/ghostdogpr/caliban/blob/v1.4.0/build.sbt#L28). 
What I did was: I explicitly bumped `zio-http` version in or app to override this transitive one and it worked. I don't need to set any big numbers to avoid `413 Request Entity Too Large` any more, and also it didn't fall apart for any binary incompatibility. Kudos!
