### ISSUE TITLE
Exception on unsafe cast in writeResponse

### ISSUE THREAD

**Issue by senia-psm** [zio/zio-http#1229]
A simple test that starts echo `Server` and performs a single `Client` call runs forever.

This looks like regression: runs forever on `2.0.0-RC7`, works as expected on `2.0.0-RC4` (with `ZManaged` instead of `Scope`).

**To Reproduce**
See this project with a single test: https://github.com/senia-psm/zhttp-bug

This test runs forever:
```scala
test("Server should be able to start on an unoccupied port") {

  val dummyRoute = Http.collect[Request] { case req @ Method.POST -> !! / "echo" =>
    Response(status = Status.Ok, data = req.data)
  }

  val layer: ZLayer[ServerChannelFactory & EventLoopGroup, Nothing, Server.Start] = ZLayer.scoped {
    Server(dummyRoute).withBinding("localhost", 0).make.orDie
  }
  val env                                                                         = ZLayer
    .make[Server.Start & EventLoopGroup & ChannelFactory](
      layer,
      EventLoopGroup.auto(0),
      ServerChannelFactory.auto,
      ChannelFactory.auto,
    )

  val action = for {
    port           <- ZIO.serviceWith[Server.Start](_.port)
    resp           <- Client.request(
                        s"http://localhost:$port/echo",
                        method = Method.POST,
                        content = HttpData.fromString("echo string"),
                      )
    responseString <- resp.bodyAsString
  } yield assertTrue(port > 0, responseString == "echo string")

  action.provideLayer(env)
},
```

**Expected behaviour**
Test above should complete in finite amount of time (< 1 second).

**Desktop:**
 - OS: Linux
 - Version: 5.4.179-gentoo

**Additional context**
Might be related to https://github.com/zio/interop-cats/issues/533

**Comment by senia-psm** [comment]
Replacing `Response(status = Status.Ok, data = req.data)` with `req.data.toByteBuf.map(bb => Response(status = Status.Ok, data = HttpData.fromByteBuf(bb)))` solves an issue, though it prevents streaming. Can be used as a workaround.

**Comment by senia-psm** [comment]
@adamgfraser tracked down the issue:
The reason is unsafe cast: `msg.data.asInstanceOf[HttpData.Complete]` in `ServerResponseHandler::writeResponse`.

**Comment by tusharmath** [comment]
Yeah this is a regression. Will take this up. Let me know if you want to give it a shot. I can point you to the exact place where changes are required.

**Comment by senia-psm** [comment]
@tusharmath I can try to fix it if you give me a hint on how to process `UnsafeAsync` in `writeResponse`. Should I convert it to `Complete` with something like `BinaryStream(unsafeAsync.toByteBufStream)`?

**Comment by tusharmath** [comment]
@senia-psm Basically you just want to read data piece by piece and write it on the channel.
Look at the code here — https://github.com/dream11/zio-http/blob/main/zio-http/src/main/scala/zhttp/http/HttpData.scala#L160

In our case, instead of creating a stream we will write it on the channel. Hope this helps.

**Comment by senia-psm** [comment]
@tusharmath it seems like I don't understand `zio-http` internals good enough to fix it - even the most obvious and straight forward fix fails for me. See #1236 - `fromStream` test fails and I have no idea how to fix it.

**Comment by senia-psm** [comment]
@tusharmath actually it seems like there is another bug - see #1237
