### ISSUE TITLE
Flaky Websocket Server test case

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#1234]
The test case `WebSocketServerSpec.success` fails sometimes.

https://github.com/dream11/zio-http/runs/6209912741?check_suite_focus=true#step:5:209

**Comment by gciuloaica** [comment]
I was not able to reproduce this failures. The test has the `nonFlaky` annotation.

**Comment by tusharmath** [comment]
It fails only on the CI. I have never been able to reproduce it locally either.

**Comment by tusharmath** [comment]
This is not happening anymore.
