### ISSUE TITLE
Throw onUnhandledInboundException in wrk test

### ISSUE THREAD

**Issue by gcnyin** [zio/zio-http#1235]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Throw onUnhandledInboundException when using wrk to do performance test.

**Screenshots**

App code

```scala
object Loom extends App {
  val app: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "text" => Response.text("Hello World!")
  }
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
}
```

Wrk command

```
wrk -t4 -c100 -d10s http://localhost:8090/text
```

OS: Ubuntu server 20.04
Version: `val ZHTTPVersion = "1.0.0.0-RC24"`

**Comment by tusharmath** [comment]
I am not sure what the issue is. What is the behaviour you are observing @gcnyin?

**Comment by gcnyin** [comment]
Sry.

After running the wrk benchmark, the application logged something like this when the http connection was closed.

```
May 02, 2022 10:17:27 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

Wrk command

```
wrk -t4 -c100 -d10s http://localhost:8090/text
```

It was running on a 2c4g machine.

**Comment by tusharmath** [comment]
The reason this error happens is because wrk closes the connections abruptly after 10 seconds. Also, since error happens outside of the request response cycle you can not capture it inside a `Http`. You can still use `withError` operator on `Server` to capture this error.
