### ISSUE TITLE
WebSocketEcho + WebSocketSimpleClient not working as is

### ISSUE THREAD

**Issue by gurghet** [zio/zio-http#1245]
**Describe the bug**
Trying to run WebSocketSimpleClient while WebSocketEcho is running will just shut down the client prematurely.

**To Reproduce**
Run WebsocketEcho and on the same machine run WebSocketSimpleClient.
The connection is established, upgraded, but then immediately closed (gracefully).

Following a capture from Wireshark with a run.

**Expected behaviour**
When WebSocketEcho is running, if I run the following command:
```
websocat --linemode-strip-newlines ws://localhost:8090/subscriptions
```
The connection is not closed after being upgraded, but remains open.
Furthemore if I enter `FOO` it correctly answer with `BAR`.

**Screenshots**
<img width="1628" alt="Снимок экрана 2022-05-08 в 18 50 01" src="https://user-images.githubusercontent.com/420735/167306557-80198334-1c47-4462-b1b5-025bcc2dcbfc.png">

**Desktop (please complete the following information):**
 - OS: BigSur
 - Browser N/A
 - Version 2.0.0-RC7+1-c29b7875-SNAPSHOT

**Comment by tusharmath** [comment]
@gurghet Can you share some sample code.

**Comment by tusharmath** [comment]
@gurghet I have changed the API to ZManaged, which will make sure that the connection is managed and doesn't close automatically.

```scala
val socket = Socket.collect[WebsocketFrame] {
  case frame => ZStream.succeed(frame)
}
.toSocketApp
.connect("ws://ws.vi-server.org/mirror")
.useForever // UseForEver will keep the connection running forever
```
