### ISSUE TITLE
v2.0.0-RC8 release?

### ISSUE THREAD

**Issue by pjfanning** [zio/zio-http#1250]
It would be nice to release the recent commit to support latest zio 2 rc.

**Comment by gurghet** [comment]
I can help with the backport of #1259 if needed. I just can't find the scala 3 version of it. If there is some work already open I'll happily join.

Edit: ok maybe there is no scala 3 version and everything is as compatible as possible, got it. I'll submit the PR soon.

**Comment by pjfanning** [comment]
@gurghet the branch is called 'zio-series/2.x'

**Comment by gurghet** [comment]
Dropped #1279

**Comment by pjfanning** [comment]
I've added a port of netty changes from master to zio2 branch - https://github.com/dream11/zio-http/pull/1278

**Comment by amitksingh1490** [comment]
Fixed in https://github.com/dream11/zio-http/pull/1280

**Comment by pjfanning** [comment]
@amitksingh1490 thanks for publishing zhttp. It looks like zhttp now relies on zhttp-logging and that does not appear to be released.

https://repo1.maven.org/maven2/io/d11/zhttp_3/2.0.0-RC8/zhttp_3-2.0.0-RC8.pom

```
<dependency>
<groupId>io.d11</groupId>
<artifactId>zhttp-logging_3</artifactId>
<version>2.0.0-RC8</version>
</dependency>
```

There is no zhttp-logging_3 directory at https://repo1.maven.org/maven2/io/d11/

**Comment by amitksingh1490** [comment]
@[pjfanning](https://github.com/pjfanning) apologies fixing this right away
