### ISSUE TITLE
how to run typelevel effects, for running doobie jdbc?

### ISSUE THREAD

**Issue by lanyusan** [zio/zio-http#1293]
I am testing zio-http, trying to run doobie transactions as typelevel effects. 

Couldn't figure out a way to do so without using doobie's `unsafeRunSync` 

Is there a way to run the effects as IO monad with zio-http?

Thanks in advance.

**Comment by guersam** [comment]
Use can use [zio-interop-cats](https://github.com/zio/interop-cats).

**Comment by guizmaii** [comment]
@lanyusan Have you seen https://github.com/gaelrenoux/tranzactio?

**Comment by lanyusan** [comment]
Thanks guys.
