### ISSUE TITLE
HttpData.fromStream should allow to use environment aware streams (2.0.0-RC9)

### ISSUE THREAD

**Issue by dobrynya** [zio/zio-http#1300]
```scala
val data: ZStream[SomeService, Throwable, Byte] = ??? 
val httpData = HttpData.fromStream(data) // This line does not compiles as it expects a stream without any dependency
````
So it needs  resolve dependencies in explicit manner like follows
```scala
val data: ZStream[SomeService, Throwable, Byte] = ??? 
val httpData = HttpData.fromStream(data.provideEnvironment(ZEnvironment(SomeService.instance)))
```
It seems to be clearer if HttpData can supply the environment to streams like HttpApp[R...]

**Comment by tusharmath** [comment]
I agree this could be a great addition to `HttpData` however adding a `R` parameter to HttpData requires adding and `R` parameter to both `Request` and `Response`, which can quickly get complicated (especially with middlewares).

What you can do as an alternative is use `Http.fromStream` instead. This way you won't have to worry about `R` or `E` :)

**Comment by dobrynya** [comment]
As I see there are changes in the branch main-zio-2 regarding to introducing polimorphic HttpData[R, E].  So it seems we can close this issue.
