### ISSUE TITLE
Epoll isn't used anymore

### ISSUE THREAD

**Issue by davidlar** [zio/zio-http#1301]
After https://github.com/dream11/zio-http/pull/1255 epoll (and probably kqueue) isn't used anymore, so nio will be used instead.
The problem is that the platform dependent jar files is not among the dependencies.

If I add `"io.netty" % "netty-transport-native-epoll" % "4.1.77.Final" classifier "linux-x86_64"` it works again for me.

Regards David

**Comment by tusharmath** [comment]
@davidlar Thanks for reporting this. This explains why there is a bit of a drop in performance in the latest version. 

Would you be able to create a PR for this? Thanks once again!

**Comment by davidlar** [comment]
Sure! I'll do that!

**Comment by davidlar** [comment]
Do you want the PR in master and/or series/2 ?

**Comment by tusharmath** [comment]
Master

**Comment by davidlar** [comment]
https://github.com/dream11/zio-http/pull/1302 created
