### ISSUE TITLE
bodyAsString can only be called once

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-http#1309]
**Describe the bug**
If you call `bodyAsString` in a `Middleware` (for example, to log the request), and then call it again in the actual processing of the request, the second call hangs forever.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a middleware that calls `bodyAsString`
2. Apply the middleware twice
3. Send a request

**Expected behaviour**
`bodyAsString` can be called any number of times.

**Comment by lachezar** [comment]
I just stumbled into the exact same issue
