### ISSUE TITLE
Release with ZIO 2.0.0

### ISSUE THREAD

**Issue by aleksandr-vin** [zio/zio-http#1348]
Last RC was June 2, I see ZIO 2.0.0 in SNAPSHOT from main. What could be the ETA on release?

**Comment by aleksandr-vin** [comment]
It is heavily needed for https://github.com/ghostdogpr/caliban/pull/1407

**Comment by aleksandr-vin** [comment]
Also needed for https://github.com/softwaremill/tapir/pull/2263

**Comment by tusharmath** [comment]
this is done :)

**Comment by gchudnov** [comment]
@tusharmath 
thank you for the release,

wondering if zhttp-test was released as well?

somehow cannot see it here: https://repo1.maven.org/maven2/io/d11/zhttp-test_2.13/

Can see only RC9, but RC10 is missing :(

**Comment by gchudnov** [comment]
ah, it was removed,
sorry, missed the message

all good
