### ISSUE TITLE
Logger doesn't propagate to `Http`

### ISSUE THREAD

**Issue by beneyal** [zio/zio-http#1352]
**Describe the bug**
When using an SLF4J logger with ZIO HTTP, the logger logs in the correct format only outside an `Http`, but inside the `Http` the logger format is the default one.

**To Reproduce**
Run this program:

```scala
object Main extends ZIOAppDefault {
  val app = Http.collectZIO[Request] { case Method.GET -> !! =>
    ZIO.logInfo("this is a message") *> // this is logged in the default format
    ZIO.succeed(Response.ok)
  }

  def run = {
    val logger = Runtime.removeDefaultLoggers >>> SLF4J.slf4j(LogLevel.All, LogFormat.line, _ => "zio-rest-api")
    val program = for {
      _ <- ZIO.logInfo("Starting app") // this logs fine
      app <- Server.start(8090, app)
    } yield app
    program.provide(logger)
  }
}
```

**Expected behaviour**
Both "Starting app" and "this is a message" should be logged in the SLF4J format.

**Additional context**
I'm using Scala 3.1.3, ZIO HTTP 2.0.0-RC10, ZIO 2.0.0, and ZIO Logging 2.0.0.

Many thanks 🙂

**Comment by jgoday** [comment]
Hi, I may be wrong but it seems to be because Server.start creates an inner runtime to handle all the requests, that does not inherits the provided logger layer.

If we add the logger layer to the Http app it should work

```scala
val program = for {
      _   <- ZIO.logInfo("Starting app")                  // this logs fine
      app <- Server.start(8090, app.provideLayer(logger))
} yield app
```

**Comment by beneyal** [comment]
In RC9 it worked without the additional `.provideLayer` to `app`, but I tried this approach and it works!

Thank you so much!

@tusharmath Do you want me to close the issue, or do you want to keep track of it?

**Comment by tusharmath** [comment]
I think we can fix this in the runtime. Let me give it a shot.

**Comment by lachezar** [comment]
I just created a small app that demonstrate the same issue and I was about to open a ticket, when I finally found this one 🤦‍♂️

Anywho, here is small demo app that shows the issue https://github.com/lachezar/zio-http-logging-issue/blob/master/src/main/scala/Main.scala

**Comment by gciuloaica** [comment]
I have open this issue on ZIO https://github.com/zio/zio/issues/7138

**Comment by adamgfraser** [comment]
You can use `ZIO.loggers` to access the current loggers though I think this is actually a more general issue and you want to capture all `FiberRef` values and propagate them to the new runtime.

**Comment by adamgfraser** [comment]
@tusharmath Let me know if you want help with this.

**Comment by gciuloaica** [comment]
@adamgfraser to avoid doing any context switch, in  `HttpRuntime` we are defining a `sticky` strategy where each EventLoop from EventLoopGroup (group of netty thread pools) has a corresponding `Runtime` instance. Ideally each `Runtime` instance should be the same with the initial `Runtime` but has a different executor attached.
