### ISSUE TITLE
Websocket no interaction just streaming to the client

### ISSUE THREAD

**Issue by Dennis4b** [zio/zio-http#1356]
Hi,

For my use case the client establishes a websocket connection, and the server streams events from a `ZStream` to the client, mixed with keepalives. The client does not otherwise talk to the server over the websocket connection.

Previously (before the refactoring that went into `-RC10`) I would have
```scala
SocketApp()
.onOpen(
    Socket.fromStream(myMessageStream)
)
```

but that API has been removed.

The examples I can find all show a `message-triggers-response` workflow, but this doesn't apply to use-case of only streaming to the client.

I currently have it working by spawning a fiber that reads from the stream and shoves the messages into the websocket channel, with an ugly `var` to keep a reference to the fiber to interrupt it later, like:

```scala
var streamingFiber = Option.empty[..]
Http.collectZIO[WebSocketChannelEvent]{
    case ChannelEvent(ch, UserEventTriggered(UserEvent.HandshakeComplete)) => {
        val streamingTask = myMessageStream.foreach(msg => ch.writeAndFlush(msg)).repeat(..).forkDaemon.etc
        // start Fiber and save to streamingFiber variable
    }
    case ChannelEvent(ch, ChannelUnregistered) => {
       streamingFiber match {
            case None => ZIO.unit
            case Some(f) => for {
                _ <- f.interrupt
                _ <- f.await
            } yield ()
       }
    }
```

Is there any easier (cleaner) way?

Of course, now that we're not worrying about IE11 anymore Server-Sent-Events would be a better fit, perhaps even just long-polling, but I'm still curious what the correct way to "push" to a websocket is.

**Comment by tusharmath** [comment]
You could try something like this with a Queue — 

```scala
Http.collectZIO[WebSocketChannelEvent] { case ChannelEvent(ch, UserEventTriggered(HandshakeComplete)) =>
    (for {
      msg   <- queue.take
      _     <- ch.writeAndFlush(WebSocketFrame.text(msg))
    } yield ()).forever.race(ch.awaitClose)
  }
```

**Comment by Dennis4b** [comment]
Aha I somehow thought I have to "return" from the `collectZIO` handler (that events within one channel are serialized), thus the fiber ref.

Your solution works perfectly, I particularly love the `.race(ch.awaitClose)`, so much happening in such a casual statement. Thank you!
