### ISSUE TITLE
release note for v2.0.0-RC10 has wrong changelog

### ISSUE THREAD

**Issue by pjfanning** [zio/zio-http#1357]
https://github.com/dream11/zio-http/releases/tag/v2.0.0-RC10

Has:
`Full Changelog: https://github.com/dream11/zio-http/compare/v1.0.0.0-RC28...v2.0.0-RC10`

Should probably be:
`Full Changelog: https://github.com/dream11/zio-http/compare/v2.0.0-RC9...v2.0.0-RC10`

**Comment by gciuloaica** [comment]
@pjfanning Change log is correct. Before this release the main branch was the branch for v1.0.0. All the v2.0.0 RC releases has been done from a branch from where we port the changes done in main branch to ZIO 2.0 RCs. So all the released changes were included in previous release. With ZIO 2.0 release we basically migrated from v1.0.0 to v2.0.0 by migrating main branch code base from ZIO 1.0 to ZIO 2.0. The change log is correct.

**Comment by pjfanning** [comment]
Thanks for the update - I'll close this.
