### ISSUE TITLE
No way to verify cookie signature

### ISSUE THREAD

**Issue by govorov** [zio/zio-http#1383]
Good evening dear team,

As far as I understand, there's no clear way to verify the signature of a request cookie (as of v1.0.0.0-RC29)
There's the `verify` method in `Cookie`, but it's private.

What's the right way of verifying incoming cookies then?
Ideally, I'd expect the server to verify signatures during decoding (like here for example https://github.com/pillarjs/cookies)

Thank you.

**Comment by tusharmath** [comment]
I think we can make the method public. 

At the moment you should get a `None` if the signature doesn't match. 
Is there a use case where you would like to read cookies that aren't verified?
