### ISSUE TITLE
HTTP model for Character sets

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#14]
HTTP uses Internet media types defined in RFC 2046. Some media types such as `text/plain` or `text/html` can optionally declare the character set.

Relevant links:
- [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.1)
- [RFC 2046](https://tools.ietf.org/html/rfc2046#section-4.1)

Create a representation for Character sets in `zio.http.Charset`.

**Comment by saraiva132** [comment]
@ioleo I will make a draft for this.
