### ISSUE TITLE
Decompression for client

### ISSUE THREAD

**Issue by fokot** [zio/zio-http#1413]
**Is your feature request related to a problem? Please describe.**
I'm using zhttp client and then I need to process results. They are compresses. Is it possible to set it up to decompress response for me? I'm using newest `2.0.0-RC11` and found only `Server.requestDecompression(..)`. `Server.responseCompression(..)` is not there. Should it be supported here, or it needs to be added? Thanks

**Describe the solution you'd like**
Add setting to client to automatically decompress the responses for me. Maybe to the request method? Or rather globally to `ChannelFactory`?

**Describe alternatives you've considered**
I'm doing it manually in the code right now.

**Comment by girdharshubham** [comment]
@fokot  There's already a PR for that: #1397

**Comment by fokot** [comment]
@girdharshubham but that one is for server. Pipeline is appended only in `ServerChannelInitializer` and not in `Client`. Maybe you can add the same in the PR to client.

**Comment by fokot** [comment]
Implemented in #1538
