### ISSUE TITLE
Missing artifact for zhttp-logging_2.13:1.0.0.0-RC28

### ISSUE THREAD

**Issue by SelwynL** [zio/zio-http#1428]
**Describe the bug**
Using version `1.0.0.0-RC28` with Scala `2.13` seems to result in the following error:
```
sbt.librarymanagement.ResolveException: Error downloading io.d11:zhttp-logging_2.13:1.0.0.0-RC28
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `"io.d11" %% "zhttp" % "1.0.0.0-RC28"` to a Scala 2.13 project
2. Run `sbt compile`

**Expected behaviour**
The `io.d11:zhttp-logging_2.13:1.0.0.0-RC28` artifact to be published

**Comment by tusharmath** [comment]
Please use `2.0.0-RC11` instead.
