### ISSUE TITLE
Organize HTTP model classes into separate package

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1447]
**What is not easy to do right now?**

All high-level data types and service types are located in the `zio.http` package, which makes navigating code more difficult and introduces the possibility of name clashes, with common names like `Headers` and `Cookies` used up by data types.

**Describe the solution you'd like**

Move all pure data classes that model aspects of the Http protocol into a new package `zio.http.model`, following the pattern of Tapir, Spray, and other Scala libraries.

**Why is it important?**

Better to do it now when the number of data types is small, than later after a stable release.

**Comment by 987Nabil** [comment]
I'll do this

**Comment by adamgfraser** [comment]
Awesome!
