### ISSUE TITLE
Move all internal traits and classes to `zio.http.internal` package

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1449]
**What is not easy to do right now?**

Many internal implementation details of the library that should only ever be seen by maintainers or very advanced users are visible in the organizational details and generate Scaladoc.

**Describe the solution you'd like**

Move internal implementation details (including internal traits) to an internal package, with package-private access modifiers, so that only end-user data types appear in the public API.

**Why is it important?**

Improving user experience and consistency with ZIO Core.

**NOTE**: Much of these are currently in `zio.http.services`.

**Comment by senia-psm** [comment]
I want to take this.
