### ISSUE TITLE
Add Middleware that does response logging using ZIO 2 Logging

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1451]
**Is your feature request related to a problem? Please describe.**

Response logging is a standard feature of some web servers. It is possible to add response logging now into any ZIO HTTP server, but it requires writing custom code, particularly if the end-goal is to pipe that response logging through the ZIO 2 logging front-end, to benefit from the work done in supporting different logging backends in the ZIO Logging project.

**Describe the solution you'd like**

Middleware that does industry-standard response logging using ZIO 2 integrated logging, including request timings.

**Describe alternatives you've considered**

Writing custom code to do the same.

**Comment by swoogles** [comment]
I'll look into this.
Do we have a clear spec for "industry-standard response logging" ?

**Comment by jdegoes** [comment]
No but some inspiration can be taken from [httpd](https://httpd.apache.org/docs/current/mod/mod_log_config.html#page-header) or Nginx.

**Comment by swoogles** [comment]
Looking at those 2, I lean towards Nginx, which uses full words:
```
$remote_addr
$remote_user
```

Httpd is more cryptic/terse with single letter options. I don't think stuff like this is user-friendly:
```
%u       | Remote user if the request was authenticated. 
%U       | The URL path requested, not including any query string.
```

**Comment by jdegoes** [comment]
Oh I agree and I am not even suggesting user-configurability in these tickets. Just choosing some reasonable defaults for request/response logging.

The docs can be taken as a reference to what sort of things these servers are capable of embedding into the access logs.

**Comment by swoogles** [comment]
`I am not even suggesting user-configurability`
Ah, good to know, I was starting down that rabbit hole 🙂

**Comment by swoogles** [comment]
Looks like I can't assign the ticket to myself in this repo for some reason, but I'll claim this one.
You can assign it to me when convenient.
