### ISSUE TITLE
Move all major end-user facing parts of the API to zio.http

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1454]
**What is not easy to do right now?**

The part of the API that a user should invest time in learning is not easy to discover, with some important websocket abstractions being located in the `socket` package (for example).

**Describe the solution you'd like**

Relocate all major end-user facing parts of the API to the zio.http package.

**Why is it important?**

It will improve discoverability of the API, and improve similarity to ZIO, which tries to expose all major parts under `import zio._`.

**Comment by jaliss** [comment]
@jdegoes I'm going to start working on this.
