### ISSUE TITLE
Add endpoints DSL that can be used to generate docs, clients, etc.

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1455]
**Is your feature request related to a problem? Please describe.**

Two issues:

1. The routing works by "first matches", and does not take advantage of the tree-like nature of URLs. As such, finding the correct handler is `O(n)` in the total number of API end points, but it should be `O(log n)` instead.
2. It is not possible to generate docs or type-safe clients or client libraries in other programming languages from ZIO HTTP server specifications.

**Describe the solution you'd like**

A clean and type-safe endpoints DSL based on ZIO Schema.

**Describe alternatives you've considered**

Tapir.

**Comment by tusharmath** [comment]
I think the current time complexity for route matching in `O(n^2)`, considering `n` routes 
of length `n`.

I think the optimization will have time complexity of `O(n)` if we use a Trie of alphanumeric chars.

**Comment by jdegoes** [comment]
@tusharmath I think it's `O(n*m)` where `m` is the path length and `n` is the number of routes. Given the path length is effectively capped to 2k for any route, you can treat `m` as a constant, making it `O(n)` in the number of routes, which can be reduced to `O(log n)` with a trie of path segments.

I see that Gin already implemented this performance trick, but as far as I can see, it is unique in Scala frameworks. 

Will close this ticket as it's already been implemented.
