### ISSUE TITLE
Export default metrics under zio.http.*

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1459]
**Is your feature request related to a problem? Please describe.**

ZIO HTTP does not currently export any metrics using ZIO 2 integrated metrics.

**Describe the solution you'd like**

Integrated ZIO 2-based metrics could include the following:

1. Request count (counter) "zio.http.requests"
2. Response broken down by status code (counter with status code in name or tagged counter) "zio.http.status.502"
3. Request duration (histogram)
4. A gauge of concurrent requests "zio.http.concurrent_requests"

I suggest these be turned on with a `Middleware`, e.g. `Middleware.metrics`.

**Describe alternatives you've considered**

Pushing it into a third-party library.

**Comment by swoogles** [comment]
I haven't done much with ZIO metrics yet, but I'll give this a try.

**Comment by swoogles** [comment]
Sigh, well this makes ticket #2 that I've worked on this week that was duplicate work.
I didn't realize PR #1394 existed until refreshing this page just now.

Branch is here: https://github.com/zio/zio-http/compare/main...swoogles:zio-http:create_metrics_middleware?expand=1
I was just wrapping up today, so I don't have time to see where it stands in comparison to the work @frekw has already done, but I will look into it tomorrow.

**Comment by frekw** [comment]
@swoogles I think they're pretty similar. I think the big difference is that by using `interceptZIOPatch` as in your branch we won't be able to catch error or defects, which we definitely want to have metrics for as well.
