### ISSUE TITLE
Publish ZIO Http under `dev.zio`

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#1473]
When trying to install according to the docs:

```
libraryDependencies += "dev.zio" %% "zio-http" % "2.0.0-RC11"
```

I'm getting:
```
sbt.librarymanagement.ResolveException: Error downloading dev.zio:zio-http_3:2.0.0-RC11
```

also tried
```
libraryDependencies += "dev.zio" %% "zio-http" % "2.0.0-RC11" cross CrossVersion.for3Use2_13
```

I'm getting:
```
sbt.librarymanagement.ResolveException: Error downloading dev.zio:zio-http_2.13:2.0.0-RC11
```

The only artifact that resolves is `"io.d11" %% "zhttp" % "2.0.0-RC11"`, however that seems to contain a completely diffrent (outdated) version - eg. the package prefix is `zhttp` instead of `zio.http`, `Server` is in `service` subpackage.

How do I install and use the latest version?

**Comment by vigoo** [comment]
Version in zio org not published yet

**Comment by tusharmath** [comment]
Let's keep the issue open, until it's resolved @vigoo.
Pinning it so that everyone is aware.

**Comment by ioleo** [comment]
FYI: I got it working by using `d11` and `2.0.0-RC10` (RC11 conflicted with tapir).

**Comment by changzhiwin** [comment]
This is a serious problem. I can't get `"dev.zio" %% "zio-http" % "2.0.0-RC11"` dependence, and d11's document site was removed.

**Comment by changzhiwin** [comment]
It's not work for me also. Anyone can tell me how to fix the dependence setting?

```
val ZIOVersion = "2.0.2"
val ZIOHttpVersion = "2.0.0-RC11"
// val ZIOHttpVersion = "2.0.0-RC11+49-fc62691f-SNAPSHOT"

resolvers ++= Seq(
  "Secured Central Repository" at "https://repo1.maven.org/maven2"
  //"Sonatype snapshots" at "https://oss.sonatype.org/service/local/repositories/snapshots/content/"
)

libraryDependencies ++= Seq(
  "dev.zio" %% "zio" % ZIOVersion, 
  "dev.zio" %% "zio-http" % ZIOHttpVersion
)
```

**Comment by vigoo** [comment]
Note that there were still no new release since it moved into the ZIO organization, this ticket was just closed because the publishing settings were fixed in the repo.

**Comment by vigoo** [comment]
Reopened to avoid confusion

**Comment by changzhiwin** [comment]
> Reopened to avoid confusion

Thanks, it's really confuse me. Though I fix this locally by  using `publishLocal ` command(both `zio-http` and `zio-http-logging`).

**Comment by ploddi** [comment]
`zio-http` snapshots can be found here -- https://oss.sonatype.org/#nexus-search;quick~zio-http_2.13
but `zio-http-logging` snapshots are missing still and it will leads to sbt errors.

Can `zio-http-logging` snapshots be also published, so we at least can use snapshot versions until official release?

**Comment by changzhiwin** [comment]
@ploddi Wait a moment, and using `publishLocal` for current development.

**Comment by vigoo** [comment]
I think this is solved now

**Comment by martintamb12** [comment]
> 

What do you mean when saying using publishLocal?
