### ISSUE TITLE
Add .toJson methods to OpenAPI data types

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1499]
**Is your feature request related to a problem? Please describe.**

The `zio.http.api.openapi.*` family of data types is an ADT to describe OpenAPI documentation. The ADT is strongly typed and incorporates data types from `zio.http.model`, as well as ZIO and the Scala standard library.

While useful, this ADT cannot currently be translated into rendered JSON, which impedes other tickets.

**Describe the solution you'd like**

Add `def toJson: String` methods to all OpenAPI data types, which directly render the OpenAPI data types to JSON, using some utility JSON class, but without introducing a dependency on a third-party JSON library (which is unnecessary for pure rendering).

**Describe alternatives you've considered**

Using `zio-json` to perform the serialization, but that forces us to use a schema that may not be ideal, and makes the code fragile to changes, as well as introducing a direct dependency on a JSON library for both client and server use cases.

**Additional context**

The [OpenAPI specification](https://swagger.io/specification/) has details on how the OpenAPI information should be encoded in JSON or YAML formats.

**Comment by 987Nabil** [comment]
I'll do this 🙂

**Comment by 987Nabil** [comment]
@jdegoes In the `OpenAPI` case class `externalDocs` is `Doc` which is an ADT that represents a full documentation. But the open api specs say it should be an object with two fields. Namely `description` and `url` (which is required) that leads to an external documentation. I can understand, that we might want to create this external docs in zio-http ourselves and link it, but it seems not to be possible for this issue. Should I just not render it, since it is optional anyway?

EDIT:
I just thought, that I could as a temporary solution render the doc as description and the URL is just `/`?

**Comment by 987Nabil** [comment]
I just realised, `Doc` is also used for the `description` fields. Which according to the spec, must be a string, that supports markdown. But `Doc` can currently only be rendered to html or plain text. I can use plain text in this cases, but maybe a markdown rendering for `Doc` should be added.

**Comment by jdegoes** [comment]
@987Nabil `Doc` is just intended to allow the user to write additional snippets of (possibly) formatted text, which appear in-line in the OpenAPI generated documentation.

In many places in OpenAPI, we can embed Markdown or HTML, and in some places, I think, only plaintext is supported. 

I will create a ticket to add `toMarkdown`. Until then, I believe `CommonMark` supports HTML so the `toHTML` should work.

**Comment by jdegoes** [comment]
@987Nabil By the way, I am not sure that the data types in `OpenAPI` use `Doc` correctly. In fact, I am pretty sure they do not. We should aim to incorporate `Doc` into the OpenAPI data types wherever any formatted text is supported. 

We should not try to use `Doc` as a linkage mechanism for external docs (that is, stored externally to the generated JSON).

**Comment by 987Nabil** [comment]
> @987Nabil `Doc` is just intended to allow the user to write additional snippets of (possibly) formatted text, which appear in-line in the OpenAPI generated documentation.
> 
> In many places in OpenAPI, we can embed Markdown or HTML, and in some places, I think, only plaintext is supported.
> 
> I will create a ticket to add `toMarkdown`. Until then, I believe `CommonMark` supports HTML so the `toHTML` should work.

I think it supports a subset of html. I could do the `toHTML`, but it might not be valid.

**Comment by 987Nabil** [comment]
@jdegoes There are some places in the API, that define fields as type of `Any`. In the current Scala code, this is impl. for two fields of `Link`. The `requestBody: Any` and `parameters: Map[String, Any]`. 
I am not really sure how to render this and even if this is a good definition in the code itself. Maybe it would be ok to be more restrictive than what swagger allows?
Maybe this is something to defer to #1498? What would restrictions mean for #1520. I guess generating `API` for `Any` is not possible anyway. 🤷‍♂️
