### ISSUE TITLE
Properly support content type headers in zio.http.api

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1506]
**Is your feature request related to a problem? Please describe.**

Currently, `EndpointClient` and `EndpointServer` in `zio.http.api.internal` do not perform an adequate job supporting and respecting content type headers.

**Describe the solution you'd like**

Modify the client and server to respect and generate the appropriate content type headers, and enhance the architecture to support any one of the protocols supported by ZIO Schema, which powers the current JSON support.

**Describe alternatives you've considered**

None.

**Additional context**

See `/src/main/scala/zio/http/api/internal/` `EndpointClient.scala` and `EndpointServer.scala`.

**Comment by jdegoes** [comment]
In particular, since ZIO Schema supports several different protocols, including gRPC, endpoints should properly support those protocols, based on `Accept` headers.

**Comment by SHSongs** [comment]
I'm interested in it.

**Comment by 987Nabil** [comment]
@jdegoes the only protocol besides json, that zio-schema supports and does have an official mime-type is [thrift](https://www.iana.org/assignments/media-types/media-types.xhtml).
protobuf for example does not have one.
I would suggest, that users can configure on which accept header to reply with which protocol. And that this config has default values for json and thrift. We could also add default values for protobuf for example, that has commonly used values, even if they are not official. But I think to make it configurable is needed to make it usable in the wild.

**Comment by jdegoes** [comment]
@987Nabil I would rather not make it configurable and choose based solely on `Accept`, because making it configurable will require figuring out a difficult API, whereas the main task here is just plumbing and architecture and tests, which doesn't require any R&D.

**Comment by jdegoes** [comment]
`application/protobuf` is as close to standard as it gets for Protobuf. Official standards seem to get hung up on the question of determining message type, which we don't need for microservices because we generate the client which knows the type.

**Comment by 987Nabil** [comment]
@jdegoes but which accept values? There is no standard.

**Comment by 987Nabil** [comment]
Let's say that is okay for protobuf and the case you described. What about the other formats?
What about the case that users don't own both sides?
