### ISSUE TITLE
Create CharSequenceExtensions to help consolidate CharSequence-related code

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1510]
**Is your feature request related to a problem? Please describe.**

ZIO HTTP tries to use `CharSequence` which can be backed by entities other than `String`, which helps because `String` must always be decoded into bytes before it can be written to sockets, and other entities can have this logic baked in. 

However, `CharSequence` have undefined equality and hash code, and there is no way to test for substrings (etc.).

**Describe the solution you'd like**

To rectify these problems, we can create `CharSequenceExtensions` object in `zio.http.internal`, which contains a few helper functions:

```scala
def equals(left: CharSequence, right: CharSequence): Boolean = compare(left, right) == 0
def compare(left: CharSequence, right: CharSequence): Int = ???
def hashCode(c: CharSequence): Int = ??? // computed like String.hashCode
def contains(sequence: CharSequence, subsequence: CharSequence): Boolean = ???
...
```

In addition, the methods in `Headers.scala` which compare char sequences and compute their hash code can be refactored to use the new helpers in `CharSequencExtensions`.

**Describe alternatives you've considered**

N/A

**Additional context**

Equality should be implemented to short-circuit on reference equality: `if (left eq right) true else { /* longer more expensive computation */ }`.

**Comment by tusharmath** [comment]
There should be a case-insensitive option also for all the operators. 
We can pass an optional boolean or create specific operators like - `iequals, icompare, icontains` etc.

**Comment by jdegoes** [comment]
Good suggestion, maybe:

```scala
sealed trait CaseMode
object CaseMode {
  case object Sensitive extends CaseMode
  case object Insensitive extends CaseMode
}
```
