### ISSUE TITLE
Optimize Headers#get

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1511]
**Is your feature request related to a problem? Please describe.**

`Headers#get` has a quick and dirty implementation that is extremely inefficient. This method is intended to get the first header having a certain name.

**Describe the solution you'd like**

Implement `Headers#get` by implementing it in the subtypes of `Headers`, which is about as fast as we can get without having an index. Take care to perform minimal allocations, always using low-level APIs rather than high-level APIs.

**Describe alternatives you've considered**

N/A

**Additional context**

The API now returns an `Option` but we could introduce an even-lower level `Unsafe` API that returns `null`, which is package-private to `http`, and which can be used by the code inside `zio.http.api` for improved performance.

**Comment by jakubjanecek** [comment]
I'd like to give this a try.
