### ISSUE TITLE
Get benchmarks running on CI and fail the build on any performance regression

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1515]
**Is your feature request related to a problem? Please describe.**

In order to both encourage broad contributions, as well as maintain performance of ZIO HTTP, it is necessary to both include benchmarks as part of CI, and fail the build if some degradation is detected.

**Describe the solution you'd like**

Have benchmarks run reliably as part of CI (even on pull requests submitted on forks!), ideally hosted in the ZIO org, and fail the build on regressions.

**Describe alternatives you've considered**

None

**Additional context**

This used to be working on the Dream11 repo.

**Comment by vigoo** [comment]
This is working now
