### ISSUE TITLE
Implement code generator that takes OpenAPI and generates zio.http.api.EndpointSpec code

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1520]
**Is your feature request related to a problem? Please describe.**

Some companies begin with OpenAPI, and then proceed to implement a server that satisfies the OpenAPI specification; then they will modify the OpenAPI specification when a change is necessary, and then re-implement the server.

**Describe the solution you'd like**

In order to support this _spec-first_ driven approach to API development (rather than _code-first_, which is the paradigm already implemented within the `zio.http.api` package), we will need a code generator, which can read in OpenAPI specification, and generate the corresponding `zio.http.EndpointSpec ` values that declaratively describe the APIs.

Then a user can implement handlers based on the code-generated `EndpointSpec ` values.

**Comment by 987Nabil** [comment]
I am on this

**Comment by johannegger** [comment]
Hi! 
is there progress on this? I'd love to try it out!

**Comment by sideeffffect** [comment]
There's been some work on that here: https://github.com/guardrail-dev/guardrail/pull/1615

**Comment by 987Nabil** [comment]
I am still on it. The goal is, that it will be part for the first non RC release. If it might make it into an RC release before that, I am not sure about.

**Comment by kitlangton** [comment]
I'm gonna give this a shot :D If it proves to be too hairy, I'll relinquish the claim as soon as I realize that.

Update: Nabil is working on this :) I've switched over to the CI Benchmarking issue.

**Comment by kitlangton** [comment]
I don't know how to unclaim—but I [unfortunately don't have time to finish this](https://github.com/zio/zio-http/pull/2357#issuecomment-1662342217)

**Comment by xonx4l** [comment]
@jdegoes can you assign it to me??

**Comment by 987Nabil** [comment]
@xonx4l Sorry, I forgot to mention this here, but I am already on this, based on my work of the other direction. See #2470 

/attempt #1520

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clhf0v5nk000ml60f2a4wr7sl/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by sankalp142002** [comment]
/attempt #1520


<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clhf0v5nk000ml60f2a4wr7sl/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
