### ISSUE TITLE
Implement a code generator that takes protobufs and generates zio.http.api.EndpointSpec values

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1521]
**Is your feature request related to a problem? Please describe.**

Some companies begin with protobufs for gRPC, and then proceed to implement a server that satisfies the protobuf specification; then they will modify the protobuf specification when a change is necessary, and then re-implement the server.

**Describe the solution you'd like**

In order to support this _spec-first_ driven approach to API development (rather than _code-first_, which is the paradigm already implemented within the `zio.http.api` package), we will need a code generator, which can read in protobuf specification, and generate the corresponding `zio.http.EndpointSpec ` values that declaratively describe the APIs.

Each gRPC service definition should translate into a single `EndpointSpec ` definition.

Then a user can implement handlers based on the code-generated `EndpointSpec ` values.

**Comment by 987Nabil** [comment]
@jdegoes @adamgfraser Is this not what zio-grpc is doing, just adjusted to the new API design?
Should this be added to zio-http? Or should this live in zio-grpc?
If it would be added to zio-http, would we use scalapb to parse the messages need for the service?
Or would we just create an interface/trait for the messages? I think messages to case classes makes more sense.

**Comment by jdegoes** [comment]
I think we generate both the EndpointSpec and the case classes from the protobufs, and use ZIO Schema to do the encoding / decoding.

**Comment by dejvid** [comment]
This would be great to add. Is anyone working in this?

**Comment by 987Nabil** [comment]
@dejvid I don't think so. I am focusing on OpenAPI currently and that is also planned for the 3.0 release afaik. I might work on protobuf afterwards, but maybe this would not be part of the next release. If you like to work on it, feel free ofc ;)

**Comment by gstrainovic** [comment]
I will work on it.

**Comment by digital-phoenix** [comment]
@jdegoes What's the current status of this issue?

**Comment by adamgfraser** [comment]
@digital-phoenix Looks like someone was working on it but that was quite a while ago so if you are interested you should feel free to pick it up.

**Comment by pablf** [comment]
/attempt #1521

<div id="algora" />

| [Algora profile](https://console.algora.io/@/pablf) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @pablf | 23 ZIO bounties | <div align="center">Scala, Rust</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clhf0u3ly000al60f8dm7o5ln/cancel-attempt) |
