### ISSUE TITLE
Improve headers codecs in zio.http.api to operate on structured data

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1524]
**Is your feature request related to a problem? Please describe.**

The header inputs, which one can construct using `zio.http.api.HttpCodec`, and which are defined in `/src/main/scala/zio/http/api/HeaderCodecs.scala`, currently produce (/accept) a `String` value, which is unstructured.

Unstructured data is more difficult to work with and may lead to protocol errors if the user does not happen to generate or parse exactly the right header value structure.

**Describe the solution you'd like**

In order to provide a safer and more useful way to interact with header values, we can change the definitions to accept/produce structured values. For example, instead of `HeaderCodec.accept` returning type `HeaderCodec[String]`, it could return type `HeaderCodec[MimeType]`, for some sealed trait `MimeType`. This can be done by utilizing the `HeaderCodec#transform` method, and by implementing a pair of highly-optimized conversion functions: one to convert the string to a specialized, type-safe data type, and the other, to convert the type-safe data type to a string.

The `HttpCodec` data type is located in `src/main/scala/zio/http/api/HeaderCodec.scala`. The new type-safe data types for header values should be located in `zio.http.model` (maybe in the headers subpackage?).

Given the scope of this work, each person who wants to work on this should pick one of the following headers to work on, claim that in the comments below, and submit a pull request for that specific header. When completed, the box may be checked.

 - [x] accept
 - [x] acceptCharset
 - [x] acceptEncoding
 - [x] acceptLanguage
 - [x] acceptRanges
 - [x] acceptPatch
 - [x] accessControlAllowCredentials
 - [x] accessControlAllowHeaders
 - [x] accessControlAllowMethods
 - [x] accessControlAllowOrigin
 - [x] accessControlExposeHeaders
 - [x] accessControlMaxAge
 - [x] accessControlRequestHeaders
 - [x] accessControlRequestMethod
 - [x] age
 - [x] allow
 - [x] authorization
 - [x] cacheControl
 - [x] connection
 - [x] contentBase
 - [x] contentEncoding
 - [x] contentLanguage
 - [x] contentLength
 - [x] contentLocation
 - [x] contentTransferEncoding
 - [x] contentDisposition
 - [x] contentMd5
 - [x] contentRange
 - [x] contentSecurityPolicy
 - [x] contentType
 - [x] cookie
 - [x] date
 - [x] dnt
 - [x] etag
 - [x] expect
 - [x] expires
 - [x] from
 - [x] host
 - [x] ifMatch
 - [x] ifModifiedSince
 - [x] ifNoneMatch
 - [x] ifRange
 - [x] ifUnmodifiedSince
 - [x] lastModified
 - [x] location
 - [x] maxForwards
 - [x] origin
 - [x] pragma
 - [x] proxyAuthenticate
 - [x] proxyAuthorization
 - [x] range
 - [x] referer
 - [x] retryAfter
 - [x] secWebSocketLocation
 - [x] secWebSocketOrigin
 - [x] secWebSocketProtocol
 - [x] secWebSocketVersion
 - [x] secWebSocketKey
 - [x] secWebSocketAccept
 - [x] secWebSocketExtensions
 - [x] server
 - [x] setCookie
 - [x] te
 - [x] trailer
 - [x] transferEncoding
 - [x] upgrade
 - [x] upgradeInsecureRequests
 - [x] userAgent
 - [x] vary
 - [x] via
 - [x] warning
 - [x] webSocketLocation
 - [x] webSocketOrigin
 - [x] webSocketProtocol
 - [x] wwwAuthenticate
 - [x] xFrameOptions
 - [x] xRequestedWith

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by tobia80** [comment]
Added https://github.com/zio/zio-http/pull/1551 for acceptCharset

**Comment by devsprint** [comment]
Added #1552 for CacheControl

**Comment by jakubjanecek** [comment]
Created #1576 for `Origin`.

**Comment by jakubjanecek** [comment]
Created #1581 for `Accept`.

**Comment by ccerbusca** [comment]
Added #1593 for `Allow`

**Comment by wpoosanguansit** [comment]
Added https://github.com/zio/zio-http/pull/1632 for Connection

**Comment by ccerbusca** [comment]
Added #1630 for Accept-Language

**Comment by geoffjohn11** [comment]
Added https://github.com/zio/zio-http/pull/1640 for Host

**Comment by wpoosanguansit** [comment]
Added https://github.com/zio/zio-http/pull/1643 for Expires

**Comment by wpoosanguansit** [comment]
Added https://github.com/zio/zio-http/pull/1644 for Expires

**Comment by wpoosanguansit** [comment]
Added https://github.com/zio/zio-http/pull/1645 for AccessControlMaxAge

**Comment by wpoosanguansit** [comment]
Added https://github.com/zio/zio-http/pull/1648 for Content-Encoding

**Comment by geoffjohn11** [comment]
Is anyone looking into Server header?

**Comment by geoffjohn11** [comment]
Added https://github.com/zio/zio-http/pull/1674 for server header

**Comment by jakubjanecek** [comment]
I'm working on `Authorization` header. I'll submit a PR soon.

**Comment by jdegoes** [comment]
Any individual item above will count for a ticket in the _ZIO Hackathon 2022_, for those of you participating.

**Comment by cyb3rn3t1c1an** [comment]
I'd like to work on `accessControlAllowMethods`

**Comment by lemony312** [comment]
I can take `retryAfter`

**Comment by walesho** [comment]
Working on `location`

**Comment by sf17490** [comment]
I'd like to work on ```warning```

**Comment by arumus** [comment]
i can take `transferEncoding`

**Comment by cyb3rn3t1c1an** [comment]
I'll work on `acceptRanges`, `ifRange` and `expect`

**Comment by 987Nabil** [comment]
I am working on all content related stuff for #1703

**Comment by devsprint** [comment]
acceptControlAllowCrdentials #1803

**Comment by vigoo** [comment]
Seems to be done
