### ISSUE TITLE
Support streaming in Client

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1527]
**Is your feature request related to a problem? Please describe.**

Many APIs provide very large responses, for example, S3, in which it is possible to download a large file or stream a video. 

**Describe the solution you'd like**

Comprehensive, performant, and rock-solid support for streaming in Client.

**Describe alternatives you've considered**

None.

**Additional context**

Need scope.

**Comment by devsprint** [comment]
In current implementation, Client streaming it is enabled when the netty's `ObjectAggregator` is not present in the pipeline.

**Comment by devsprint** [comment]
- [ ] Client response streaming should be enabled based on `Transfer-Encoding` header value.
- [ ] Add implementation for Client Request streaming - send data to server (POST, PUT) using chunked request.

**Comment by kmatasfp** [comment]
I will take it
