### ISSUE TITLE
Comprehensive test suite for ZIO HTTP API endpoints

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1529]
**Is your feature request related to a problem? Please describe.**

`zio.http.api` lacks tests for client and server, for happy and unhappy paths.

**Describe the solution you'd like**

Develop one test suite for the client, one for the server, which test both happy and unhappy paths.

**Describe alternatives you've considered**

None.

**Additional context**

Goal should be relatively high level of code coverage of `zio.http.api`.

**Comment by jupposessho** [comment]
I am working on this one.
