### ISSUE TITLE
Introduce benchmark for ZIO HTTP API

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1530]
**Is your feature request related to a problem? Please describe.**

`zio.http.api` has no benchmark. A variety of benchmarks should be added so that optimization may proceed in a data-driven way.

**Describe the solution you'd like**

 - [x] A benchmark that tests simple request/response of small data
 - [ ] A benchmark that tests simple request/response of large data
 - [x] A benchmark that tests dispatch to a large number of similar routes (benefits from radix tree)
 - [ ] A benchmark that tests performance of unhappy path (no matches)
 - [ ] A benchmark that tests performance of unhappy path (malformed data)

Ideally, each benchmark would come with a version for ZIO HTTP API, and another version for an equivalent in the space (e.g. Tapir on Akka HTTP).

**Describe alternatives you've considered**

None.

**Comment by kitlangton** [comment]
@adamgfraser and I are taking this

**Comment by jdegoes** [comment]
🙏
