### ISSUE TITLE
Wholly intern benchmarking

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1531]
**Is your feature request related to a problem? Please describe.**

All benchmarks should live inside the ZIO organization.

**Describe the solution you'd like**

Move benchmarks into the ZIO organization.

**Describe alternatives you've considered**

None.

**Comment by jdegoes** [comment]
See [here](https://github.com/zio/FrameworkBenchmarks)

**Comment by vigoo** [comment]
I think this is done
