### ISSUE TITLE
Http.catchAllCause

### ISSUE THREAD

**Issue by fokot** [zio/zio-http#1539]
**Is your feature request related to a problem? Please describe.**
`Http.catchAllDefect` gives me ability to handle `Throwable`s. But they do not have nice stack trace information as `Cause`. It would be nice to have method to handle `Cause` as well. Now when I want to log the error in an application I will log every endpoint separately as there I can do `ZIO.foldCauseZIO` and get tracing information.

**Comment by adamgfraser** [comment]
I'm working on this.
