### ISSUE TITLE
Multipart form data server support

### ISSUE THREAD

**Issue by fokot** [zio/zio-http#1559]
**Is your feature request related to a problem? Please describe.**
Server can accept and parse Multipart form data requests.

**Describe the solution you'd like**
Something nice

**Describe alternatives you've considered**
We can either use https://netty.io/4.0/api/io/netty/handler/codec/http/multipart/InterfaceHttpPostRequestDecoder.html or parse it ourselves in ZIO streams.

**Comment by fokot** [comment]
It looks it needs to be added here https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala#L124

**Comment by fokot** [comment]
I will work on it

**Comment by tusharmath** [comment]
There are two ways we can implement it —

1. Using Netty's multipart-decoder
2. Using ZIO Parser

We can also decode a FullHttpRequest or an HttpRequest where the body is a stream.

In my opinion, we should move fast on this issue by implementing a non-streaming solution first and decoding it with netty's multipart decoder. That will perform the decoding in memory at once. So it won't work for very large files, but at least build some multipart support in the library.

**Comment by Tasselmi** [comment]
hi, my friends. any update?
