### ISSUE TITLE
Is some difficult to custom bind port?

### ISSUE THREAD

**Issue by changzhiwin** [zio/zio-http#1567]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when configure bind port, can't find an easy way to do that.

what I want:
```
  val myApp = for {
    config <- ZIO.service[AppConfig]
    _ <- Server.serve(httpRoute, config.port)  // error, not have this method
  }
```

what I can find:
```
def run = myApp.provide(
  ServerConfig.live(ServerConfig.default.port(8090)), // here, but can't use config
  Server.live
)
```

**Comment by Wosin** [comment]
One thing I can think of is to create a custom layer that creates `ServerConfig` from `AppConfig` or even do mapping in `provide`: 
```
val appLayer = ZLayer.fromZIO(
    for {
      config <- ZIO.service[AppConfig]
    } yield ServerConfig.default.port(config.port),
  )
  def run      = Server.serve(app).provide(ZLayer.succeed(AppConfig(9999)) >>> appLayer >>> Server.live)
```

But I agree that it would be cool to be able to this more idiomatically.

**Comment by changzhiwin** [comment]
@Wosin yes, this works, but too redundant for this purpose.

**Comment by Wosin** [comment]
Agreed.

**Comment by jdegoes** [comment]
We can create an overloaded `Server.serve` that binds to the specified port. 👍

**Comment by changzhiwin** [comment]
@jdegoes It's not easy thought overloaded `Server.serve`. The dependence of `ServerConfig` can't modify globally.
`ServerConfig`  >>> `NettyDriver`
`ServerConfig` >>> `Server`

**Comment by Wosin** [comment]
@jdegoes how about just modifying the `default` to something like:
```
  def default(port: Int = 8080) : ZLayer[Any, Throwable, Server] = {
    implicit val trace = Trace.empty
    ServerConfig.live(port) >>> live
  }

 ```
 
This should allow minimal work to provide flexibility for the users that want to use port that's different than default.

**Comment by jdegoes** [comment]
👍

**Comment by Wosin** [comment]
Solved.

**Comment by Wosin** [comment]
@changzhiwin Recently merged PR adds `Server.withDefaultPort()` that solves this issue.

@jdegoes  I think we can close that.
