### ISSUE TITLE
isolate host in URL

### ISSUE THREAD

**Issue by yisraelU** [zio/zio-http#1624]
It would be nice to have the ability to modify the path without needing to know the hostname .
currently the setPath method will inadvertently override the host with the new path
A suggestion would be to check if a relative path was passed in and  the existing path is absolute to combine them appropriately

**Comment by jmgimeno** [comment]
Maybe my understanding of the code is completely wrong, but I'm unable to see how `setPath` is able to **inadvertently override the host with the new path**.

**Comment by yisraelU** [comment]
@jmgimeno 
Because Host is not stored in the URL,rather in the Path. Path is a union of RelativePath and AbsolutePath
If you have a AbsolutePath stored and you wish to change the path not the host , setPath will override the Path reference and set it to a RelativePath
https://github.com/zio/zio-http/blob/0d3527faa3eb460a0715f79788d59b2c4afe6b23/zio-http/src/main/scala/zio/http/URL.scala#L72

**Comment by jmgimeno** [comment]
Sorry to insist, but I'm unable to find the `host` in the `path`. 

In the code below, which are extracts of the code I've found on package `zio.http`, I see that `host` is encoded in a `Location.Absolute` which is in the `kind` field of the `URL`, not in the `path`.

And the `Path` is a `Vector` of `Segment`s, each one containing only `text`.

```scala

// from zio/http/Path.scala
final case class Path private (segments: Vector[Segment]) 

// from zio/http/URL.scala
final case class URL(
  path: Path,
  kind: URL.Location = URL.Location.Relative,
  queryParams: QueryParams = QueryParams.empty,
  fragment: Option[Fragment] = None,
) { ... } 

object URL {

  sealed trait Location
  
  object Location {
      final case class Absolute(scheme: Scheme, host: String, port: Int) extends Location
  
      case object Relative extends Location
  }

}
```

**Comment by bracl** [comment]
This was my conclusion as well, I went to write a failing test first, and saw that the desired behaviour in the ticket was already happening. 

This PR adds a test to prove it: https://github.com/zio/zio-http/pull/1699

**Comment by yisraelU** [comment]
You are right , I was misremembering.
I dont recall now how I bumped into this issue , but it seems like it was my error , I will close this issue
