### ISSUE TITLE
Improve operations with headers in Middleware

### ISSUE THREAD

**Issue by vadeg** [zio/zio-http#1628]
**Is your feature request related to a problem? Please describe.**
When using `Middleware.addHeader` function it is unclear where the header will be added: to request or to response. Without finding a simple example which is related to Middleware in general where in one line it states:
> Let us consider a simple example using out-of-the-box middleware called addHeader We will write a middleware that will attach a custom header to the response.

and without digging dive how exactly Middleware works it is difficult to grasp the idea of this. 

**Describe the solution you'd like**

I have two suggestions:

### Replace Middleware.addHeader with Middleware.addResponseHeader

Replace `Middleware.addHeader` with `Middleware.addResponseHeader` which is more clear where the header will be added.

### Add `Middleware.addRequestHeader` function

Add an additional `Middleware.addRequestHeader` function which adds a header to the Request. For example, it could be done via `Middleware.transform`:
```scala
Middleware.transform[Request, Response](
  in => in.addHeader("my_custom_header", my_custom_value),
  identity
)


```

**Comment by tusharmath** [comment]
We can alternatively also do something like `Middleware.addHeader[Request]` and `Middleware.addHeader[Response]`.

**Comment by jdegoes** [comment]
👍 to renaming `addResponseHeader`.

I think there may be applications for adding a header to the request, but it would only be for pre-processing by other middleware, pretty much. If it's important we'll have to consider that in light of declarative middleware.

**Comment by Wosin** [comment]
Are we also going to rename all specific methods too? E.g. `Middleware.withAge` will also add `Age` header to the response only.
