### ISSUE TITLE
Implement a code generator that takes OpenAPI spec and generates zio.http.api.EndpointSpec values

### ISSUE THREAD

**Issue by sideeffffect** [zio/zio-http#1661]
**Is your feature request related to a problem? Please describe.**

Some companies begin with OpenAPI specifications, and then proceed to implement a server that satisfies a given OpenAPI specification; then they will modify the OpenAPI specification when a change is necessary, and then re-implement the server.

**Describe the solution you'd like**

In order to support this spec-first driven approach to API development (rather than code-first, which is the paradigm already implemented within the zio.http.api package), we will need a code generator, which can read in a OpenAPI specification, and generate the corresponding zio.http.EndpointSpec values that declaratively describe the APIs.

Then a user can implement handlers based on the code-generated API values.

clone of https://github.com/zio/zio-http/issues/1522
ticket in Guardrail https://github.com/guardrail-dev/guardrail/issues/1038

**Comment by zeal18** [comment]
I've started working on this before, but will try to accomplish during the hackathon

**Comment by 987Nabil** [comment]
I guess #1520 is a duplicate
@zeal18 if you are interested, maybe we can pair on this. You can reach me also in discord. There is only one Nabil ;)

**Comment by zeal18** [comment]
After a conversation with @987Nabil, I still believe that this functionality should be implemented on the guardrail side which I'm going to do

**Comment by vigoo** [comment]
Closed as it is a duplicate, keeping the original.
