### ISSUE TITLE
Implement an existing ZIO HTTP middleware in terms of new declarative middleware API

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1689]
**Background**

ZIO HTTP has long supported _middleware_, which are functions that transform one `Http` into another `Http`. Middleware allow an orthogonal way of decomposing complex server functionality into modular aspects--such as logging, metrics, authentication, and so forth.

The existing middleware machinery lives in `zio.http.Middleware` and the associated companion object, with many concrete middleware implementations being defined in a subpackage that is brought into the `Middleware` companion object. 

In an effort to better support the needs of `zio.http.api`, a new declarative encoding of middleware has been introduced, which lives in the package `zio.http.api`. Unlike the previous definition of `Middleware`, the new definition of middleware divides the middleware into two separate pieces:

1. A specification. Currently, this is called `MiddlewareSpec`, and it describes two things:
  1. What the middleware requires from an incoming HTTP `Request`. For example, an authentication middleware may require an `Authentication` header. This is described by a `zio.http.api.HttpCodec`, which is limited to look at the headers and query string parameters of the request (and soon, the full path of the incoming request).
  2. What  modifications the middleware makes to the HTTP `Response` generated by the handler. For example, one middleware might add a `X-Trace-Id` header to the response, for purposes of distributed tracing. This is described by a `zio.http.api.HttpCodec`, which is limited to modify the status and the headers of the response.
2. An implementation. An implementation, which in the happy path, takes in the middleware input, and produces the middleware output. An implementation could also decide to abort calling the route handler for an endpoint, rather than producing the normal modification to the HTTP response. This abort behavior is useful for error conditions, for example, an authentication middleware does NOT want the route handler to be invoked if authentication fails. Most middleware will not use abort.

The specifications for middleware are intended to live in the `zio.http.api.MiddlewareSpec` companion object. The implementations for middleware are defined to live in the `zio.http.api.Middleware` companion object.

Here is the specification for a middleware that adds a fixed `Cookie` header to responses:

```scala
def addCookie: MiddlewareSpec[Unit, Cookie[Response]] =
    MiddlewareSpec(
      HttpCodec.empty,
      HeaderCodec.cookie.transformOrFail(
        str => Cookie.decode[Response](str).left.map(_.getMessage),
        _.encode(false).left.map(_.getMessage),
      ),
    )
```

This `MiddlewareSpec` does not require anything from the request but does produce a response cookie. Note that the specification for the middleware does not actually need to have any specific cookie, because it only defines the structure of the middleware: what it is looking for in the request, and what it appends to the response.

The implementation for such a middleware could look like this:

```scala
def addCookie(cookie: Cookie[Response]): Middleware[Any, Unit, Cookie[Response]] =
    fromFunction(MiddlewareSpec.addCookie)(_ => cookie)
```

This very simple implementation ignores the `Unit` input to the middleware, and produces a static (fixed) cookie in the response. Of course, most middlewares would not be so simple, but this is a nice example because it is very small.

To produce implementations of middleware specs, you can use the `MiddlewareSpec#implement` family of functions. Always use the weakest / least powerful way of implementing a spec that satisfies your requirements, to keep the code simple and provide future opportunities for performance optimization.

**The New Middleware**

We do not intend to support both the old middleware and the new middleware, because there is too much overlap between them. Rather, we intend to move to the new middleware, which present additional opportunities for documentation, automatic type-safe client libraries, and performance optimization--all of which are powered by `MiddlewareSpec`, because it is such a precise and purely declarative description of what middleware does with requests and responses.

In order to switch over to the new middleware, it needs to have feature-parity with the old middleware, using the same API, so we can avoid breaking code in the wild built on previous releases of ZIO HTTP (whenever possible). 

**The Work To Be Done**

At the end of this ticket, you will find a a list of existing middleware, which need to be ported to the new declarative middleware framework.

In order to do the port, it will be necessary to make three changes to the code base:

1. Add a spec for the middleware in the `zio.http.api.MiddlewareSpec` companion object, following the pattern laid down by the existing specs.
2. Implement the spec inside the `zio.http.api.Middleware` companion object, following the pattern laid down by the existing implementations. Note that the implementation can be copy/pasted from the existing middleware, but some changes will need to be made in order to facilitate the transfer.
3. Add a test suite for the middleware, following the convention `XYZMiddlewareSpec`, where `XYZ` is the name of the middleware. You can find an example test suite in `CsrfMiddlewareSpec.scala`, which can form the basis of your own test suite. If there are tests for the existing middleware, you should be able to reuse these for your ported middleware.

**WARNING**: _Only `HttpMiddleware` can currently be ported: that is, middleware that operate on request/responses. It is expected that the serialization / deserialization middleware can be implemented as aspects on `HttpAspect`, rather than as "proper middleware", which is a more restricted kind of `HttpAspect`._

**ZIO Hackathon Notes**

To sign up for porting one middleware, simply comment on the ticket below, and indicate _which_ middleware you want to work on. Note that you only have to port a **single** middleware in order to qualify for your free t-shirt. Of course, if you find porting a middleware easy, you are encouraged to port a few to help us work through the porting backlog!

**Testing Notes**

In order to add a middleware to an `Http`, you can use the temporary method `Http#withMiddleware`, which may only be called on an HTTP whose input type is `Request`, and whose output type is `Response`. This will allow you to "install" a middleware around an `Http`, which is useful for testing to make sure your new middleware does what it is supposed to.

You may find bugs in the declarative middleware machinery, because it is so new. If so, please work with @jdegoes and @afsalthaj to resolve them so you can make progress on your ticket.

**Tracker for Porting Middleware**

- https://github.com/zio/zio-http/issues/1700

- [ ] `requestLogging` - parameters: `( level: Status => LogLevel = (_: Status) => LogLevel.Info, loggedRequestHeaders: Set[String] = Set.empty, loggedResponseHeader: Set[String] = Set.empty, logRequestBody: Boolean = false, logResponseBody: Boolean = false, requestCharset: Charset = StandardCharsets.UTF_8, responseCharset: Charset = StandardCharsets.UTF_8)`
- [ ] `metrics` - parameters: `( pathLabelMapper: PartialFunction[Request, String] = Map.empty, concurrentRequestsName: String = "http_concurrent_requests_total", totalRequestsName: String = "http_requests_total", requestDurationName: String = "http_request_duration_seconds", requestDurationBoundaries: MetricKeyType.Histogram.Boundaries = Metrics.defaultBoundaries, extraLabels: Set[MetricLabel] = Set.empty)`
- https://github.com/zio/zio-http/issues/1701
- https://github.com/zio/zio-http/issues/1702
- [x] `withAccessControlAllowCredentials` - parameters: `(value: Boolean)`
- [ ] `withAccessControlAllowHeaders` - parameters: `(value: CharSequence)`
- [x] `withAccessControlAllowMethods` - parameters: `(value: Method*)`
- [x] `withAccessControlAllowOrigin` - parameters: `(value: CharSequence)`
- [ ] `withAccessControlExposeHeaders` - parameters: `(value: CharSequence)`
- [ ] `withAccessControlMaxAge` - parameters: `(value: CharSequence)`
- [ ] `withAccessControlRequestHeaders` - parameters: `(value: CharSequence)`
- [ ] `withAccessControlRequestMethod` - parameters: `(value: Method)`
- [ ] `withAge` - parameters: `(value: CharSequence)`
- [ ] `withAllow` - parameters: `(value: CharSequence)`
- [ ] `withCacheControl` - parameters: `(value: CharSequence)`
- [ ] `withCacheControlMaxAge` - parameters: `(value: Duration)`
- [x] `withConnection` - parameters: `(value: CharSequence)`
- https://github.com/zio/zio-http/issues/1703
- [ ] `withCookie` - parameters: `(value: CharSequence)`
- [ ] `withDate` - parameters: `(value: CharSequence)`
- [ ] `withDnt` - parameters: `(value: CharSequence)`
- [ ] `withEtag` - parameters: `(value: CharSequence)`
- [ ] `withExpect` - parameters: `(value: CharSequence)`
- [x] `withExpires` - parameters: `(value: CharSequence)`
- [ ] `withFrom` - parameters: `(value: CharSequence)`
- [ ] `withHost` - parameters: `(value: CharSequence)`
- [ ] `withIfMatch` - parameters: `(value: CharSequence)`
- [ ] `withIfModifiedSince` - parameters: `(value: CharSequence)`
- [ ] `withIfNoneMatch` - parameters: `(value: CharSequence)`
- [x] `withIfRange` - parameters: `(value: CharSequence)`
- [ ] `withIfUnmodifiedSince` - parameters: `(value: CharSequence)`
- [ ] `withLastModified` - parameters: `(value: CharSequence)`
- [ ] `withLocation` - parameters: `(value: CharSequence)`
- [ ] `withMaxForwards` - parameters: `(value: CharSequence)`
- [ ] `withMediaType` - parameters: `(mediaType: MediaType)`
- [ ] `withOrigin` - parameters: `(value: CharSequence)`
- [ ] `withPragma` - parameters: `(value: CharSequence)`
- [x] `withProxyAuthenticate` - parameters: `(value: CharSequence)`
- [x] `withProxyAuthorization` - parameters: `(value: CharSequence)`
- [ ] `withRange` - parameters: `(value: CharSequence)`
- [x] `withReferer` - parameters: `(value: CharSequence)`
- [x] `withRetryAfter` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketAccept` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketExtensions` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketKey` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketLocation` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketOrigin` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketProtocol` - parameters: `(value: CharSequence)`
- [ ] `withSecWebSocketVersion` - parameters: `(value: CharSequence)`
- [ ] `withServer` - parameters: `(value: CharSequence)`
- [ ] `withSetCookie` - parameters: `(value: Cookie[Response])`
- [ ] `withTe` - parameters: `(value: CharSequence)`
- [ ] `withTrailer` - parameters: `(value: CharSequence)`
- [x] `withTransferEncoding` - parameters: `(value: CharSequence)`
- [ ] `withUpgrade` - parameters: `(value: CharSequence)`
- [ ] `withUpgradeInsecureRequests` - parameters: `(value: CharSequence)`
- [ ] `withUserAgent` - parameters: `(value: CharSequence)`
- [ ] `withVary` - parameters: `(value: CharSequence)`
- [ ] `withVia` - parameters: `(value: CharSequence)`
- [ ] `withWarning` - parameters: `(value: CharSequence)`
- [ ] `withWebSocketLocation` - parameters: `(value: CharSequence)`
- [ ] `withWebSocketOrigin` - parameters: `(value: CharSequence)`
- [ ] `withWebSocketProtocol` - parameters: `(value: CharSequence)`
- [ ] `withWwwAuthenticate` - parameters: `(value: CharSequence)`
- [ ] `withXFrameOptions` - parameters: `(value: CharSequence)`
- [ ] `withXRequestedWith` - parameters: `(value: CharSequence)`

**Comment by dev-andrey** [comment]
I would like to work on this issue. I can start with the first six:
  cors - parameters: [R, E](config: CorsConfig = CorsConfig())
  basicAuth - parameters: (f: Credentials => Boolean)
  basicAuth - parameters: (u: String, p: String)
  basicAuthZIO - parameters: [R, E](f: Credentials => ZIO[R, E, Boolean])
  bearerAuth - parameters: (f: String => Boolean)
  bearerAuthZIO - parameters: [R, E](f: String => ZIO[R, E, Boolean])

**Comment by afsalthaj** [comment]
👍🏻

**Comment by swoogles** [comment]
@jdegoes should I split this list up into multiple issues that can be assigned to people?

I'm hesitant to assign this one to Andrey since there are so many others that are still up for the taking.

**Comment by jeffwilde** [comment]
@swoogles , I think that's the right move. I'd like to work on one of these if broken up or tracked separately.

**Comment by vder** [comment]
Ok I'll try to overcome the following ones:
addHeader - parameters: (header: Header)
addHeader - parameters: (name: CharSequence, value: CharSequence)
addHeaders - parameters: (headers: Headers)
removeHeader - parameters: (name: String)
removeHeaders - parameters: (headers: List[String])

and then we will see whats next

**Comment by Smudgey** [comment]
I would like to work on this issue. 

I will attempt:
withAccept - parameters: (value: CharSequence)
withAcceptEncoding - parameters: (value: CharSequence)
withAcceptLanguage - parameters: (value: CharSequence)
withAcceptPatch - parameters: (value: CharSequence)
withAcceptRanges - parameters: (value: CharSequence)

and see how I get on

**Comment by bburdiliak** [comment]
I would go with:

 withContentBase - parameters: (value: CharSequence)
 withContentDisposition - parameters: (value: CharSequence)
 withContentEncoding - parameters: (value: CharSequence)
 withContentLanguage - parameters: (value: CharSequence)
 withContentLength - parameters: (value: Long)

**Comment by swoogles** [comment]
> I would like to work on this issue. I can start with the first six: cors - parameters: [R, E](config: CorsConfig = CorsConfig()) basicAuth - parameters: (f: Credentials => Boolean) basicAuth - parameters: (u: String, p: String) basicAuthZIO - parameters: [R, E](f: Credentials => ZIO[R, E, Boolean]) bearerAuth - parameters: (f: String => Boolean) bearerAuthZIO - parameters: [R, E](f: String => ZIO[R, E, Boolean])

Please comment on this ticket, so that I can assign you- https://github.com/zio/zio-http/issues/1700

**Comment by BalduinLandolt** [comment]
I could give those a shot:

- customAuth - parameters: ( verify: Headers => Boolean, responseHeaders: Headers = Headers.empty, responseStatus: Status = Status.Unauthorized)
- customAuthZIO - parameters: [R, E](verify: Headers => ZIO[R, E, Boolean], responseHeaders: Headers = Headers.empty, responseStatus: Status = Status.Unauthorized)

(though that would actually belong to #1700 content-wise)

**Comment by swoogles** [comment]
> I would like to work on this issue.
> 
> I will attempt: withAccept - parameters: (value: CharSequence) withAcceptEncoding - parameters: (value: CharSequence) withAcceptLanguage - parameters: (value: CharSequence) withAcceptPatch - parameters: (value: CharSequence) withAcceptRanges - parameters: (value: CharSequence)
> 
> and see how I get on

@Smudgey  Please comment on this ticket so that I can assign you - https://github.com/zio/zio-http/issues/1702

**Comment by swoogles** [comment]
@bburdiliak Can you comment on this ticket so that I can assign you - https://github.com/zio/zio-http/issues/1703

**Comment by swoogles** [comment]
> I could give those a shot:
> 
>     * customAuth - parameters: ( verify: Headers => Boolean, responseHeaders: Headers = Headers.empty, responseStatus: Status = Status.Unauthorized)
> 
>     * customAuthZIO - parameters: [R, E](verify: Headers => ZIO[R, E, Boolean], responseHeaders: Headers = Headers.empty, responseStatus: Status = Status.Unauthorized)
> 
> 
> (though that would actually belong to #1700 content-wise)

Agreed. @dev-andrey Do you want to tackle these extra 2 entries? I will add them to your ticket if so. 

@BalduinLandolt  Are there any others you're interested in?

**Comment by dev-andrey** [comment]
@swoogles yeah, I don't mind picking that extra middleware as they seem related to auth

**Comment by BalduinLandolt** [comment]
@dev-andrey withAuthorization and withBasicAuthorization  may fall under those too (judging from the name, haven't looked at the code)

sure, I'll find something. Will let you know once I'm decided

**Comment by BalduinLandolt** [comment]
@swoogles I give `requestLogging` a try. Not sure how far I'll come, though

**Comment by BalduinLandolt** [comment]
@swoogles I started working on `requestLogging` together with @irinaschubert, but we reached a point where we're not so sure anymore if it's currently even possible at all (without considerable regressions to the current implementation): Currently, lot's of things are/can be logged, both from the incoming Request and the outgoing Response. But we didn't find a way to get a hold on the Request at all, there seem to be codecs only for headers etc.  
And it also says so in the description above:

> [MiddlewareSpec describes w]hat the middleware requires from an incoming HTTP Request. [...] This is described by a zio.http.api.HttpCodec, which is limited to look at the headers and query string parameters of the request (and soon, the full path of the incoming request).

How should we proceed here?

**Comment by swoogles** [comment]
@jdegoes I think you've got more insight to the current state of affairs here ^

**Comment by bburdiliak** [comment]
Are there any unassigned subtasks of this one?

**Comment by swoogles** [comment]
> Are there any unassigned subtasks of this one? 

Hey @bburdiliak I have just been creating subtasks as people volunteer for various groups. If you want to claim a few more, I would be happy to create and assign another one.

**Comment by bs76** [comment]
@dev-andrey Will there be specific middleware to *remove* sensitive headers ? e.g. for BASIC auth I'd like to drop the password part of Authentication header ideally always, unless specifying I want to keep it.

**Comment by wpoosanguansit** [comment]
Commit for AccessControlAllowOrigin https://github.com/zio/zio-http/pull/1780 for review.

**Comment by wpoosanguansit** [comment]
Commit for AccessControlAllowMaxAge https://github.com/zio/zio-http/pull/1781

**Comment by wpoosanguansit** [comment]
Commit for Expires - https://github.com/zio/zio-http/pull/1791

**Comment by wpoosanguansit** [comment]
Commit for Connection https://github.com/zio/zio-http/pull/1792

**Comment by wpoosanguansit** [comment]
Commit for TransferEncoding - https://github.com/zio/zio-http/pull/1800

**Comment by vigoo** [comment]
@jdegoes I think this is no longer relevant, is it?

**Comment by jdegoes** [comment]
@vigoo Closed because they can't be unified in the end.
