### ISSUE TITLE
Implement zio.http.api.internal.RichTextCodec#decode

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1691]
**Background**

`RichTextCodec` defines a codec for some structured type `A`, which may be decoded from a string, or encoded to a string. Codecs can be thought of as combinations of two things: a parser, which can produce an `A` from a string input (decoding); and a printer, which can render an `A` to a string (encoding).

**Task**

This task is to implement the `decode` method of `RichTextCodec`.

This can be done by recursively pattern matching on `RichTextCodec` (which is a sealed trait), finding out which subtype it is, and implementing the subtype-specific way of decoding.

Together with this, you should implement a test suite that proves the implementation can handle all the `RichTextCodec` constructors and operators, so that we have confidence in the correctness of decoding.

**Notes**

This ticket will benefit from someone who has used parser combinators in Scala, or even who has written parsers before.

**Comment by jpablo** [comment]
I'd like to work on this

**Comment by jpablo** [comment]
Just wanted to clarify on the expected behavior of 
```scala
final def decode(value: CharSequence): Either[String, A] 
```
When the Codec is 
```scala
final case class CharIn(set: BitSet) extends RichTextCodec[Unit]
```

Is the intention to only allow a single character in the bitset, as in 
```scala
def char(c: Char): RichTextCodec[Unit] = CharIn(BitSet(c.toInt))
```
or will it be possible to create a `CharIn` with multiple characters?

**Comment by jdegoes** [comment]
The type on CharIn was wrong and this has been fixed. It will decode to one of the characters from the bit set.

**Comment by Wosin** [comment]
Should this be closed ??
