### ISSUE TITLE
Implement zio.http.api.internal.RichTextCodec#encode

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1692]
**Background**

`RichTextCodec` defines a codec for some structured type `A`, which may be decoded from a string, or encoded to a string. Codecs can be thought of as combinations of two things: a parser, which can produce an `A` from a string input (decoding); and a printer, which can render an `A` to a string (encoding).

**Task**

This task is to implement the `encode` method of `RichTextCodec`.

This can be done by recursively pattern matching on `RichTextCodec` (which is a sealed trait), finding out which subtype it is, and implementing the subtype-specific way of encoding.

Together with this, you should implement a test suite that proves the implementation can handle all the `RichTextCodec` constructors and operators, so that we have confidence in the correctness of encoding.

**Comment by rajcspsg** [comment]
@jdegoes I would like to work on this

**Comment by swoogles** [comment]
@rajcspsg Great! If you want to discuss your ongoing work, please post in here: https://discord.com/channels/724305612166660202/903694270639263775
