### ISSUE TITLE
Implement zio.http.api.internal.RichTextCodec#describe

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1693]
**Background**

`RichTextCodec` defines a codec for some structured type `A`, which may be decoded from a string, or encoded to a string. Codecs can be thought of as combinations of two things: a parser, which can produce an `A` from a string input (decoding); and a printer, which can render an `A` to a string (encoding). However, they are more powerful than this, because they are pure data, it is possible to use them to generate documentation (the purpose of this ticket).

**Task**

This task is to implement the `describe` method of `RichTextCodec`, which is intended to generate human-readable documentation for any `RichTextCodec`, ultimately for purpose of embedding into OpenAPI documentation.

This can be done by recursively pattern matching on `RichTextCodec` (which is a sealed trait), finding out which subtype it is, and implementing the subtype-specific way of describing the codec in a human-readable way.

Together with this, you should implement a test suite that proves the implementation can handle all the `RichTextCodec` constructors and operators, so that we have confidence in the correctness of documentation generation.

**Comment by gregor-rayman** [comment]
I'd like to work on this
