### ISSUE TITLE
Middleware to wrap handler effect

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#1695]
**Describe the bug**
Introduced tracing with `zio-telemetry`, I wanted to add a top-level span (for all requests) that handles incoming trace headers.
To avoid re-writing the same logic in every endpoint. It does work in the sense - the span is created and reported.
However any span within endpoints is not "connected" to this top-level span (in jaeger UI the appear as seperate traces).

**To Reproduce**
1. Create tracing `Middleware[R, E, Request, Response, Request, Respone]` and add `http.contramapZIO` with `Tracing.spanFrom(propagator, req.headers, getter, "span-name", SpanKind.Server, (_: Throwable) => OTELStatusCode.Unset)(ZIO.attempt(req))`
2. The assumption being we "wrap" the effect (of handling request) in the top-level span
3. Add middleware to your http app
4. In http app route have another tracing wrapper around business logic `tracing.span("span-name-2", SpanKind,Server, (_: Throwable) => OTELStatusCode.Unset)(businessLogicEff)`

**Expected behaviour**
Expected two spans reported in Jaeger in parent-child relationship

**Screenshots**
Actual result:
![image](https://user-images.githubusercontent.com/1419884/198251928-2bfbb90f-ea79-48a7-9a82-61498d83150d.png)

Expected result:
![image](https://user-images.githubusercontent.com/1419884/198252040-1c9d22dc-8792-4005-b587-ac51e1282ff1.png)

**Env (please complete the following information):**
 - ZIO 2.0.2
 - zio-telemetry 2.0.3
 - zhttp 2.0.0-RC10

**Additional context**
Is there another way of "wrapping" request handler I missed?
It seems I'm wrapping request construction effect `Request => UIO[Request]` not the actual handler effect

**Comment by ioleo** [comment]
Middleware implementation:
```scala
object TracingMiddleware {

  val propagator: TextMapPropagator = W3CTraceContextPropagator.getInstance()
  val getter: TextMapGetter[Headers] = new TextMapGetter[Headers] {
    override def keys(carrier: Headers): JIterable[String] =
      carrier.toList.map(_._1).asJava

    override def get(carrier: Headers, key: String): String =
      carrier.toList.find(_._1 == key).map(_._2).getOrElse(null)
  }

  def trace[R <: Tracing, E >: Throwable]: Middleware[R, E, Request, Response, Request, Response] =
    new Middleware[R, E, Request, Response, Request, Response] {

      override def apply[R1 <: R, E1 >: E](
          http: Http[R1, E1, Request, Response]
      ): Http[R1, E1, Request, Response] =
        http
          .contramapZIO[R1, E1, Request] { r =>
            Tracing
              .spanFrom(
                propagator,
                r.headers,
                getter,
                "getCalls",
                SpanKind.SERVER,
                (_: Throwable) => OTELStatusCode.UNSET
              )(ZIO.attempt(r))
          }
    }
}

```

**Comment by ioleo** [comment]
Also tried a little bit diffrent approach, trying to "lift" Http app into one that wraps all requests in tracing.

```scala
new Middleware[R, E, Request, Response, Request, Response] {

      override def apply[R1 <: R, E1 >: E](
          http: Http[R1, E1, Request, Response]
      ): Http[R1, E1, Request, Response] =
        Http.collectZIO[Request] { case req =>
          Tracing
            .spanFrom(
              propagator,
              req.headers,
              getter,
              "request",
              SpanKind.SERVER,
              (_: E1) => OTELStatusCode.UNSET
            )(http(req).mapError(_.get))
        }
    }
 ```
 
This one actually works (although feels kinda dirty).
Not sure where the `Option[E1]` error came from (that `.get` worries me, did it to quickly satisfy the compiler, but is it ever going to be `None`?)

**Comment by vigoo** [comment]
Here is an example with the latest snapshot versions:
```
      "dev.zio" %% "zio" % "2.0.9+7-3a52faec-SNAPSHOT",
      "dev.zio" %% "zio-http" % "0.0.4+18-e8b75563-SNAPSHOT",
      "dev.zio" %% "zio-opentelemetry" % "3.0.0-RC2",
```

```scala
import io.opentelemetry.api.trace.SpanKind
import zio._
import zio.http.model.Method
import zio.http._
import zio.telemetry.opentelemetry._
import zio.telemetry.opentelemetry.context.ContextStorage
import zio.telemetry.opentelemetry.tracing.Tracing

object Main extends ZIOAppDefault {
  override def run: ZIO[Environment with ZIOAppArgs with Scope, Any, Any] = {
    val tracingMiddleware: RequestHandlerMiddleware[Tracing, Nothing] = new RequestHandlerMiddleware[Tracing, Nothing] {
      override def apply[R1 <: Tracing, Err1 >: Nothing](handler: Handler[R1, Err1, Request, Response])(implicit trace: Trace): Handler[R1, Err1, Request, Response] =
        Handler.fromFunctionZIO[Request] { request =>
          ZIO.service[Tracing].flatMap { tracing =>
            import tracing.aspects._
            handler.runZIO(request) @@ root[Err1]("request", SpanKind.SERVER)
          }
        }
    }

    val app = Http.collectZIO[Request] {
      case Method.GET -> !! / "test" =>
        ZIO.serviceWithZIO[Tracing] { tracing =>
          import tracing.aspects._

          ZIO.succeed(Response.text("Hello")).delay(2.seconds) @@ span("child span")
        }
    }

    Server.serve(app @@ tracingMiddleware)
      .provide(
        Server.default,
        Tracing.live,
        JaegerTracer.live,
        ContextStorage.fiberRef
      )
  }
}
```

![image](https://user-images.githubusercontent.com/2292489/219872971-f888b716-7deb-45ea-9509-d3a422834298.png)
