### ISSUE TITLE
Middleware Rewrites - Cors & Auth

### ISSUE THREAD

**Issue by swoogles** [zio/zio-http#1700]
Part of https://github.com/zio/zio-http/issues/1689

- [ ] `cors` - parameters: `[R, E](config: CorsConfig = CorsConfig())`
- [ ] `basicAuth` - parameters: `(f: Credentials => Boolean)`
- [ ] `basicAuth` - parameters: `(u: String, p: String)`
- [ ] `basicAuthZIO` - parameters: `[R, E](f: Credentials => ZIO[R, E, Boolean])`
- [ ] `bearerAuth` - parameters: `(f: String => Boolean)`
- [ ] `bearerAuthZIO` - parameters: `[R, E](f: String => ZIO[R, E, Boolean])`
- [ ] `customAuth` - parameters: `( verify: Headers => Boolean, responseHeaders: Headers = Headers.empty, responseStatus: Status = Status.Unauthorized)`
- [ ] `customAuthZIO` - parameters: `[R, E](verify: Headers => ZIO[R, E, Boolean], responseHeaders: Headers = Headers.empty, responseStatus: Status = Status.Unauthorized)`
- [ ] `withAuthorization` - parameters: `(value: CharSequence)`
- [ ] `withBasicAuthorization` - parameters: `(username: String, password: String)`

**Comment by dev-andrey** [comment]
I would like to work on this issue
