### ISSUE TITLE
Middleware Rewrites - withAccept*

### ISSUE THREAD

**Issue by swoogles** [zio/zio-http#1702]
Part of #1689 

- [x] `withAccept` - parameters: `(value: CharSequence)`
- [x] `withAcceptEncoding` - parameters: `(value: CharSequence)`
- [x] `withAcceptLanguage` - parameters: `(value: CharSequence)`
- [x] `withAcceptPatch` - parameters: `(value: CharSequence)`
- [x] `withAcceptRanges` - parameters: `(value: CharSequence)`

**Comment by Smudgey** [comment]
I am working on this ticket

**Comment by vigoo** [comment]
Seems to be already done
