### ISSUE TITLE
Middleware Rewrites - withContent*

### ISSUE THREAD

**Issue by swoogles** [zio/zio-http#1703]
Part of #1689 

- [x] `withContentBase` - parameters: `(value: CharSequence)`
- [x] `withContentDisposition` - parameters: `(value: CharSequence)`
- [x] `withContentEncoding` - parameters: `(value: CharSequence)`
- [x] `withContentLanguage` - parameters: `(value: CharSequence)`
- [x] `withContentLength` - parameters: `(value: Long)`
- [x] `withContentLocation` - parameters: `(value: CharSequence)`
- [x] `withContentMd5` - parameters: `(value: CharSequence)`
- [x] `withContentRange` - parameters: `(value: CharSequence)`
- [x] `withContentSecurityPolicy` - parameters: `(value: CharSequence)`
- [x] `withContentTransferEncoding` - parameters: `(value: CharSequence)`
- [x] `withContentType` - parameters: `(value: CharSequence)`

**Comment by 987Nabil** [comment]
I am on it 🙂

**Comment by bburdiliak** [comment]
I am on it

**Comment by 987Nabil** [comment]
@bburdiliak too late I guess 😅

**Comment by vigoo** [comment]
This seems to be already done
