### ISSUE TITLE
Don't run blocking effects on the netty's runtime

### ISSUE THREAD

**Issue by digy** [zio/zio-http#1723]
**Is your feature request related to a problem? Please describe.**

Would like to reopen the issue https://github.com/zio/zio-http/issues/1368 since running any effect that blocks will block the whole thread.

```scala
import zio._
import zio.http._
import zio.http.model.Method

object BlockingEffect extends ZIOAppDefault {
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {

    val handler = ZIO.succeed(Thread.sleep(10000)) <&> ZIO.debug("debug") *> ZIO.succeed(Response.ok)

    val app  = Http.collectZIO[Request] {
      case Method.GET -> !! / "blocking" => handler
    }

    val action = for {
      _ <- Server.serve(app).forkDaemon
      _ <- ZIO.sleep(1.second)
      _ <- Client.request("http://localhost:8080/blocking")
    } yield ()

    val config = ServerConfig.default
      .port(8080)
      .maxThreads(1)

    action.provide(
      Server.live,
      Client.default,
      ServerConfig.live(config),
      zio.Scope.default,
    )
  }
}
```

**Describe the solution you'd like**
I think zio-http should be smarted about blocking effects such that running an effect in zio and in zio-http  have the same behavior.

**Describe alternatives you've considered**
Running all effects on the zio runtime instead of netty's runtime

**Comment by vigoo** [comment]
Fixed by #1999
