### ISSUE TITLE
Feature: Provide option to send the http request to different host other than the default one configured

### ISSUE THREAD

**Issue by rajcspsg** [zio/zio-http#1731]
**Is your feature request related to a problem? Please describe.**
http client in netty connects to server using connect() as in below example -

```
EventLoopGroup eventLoopGroup = EPOLL? new EpollEventLoopGroup(): new NioEventLoopGroup();
        try {
            Channel channel = new Bootstrap()
                    .group(eventLoopGroup)
                    .channel(channelClazz)
                    .handler(new ChannelInitializer<Channel>() {
                        @Override
                        protected void initChannel(Channel ch) throws Exception {
                            ch.pipeline().addLast(new StringDecoder(StandardCharsets.UTF_8))
                                    .addLast(new StringEncoder(StandardCharsets.UTF_8));

                        }
                    }).connect("127.0.0.1", 8000).sync().channel(); //.closeFuture().syncUninterruptibly();
```

one application I worked earlier uses [async-http-client](https://github.com/AsyncHttpClient/async-http-client) which supports this feature to send certain requests to different host/ip address. This is very helpful in testing the application live in certain environment.

Example using async-http-client- 

```
Request request1 = post("http://www.es1.com/search-index/index-name/index-id").setBody(payload).build();
Future<Response> whenResponse1 = asyncHttpClient.executeRequest(request1);
Request request = post("http://www.es2.com/search-index/index-name/index-id").setBody(payload).build();
Future<Response> whenResponse2 = asyncHttpClient.executeRequest(request2);
```

As you see above the same `asyncHttpClient` used to execute request1 and request2 which are sent to different servers.

**Describe the solution you'd like**
I'm still thinking on the approach to solve the problem. Will update this section soon. Other zio users/maintainers please feel free to comment on solution. 

**Describe alternatives you've considered**
The async-http-client supports this but it is not functional(it uses apache http client under the hood) and it is not actively maintained very much.

**Additional context**
NA

**Comment by vigoo** [comment]
The `Client` (`ZClient`) API already supports this. 
- you can either use the `.host` to set the host separately
- or use `.request` to use the host stored in a `Request`
