### ISSUE TITLE
Form data handling

### ISSUE THREAD

**Issue by frekw** [zio/zio-http#1756]
**Is your feature request related to a problem? Please describe.**
It would be nice if support for parsing `<form>` data was supported.

Right now I'm using `QueryStringDecoder` from Netty and doing something like:
```
  def parsePostBody(r: Request) =
    (for {
      body <- r.body.asString
      map  <- ZIO.succeed {
                import scala.jdk.CollectionConverters._
                val params = new QueryStringDecoder(body, StandardCharsets.UTF_8, false, 1024, true).parameters().asScala
                (for ((k, v) <- params) yield k -> v.asScala.toList).toMap
              }
    } yield map).orElseFail(HttpError.BadRequest("Invalid body"))
```

but it would be nice if it shipped with zio-http, perhaps with a cleaner API?

**Describe the solution you'd like**
Easily be able to handle data submitted via HTML forms.

**Describe alternatives you've considered**
Continue doing what I'm already doing.

**Comment by jdegoes** [comment]
How about:

```scala
Body#asQueryParams
```

Then eventually we would add `QueryParams#as[A: Schema]`.

**Comment by codingismy11to7** [comment]
looks like netty's `QueryStringDecoder` only throws `IllegalArgumentException`s, and it returns an ordered map (as does Play's form data decoder), so I made this slightly tweaked version. might open a PR with the `asQueryParams` functionality

```scala
import io.netty.handler.codec.http.{QueryStringDecoder => QSD}
import zio.{NonEmptyChunk, ZIO}

import java.nio.charset.Charset
import scala.collection.immutable.ListMap
import scala.jdk.CollectionConverters._

...

  def decode(
      data: String,
      charset: Charset,
      maxParams: Int = 1024,
  ): ZIO[Any, IllegalArgumentException, ListMap[String, NonEmptyChunk[String]]] = ZIO
    .attempt {
      val qsd    = new QSD(data, charset, false, maxParams, true)
      val params = qsd.parameters().entrySet().asScala.view
      ListMap.from(
        params.map(entry => entry.getKey -> NonEmptyChunk.fromIterableOption(entry.getValue.asScala)).collect {
          case (key, Some(value)) => key -> value
        },
      )
    }
    .refineToOrDie[IllegalArgumentException]
```

**Comment by frekw** [comment]
I've given this some more thought. In a lot of ways parsing forms is very similar to what `zio-config`s `ConfigDescriptors` are doing, perhaps with the added possibility to easily specialize a field with added validation?


```scala
val myForm = (Form.string("name").withValidation(notEmpty && minLength(1)) zip Form.string("email").withValidation(validEmail)).map { (name, email) => ??? }

myForm.parse(request) // Either[NonEmptyChunk[E], A]
```

**Comment by frekw** [comment]
I came up [with this](https://gist.github.com/frekw/6c9d16dd974aacf9af683f60dd8eb4fe).

That allows me to do the following:

```scala
object Main extends ZIOAppDefault {
  import FormValue._
  import zio.prelude.{Subtype, Validation}
  import zio.prelude.Assertion
  import zio.prelude.Assertion._
  
    object Email extends Subtype[String] {
    override def assertion                        = assert {
      Assertion.matches("(?i)^[A-Z0-9_+-]+(\\.[A-Z0-9_+-]+)*@[A-Z0-9][A-Z0-9_-]*(\\.[A-Z0-9_-]+)*\\.[A-Z]{2,10}$")
    }
  }
  type Email = Email.Type
  

  val name   = string("name").map(_.toUpperCase())
  val email  = string.mapOrFail(Email.make(_))

  val form =
    (string("name") zip int("age") zip boolean("bool").default(false) zip optional(string("maybe")) zip email(
      "email"
    )).map { case (n, a, b, m, e) =>
      val x = n
      s"$n :: $a :: $b :: $m :: ${foo(e)}"
    }

  def foo(e: Email): String = e.toString.toUpperCase

  def run: ZIO[Environment with ZIOAppArgs with Scope, Any, Any] =
    for {
      res <- form
               .decode("name=Fredrik&age=35&bool=true&maybe=shrug&email=foo@bar.se")
               .tapError(err => ZIO.debug(s"err: ${err}"))
      _   <- ZIO.debug(s"res: $res")
    } yield ()
}

```

What I find nice about it is that it easily allows me to combine extracting data out of forms and also parsing them using e.g zio-prelude, while still keeping track of the path in the form that failed (is possible). I tried going down the zio-schema route first, but handling custom subtypes felt tricker (which could very well be to my inexperience with zio-schema).

Would be happy to take feedback and work to integrate it into zio-http, but it currently makes quite heavy use of `ZValidation` to aggregate errors so I'm not sure what you think of zio-prelude as an additional dependency @jdegoes?

**Comment by jdegoes** [comment]
I would go down the ZIO Schema rabbit hole: just encode the information into a DynamicValue, and then use the Schema#fromDynamic to load it into the specified type. That's the easiest way. Gives you good errors too.

**Comment by scottweaver** [comment]
Checkout this PR, https://github.com/zio/zio-http/pull/1953.

It supports codecs for both url-encoded and multi-part forms using a single `Form` data structure.

There are also new operators on `Body` that allow for encoding and decoding to and from both form encodings.

It doesn't use zio-schema, though I am guessing it could be ported eventually.
