### ISSUE TITLE
Not possible to use the `CSRF` middleware via `<form>`s

### ISSUE THREAD

**Issue by frekw** [zio/zio-http#1757]
**Describe the bug**
Since the [`csrfGenerate`](https://github.com/zio/zio-http/blob/dfc18d1b4b1a02de3104c6251b5be565b80756a7/zio-http/src/main/scala/zio/http/api/Middleware.scala#L277) only adds the CSRF-token via `Middleware.addCookieZIO`, it will only be available after the response has been processed. In order to have CSRF validation for forms, I need to be able to add a hidden `_csrf_token` `<input>` to the form I'm submitting. But since the token hasn't been generated yet that's not possible.

**Expected behaviour**
To support CSRF tokens for forms. This means we might need a way to keep track of something stateful (perhaps a `FiberRef`?) for the request.

**Comment by vigoo** [comment]
Related to #1761

**Comment by jdegoes** [comment]
Closing for now, as I think this has been fixed. cc @vigoo
