### ISSUE TITLE
Feature: A middleware can produce value that can be propagated thru the next handlers

### ISSUE THREAD

**Issue by guersam** [zio/zio-http#1761]
**Is your feature request related to a problem? Please describe.**
When I write web servers, there are repeated use cases that I want to reuse common logics producing some context info e.g. auth session, correlation id, etc., and use the value in the application/business logic.

For example, an authentication middleware in a Node.js web server does:
1. Read the auth token from the request header
2.  Attempt to load a login session from the session storage with the token
3.  If the session is invalid, reject the request with a 401 response
4.  Otherwise keep the retrieved `Session` (or `User`) in the request/context object

I wonder if we can achieve the same ergonomics in a much safer way.

**Describe the solution you'd like**
1. A middleware can produce a typed value. 
2. The value can (somehow) be used in the next middleware and endpoint handlers.

**Describe alternatives you've considered**
For some crucial parts like authentication/authorization, some dedicated inputs and handlers might be added to `EndpointSpec` like [tapir does](https://tapir.softwaremill.com/en/latest/server/logic.html#re-usable-security-logic)

Also, there is [an existing workaround](https://github.com/ghostdogpr/caliban/blob/v2.0.1/examples/src/main/scala/example/ziohttp/AuthExampleApp.scala#L83-L93) using (Fiber)Ref with R type, but it doesn't guarantee the the user is authenticated in type level.

**Additional context**
I'm promoting this issue from [a comment in the middleware redesign ticket.](https://github.com/zio/zio-http/issues/1501#issuecomment-1260418534)

**Comment by BalduinLandolt** [comment]
I did something like this recently. The following middleware requires an `AuthenticatorService` that knows how to authenticate the user, given a request (i.e. extract the token, validate, etc.).

```scala
final case class AuthenticationMiddleware(authenticatorService: AuthenticatorService) {

  /**
   * An authentication middleware that transforms a HttpApp (Request => Response)
   * into a custom Http ((Request, User) => Response).
   * This makes the requesting user available in the context of the request in a ZIO HTTP route.
   *
   * Can be used like this:
   *    {{{
   *      final case class Route(authMiddleware: AuthenticationMiddleware){
   *        private val middleware = authMiddleware.authenticationMiddleware
   *
   *        private val authenticatedRoutes: UHttp[(Request, User), Response] =
   *          Http.collectZIO[(Request, User)] {
   *            case (Method.GET -> !! / "admin" / "users", user: User)  => ???
   *          }
   *
   *        val routes = authenticatedRoutes @@ middleware
   *      }
   *    }}}
   */
  val authenticationMiddleware: UMiddleware[(Request, User), Response, Request, Response] =
    Middleware.codecZIO[Request, Response](
      request =>
        for {
          requestingUser <-
            authenticatorService
              .getUser(request)
              .orElseSucceed(Users.AnonymousUser)
        } yield (request, requestingUser),
      out => ZIO.succeed(out)
    )
}

object AuthenticationMiddleware {
  val layer: URLayer[AuthenticatorService, AuthenticationMiddleware] =
    ZLayer.fromFunction(AuthenticationMiddleware.apply _)
}
```

I don't know if that meets your criteria for "ergonomic", but it works... so maybe an example like this should be included in the docs?

---

**Edit:** I just realized that doesn't work in `v0.0.4` but it used to in `v0.0.3` - will update my comment once I know what's going on.
