### ISSUE TITLE
0.0.3 logging regression, no longer propagated

### ISSUE THREAD

**Issue by fancellu** [zio/zio-http#1811]
**Describe the bug**

I've just upgraded the below repo to 0.0.3, but now I see that logging context is not propagated

https://github.com/fancellu/zio-restful-webservice

**To Reproduce**

If you run it up and go to localhost:8080/up you'll see that logging output is not coloured, as it used to be in 2.0.0-RC11
Looks like what we had in RC10 https://github.com/dream11/zio-http/issues/1352

**Expected behaviour**

Coloured logging

The prev 2.0.0-RC11 version worked just fine https://github.com/fancellu/zio-restful-webservice/commit/7084d7655356a1034f2e247bbcf23c4c01f9ee2b

You can "fix" it by supplying the logger directly, as we had to in RC10

e.g. .provideLayer(MainApp.logger) 

but that is obviously not ideal

**Comment by bilal-fazlani** [comment]
👀

**Comment by adamgfraser** [comment]
@fancellu Can we minimize this further? This simple example works correctly so I am wondering what is different in your application.

```scala
import zio._
import zio.http._
import zio.http.model._

object Example extends ZIOAppDefault {

  val logger =
    ZLogger.default.map(_.toUpperCase).map(println)

  override val bootstrap =
    Runtime.removeDefaultLoggers >>> Runtime.addLogger(logger)

  val app: HttpApp[Any, Nothing] =
    Http.collectZIO[Request] { case Method.GET -> !! / "test" =>
      ZIO.log("test").as(Response.text("Hello World!"))
    }

  val run =
    Server.serve(app).provide(Server.default)
}
```

```
[info] TIMESTAMP=2023-01-15T15:05:47.537019Z LEVEL=INFO THREAD=#ZIO-FIBER-25 MESSAGE="TEST" LOCATION=<EMPTY>.EXAMPLE.APP.APPLYORELSE FILE=EXAMPLE.SCALA LINE=15
```

**Comment by fancellu** [comment]
Yes, your Example works thanks. I added another non working ExampleNotWorking 
https://github.com/fancellu/zio-restful-webservice/tree/1811-logging-issue
i.e. My MainApp creates a logger, and uses provide. I think that is the issue. As best as I can tell, this used to work. 
I'm happy to use your way of doing things and will update my repo

**Comment by adamgfraser** [comment]
This also works:

```scala
import zio._
import zio.http._
import zio.http.model._

object Example extends ZIOAppDefault {

  val logger =
    ZLogger.default.map(_.toUpperCase).map(println)

  val app: HttpApp[Any, Nothing] =
    Http.collectZIO[Request] { case Method.GET -> !! / "test" =>
      ZIO.log("test").as(Response.text("Hello World!"))
    }

  val run =
    Server.serve(app).provide(Server.default).provide(Runtime.removeDefaultLoggers >>> Runtime.addLogger(logger))
}
```

**Comment by fancellu** [comment]
I fixed my repo thanks
https://github.com/fancellu/zio-restful-webservice/commit/efc3bc7278bb37b18a33a6caf215d7766e6fd80d
