### ISSUE TITLE
Simplify specializing the NettyDriver

### ISSUE THREAD

**Issue by frekw** [zio/zio-http#1813]
**Is your feature request related to a problem? Please describe.**
More control over the NettyDriver is sometimes desirable, for example being able to share the EventLoopGroup and ChannelFactory when writing integration tests. While currently possible, setting everything up to be shareable is more annoying than it could be, and currently involved duplicating most of the layer-related code from NettyDriver (but with less type ascriptions, since a lot of the needed types are `private[zio]`).

[An example](https://github.com/softwaremill/tapir/blob/947202d2dd8cce5a002aa4e8e1c064fc2fc17420/server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala#L27-L66) of what it currently looks like.

**Comment by adamw** [comment]
To add some background, this used to work fine with older versions of zio-http.

We need this feature in tapir to quickly run a large number of tests which start & stop multiple HTTP servers. Here's how we've been using the configuration:

https://github.com/softwaremill/tapir/blob/779274f64813e5783bb8804c80dfa050894689dd/server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala#L24-L25

**Comment by jdegoes** [comment]
cc @scottweaver

**Comment by scottweaver** [comment]
Is the desire just to have control over the `EventLoopGroup` and the `ChannelFactory[ServerChannel])`, or more than that?

**Comment by adamw** [comment]
@scottweaver yes, these are the dependencies that we are providing as shared resources
