### ISSUE TITLE
HTTP Client OOM

### ISSUE THREAD

**Issue by Raawaan** [zio/zio-http#1867]
**Describe the bug**
I'm trying to consume 10M events from ZIO-Kafka and send HTTP request for each using ZIO HTTP client. unfortunately, I got the below exception when It reaches the consumption of the 2M+ events

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ZScheduler-Supervisor"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ZScheduler-2"
```

note that consuming the 10M and committing them using offset-batches without sending the HTTP requests works fine without using any additional memory and the GC performs great.

**Screenshots**

***sending the HTTP request for each event (fails at the consumption of 2M events)***
jconsole
<img width="1395" alt="Screen Shot 2022-12-07 at 11 51 05 AM" src="https://user-images.githubusercontent.com/20085190/206146140-626e026f-eb1a-4e44-b69d-59069771312a.png">

jmap 
<img width="902" alt="Screen Shot 2022-12-07 at 11 51 58 AM" src="https://user-images.githubusercontent.com/20085190/206146289-a4b8e767-6a20-4e4c-969f-5b844a0ef826.png">

***without sending the HTTP request for each event***
jconsole
<img width="1373" alt="Screen Shot 2022-12-07 at 11 56 22 AM" src="https://user-images.githubusercontent.com/20085190/206147347-601a6fe4-f751-4680-910e-fc2b4787c62e.png">

jmap
<img width="966" alt="Screen Shot 2022-12-07 at 11 56 40 AM" src="https://user-images.githubusercontent.com/20085190/206147406-8754b681-f758-45c2-81c0-f0c805c88dba.png">

**Desktop:**
 - OS: macOS Monterey  
 - Version ZIO-HTTP version 0.0.3 (I've tried to use 2.0.0R but due to the  limitation of client-config I switched to 0.0.3 as it contains more configs for the client ex: connection-pool)

**Comment by adamgfraser** [comment]
@Raawaan Can you try upgrading to ZIO 2.0.5?

**Comment by Raawaan** [comment]
unfortunately, after upgrading to ZIO 2.0.5 I got a similar exception 

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ZScheduler-0"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ZScheduler-3"
```

screenshot for jmap 
<img width="827" alt="Screen Shot 2022-12-07 at 5 02 45 PM" src="https://user-images.githubusercontent.com/20085190/206214218-2cc20333-d4b2-4297-8212-ae42cca78c22.png">


also, I'm not creating any "scala.Tuple2, "scala.collection.immutable" ..etc objects.

**Comment by adamgfraser** [comment]
Alright. If you can create a minimized reproducer we will take a look.

**Comment by Raawaan** [comment]
@adamgfraser kindly find the repo here https://github.com/Raawaan/pre-launch-consumer
topic "subscriber-msg-ten-million" contains 10 million events.

thank you

**Comment by adamgfraser** [comment]
Minimized:

```scala
import zio._
import zio.http._
import zio.http.model._
import zio.http.netty.client._
import zio.stream._

object Example extends ZIOAppDefault {

  val stream = ZStream.iterate(0)(_ + 1)

  val echo = Http.collect[Request] {
    case Method.GET -> !! / n => Response.text(n)
  }

  def request(n: Int): ZIO[Client, Throwable, Response] =
    Client.request(s"http://localhost:8080/$n")

  val workflow =
    for {
      _ <- Server.serve(echo).fork
      _ <- stream.mapZIO(request).mapZIO(_.body.asString).debug.runDrain
    } yield ()

  val run =
    workflow.provide(
      Server.live,
      ServerConfig.live,
      Client.live,
      ClientConfig.live(ClientConfig(connectionPool = ConnectionPoolConfig.Dynamic(100, 10000, 1.second))),
      ConnectionPool.auto,
      Scope.default
    )
}
```

**Comment by Raawaan** [comment]
exactly, got a similar error for this minimized version 
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "zio-timer-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ZScheduler-Supervisor"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RMI Scheduler(0)"
Exception in thread "RMI TCP Connection(idle)" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RMI TCP Connection(idle)"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RMI TCP Connection(idle)"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ZScheduler-5"
```

**Comment by rajcspsg** [comment]
I ran @adamgfraser code in my local and got the heapdump [here](https://easyupload.io/m/862fz1). I would be available for only 30 days

**Comment by rajcspsg** [comment]
@adamgfraser I rewrite your code as below. The difference is it is calling external http server.

```
import zio.{ZIOAppDefault, _}
import zio.http._
import zio.http.model._
import zio.http.netty.client._
import zio.stream._

object ZioHttpErrorDemo2 extends ZIOAppDefault {
  val stream = ZStream.iterate(0)(_ + 1)

  def request(n: Int): ZIO[Client, Throwable, Response] =
    Console.printLine(n) *> Client.request(s"https://httpbin.org/get")

  val workflow :ZIO[Client, Throwable, Unit] = stream.mapZIO(request).runDrain

  val run =
    workflow.provide(
      Client.live,
      ClientConfig.live(ClientConfig(connectionPool = ConnectionPoolConfig.Dynamic(100, 10000, 1.second))),
      ConnectionPool.auto,
      Scope.default
    )

```

I will upload heap dump results shortly.

**Comment by adamgfraser** [comment]
@rajcspsg I don't think we need more reproducers. My original example already reproduces the issue without a dependency on an external server. We just need to fix it.
