### ISSUE TITLE
Not possible to bind to multiple ports.

### ISSUE THREAD

**Issue by Kreinoee** [zio/zio-http#1933]
**Describe the bug**

I have a project having two different API; an internal one and a external one, and they should be served on 2 different ports. 

I have tried multiple things to make it work, but did not succeed. Typically only one of the server ends up being bound.

I have tried providing the the Server instance in local scope, to make each HTTP server have it's own instance to work on:

```
package sandbox

import zio.{Scope, ZIO, ZIOAppArgs, ZIOAppDefault}


object ZioMain extends ZIOAppDefault {

  val toRun = for {
    _ <- HttpServer1.serveFork.provide(HttpServer1.live)
    _ <- HttpServer2.serveFork.provide(HttpServer2.live)
  } yield ZIO.unit

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = toRun
}

```

Where the HttpServer objects are defined like this:

```
package sandbox

import zio.http.ServerConfig.LeakDetectionLevel
import zio.http.ServerConfig.default.nThreads
import zio.{Fiber, URIO, ZIO, ZLayer}
import zio.http.model.Method
import zio.http._

object HttpServer1 {

  private def http(): Http[Any, Nothing, Request, Response] = {
    Http.collectZIO[Request] {
      case Method.GET -> !! =>
        ZIO.succeed(Response.text("Hello from Server 1"))
      case Method.GET -> !! / "are_you_server_1" =>
        ZIO.succeed(Response.text("YES"))
    }
  }

  def serveFork: URIO[Server, Fiber.Runtime[Nothing, Nothing]] = Server.serve(http())

  def live: ZLayer[Any, Nothing, Server] = configLayer >>> Server.live.orDie

  def configLayer: ZLayer[Any, Nothing, ServerConfig] = {
      ServerConfig.live(
        ServerConfig.default
          .port(8080)
          .leakDetection(LeakDetectionLevel.PARANOID)
          .maxThreads(nThreads)
      )
  }
}

```
Server 2 is the same, beside some replaced strings and port 8081.

But in this case, only server 1 is end up listening and answering requests. 

I have also tried Making the `live` methed in the servers return a wrapper type around the server, so that the `serveFork` method could require that instead of the Server directly, and then install it like:

```
  def serveFork: URIO[Server1, Fiber.Runtime[Nothing, Nothing]] = {
    (ZIO.serviceWithZIO[Server1](
      _.underlying.install(http())
    ) *> ZIO.never).fork
  }
```
And then provide the two Server1 and Server2 layers in the global environment at the outermost ZIO.  However this yields the same result, only one of them will be running. 

Finally I also tried to use Server.Base instead, and to provide it with NettyDriver my self. Using NettyDriver.default did not change the result. I also tried looking into creating NettyDriver my self, with NettyDriver.make, but had a hard time reproducing how NettyDriver.default works, as it uses package private stuff.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build some code based on the examples from the description
2. Start the service
3. Try to make http request to localhost:8080 and localhost:8081
4. See tha only one of the servers is reachable.

**Expected behaviour**
I would have expected both servers to be running, listening on one port each.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Comment by vigoo** [comment]
Thanks for the report @Kreinoee!

This seems to be a problem in your code:

`Serve.serve` starts the server and never returns (it contains `*> ZIO.never`) so you need to run it from a forked fiber in order to be able to start the next server too.

I assume you had this `.fork` in `serveFork` before (but it's not there in the example code above). Adding it there is still not good, because then we have something like this (after some inlineing):

```scala
_ <- Server.serve(app1).fork.provide(HttpServer1.live)
_ <- Server.serve(app2).fork.provide(HttpServer2.live)
```

The problem here is that the two `HttpServer` layers are created, then the server's fiber is forked, and immediately after the fork the layers get released (that's how `provide` works - the provided layer's scope ends after it. So the reference to the HttpServer leaks into the forked fiber, but the underlying Netty services get immediately released.

The proper order of operations is:

```scala
_ <- Server.serve(app1).provide(HttpServer1.live).fork
_ <- Server.serve(app2).provide(HttpServer2.live).fork
```
