### ISSUE TITLE
Custom logger didn't work on version `2.0.0-RC10`

### ISSUE THREAD

**Issue by patrhez** [zio/zio-http#1940]
**Describe the bug**

My custom logger cannot be propagated to the http app on zio-http version `2.0.0-RC10`

**To Reproduce**

1. Clone the project from https://zio.dev/guides/quickstarts/restful-webservice 
2. Rewrite the build.sbt file:
```
scalaVersion := "3.2.0"
organization := "dev.zio"
name := "zio-quickstart-restful-webservice"

libraryDependencies ++= Seq(
  "dev.zio" %% "zio" % "2.0.1",
  "dev.zio" %% "zio-json" % "0.3.0-RC11",
  "io.d11" %% "zhttp" % "2.0.0-RC10",
  "io.getquill" %% "quill-zio" % "4.3.0",
  "io.getquill" %% "quill-jdbc-zio" % "4.3.0",
  "com.h2database" % "h2" % "2.1.214",
  "dev.zio" %% "zio-logging" % "2.1.7",
  "dev.zio" %% "zio-logging-slf4j" % "2.1.7",
  "ch.qos.logback" % "logback-classic" % "1.4.5"
)
```
```scala
package dev.zio.quickstart

import zhttp.http.*
import zhttp.service.Server
import zio.*
import zio.logging.*
import zio.logging.LogFormat.*
import zio.logging.backend.SLF4J

object MainApp extends ZIOAppDefault {

  val logger = ZLogger.default.map(_.toUpperCase).map(println)

  override val bootstrap: ZLayer[ZIOAppArgs, Any, Any] =
    Runtime.removeDefaultLoggers >>> Runtime.addLogger(logger)

  val app: Http[Any, Nothing, Request, Response] =
    Http.collectZIO[Request] {
      case Method.GET -> !! / "test" => {
        ZIO.log("test").as(Response.text("Hello world"))
      }
    }

  override val run = Server.app(app).withPort(8081).startDefault
}
```

The output:
```shell
timestamp=2023-01-15T07:56:20.964235Z level=INFO thread=#zio-fiber-33 message="test" location=dev.zio.quickstart.MainApp.app file=MainApp.scala line=27
```

**Expected behaviour**

The http app should apply the custom logger and uppercase the logs

**Additional context**
@adamgfraser provided the example code under the original issue https://github.com/zio/zio/issues/7705

Thanks!

**Comment by adamgfraser** [comment]
@PengzhengHe That version of ZIO HTTP is more than six months old and as described in my linked comment the example works correctly on both the most recent ZIO HTTP version `0.0.3` as well as the latest snapshot. Can you please try using the most recent version and either post an updated minimized reproducer or close this issue if the bug no longer occurs?

**Comment by patrhez** [comment]
After switching from `"io.d11" %% "zhttp" % "2.0.0-RC10"` to `"dev.zio" %% "zio-http" % "0.0.3"` and it works.

Thanks.
