### ISSUE TITLE
Multiple set-cookie headers may be handled incorrectly if there are other headers

### ISSUE THREAD

**Issue by paul-lysak** [zio/zio-http#1960]
**Describe the bug**
If there are other headers besides `set-cookie` then `set-cookie` headers may be packed into the single header instead of being kept in separate headers. 

**To Reproduce**
Unit test for the HeaderSpec (will be added to the PR):
```
      test("should encode multiple cookie headers as two separate headers also if other headers are present") {
        val cookieHeaders = Headers(HeaderNames.setCookie, "x1") ++ Headers(HeaderNames.setCookie, "x2")
        val otherHeaders = Headers(HeaderNames.contentType, "application/json")
        val result        = (otherHeaders ++ cookieHeaders).encode.entries().size()
        assertTrue(result == 3)
      },
```

**Expected behaviour**
Each `set-cookie header` 

**Additional context**
`Headers.encode` uses `span` instead of `partition`, so it divides the headers list at one specific point instead of finding all items that match the condition. 
PR will be provided.

**Comment by vigoo** [comment]
Fixed by #1961
