### ISSUE TITLE
Unhandled HTTP Method returns Internal server error

### ISSUE THREAD

**Issue by bilal-fazlani** [zio/zio-http#1967]
**Describe the bug**

**Given** an endpoint is created at a route with HTTP Verb GET, 
**When** an HTTP request is executed with POST verb, 
**Then** server returns HTTP 500 as a response

**To Reproduce**

```scala
import zio.http.{Server, ServerConfig}
import zio.http.api.*
import zio.ZIO

object Main extends zio.ZIOAppDefault {
  val spec = EndpointSpec.get("api" / "sample")
  val endpoint = spec.implement(input => ZIO.unit)

  val httpApp = spec.toServiceSpec.toHttpApp(endpoint)

  override def run = Server
    .serve(httpApp)
    .exitCode
    .provide(
      ServerConfig.live(ServerConfig.default.port(9092)),
      Server.live
    )
}
```

```bash
bash-3.2$ curl -X POST http://localhost:9092/api/sample --verbose
*   Trying 127.0.0.1:9092...
* Connected to localhost (127.0.0.1) port 9092 (#0)
> POST /api/sample HTTP/1.1
> Host: localhost:9092
> User-Agent: curl/7.85.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 0
<
* Connection #0 to host localhost left intact
```

**Expected behaviour**

It should return either [HTTP Status 405](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405) or [HTTP Status 404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)

**Version**

"dev.zio" %% "zio-http" % "0.0.4"

**Additional context**

This problem only occurs when using `EndpointSpec`.
When using building the routes manually, it does return `HTTP Status 404` expected.

```scala
  val app = Http.collect {
    case GET -> !! / "api" / "sample" => Response.ok
  }
```

**Comment by vigoo** [comment]
Currently the HandlerTree only considers static path segments to find the handler, and all the remaining conditions, including the method check are evaluated as input decoders which fail in case of not matching (in EndpointServer).

I think everything that we want to handle as 404 should be part of the tree including the methods - and only fail with 500 when the remaining input decoders are failing (for example unexpected body). (and we should generate better error response but that's out of scope of this).
