### ISSUE TITLE
Server doesn't call errorCallback

### ISSUE THREAD

**Issue by heaven-born** [zio/zio-http#1973]
**Describe the bug**

When you do  `Server.serve(app, Some(errorCallback))` the `errorCallback` is never called on fatal error.

**How to reproduce**

`case Method.GET -> !!   =>   ZIO.die(new RuntimeException("I'm dead"))`

**Additional context**

I've tracked down the issue till `ServerInboundHandler`.  Def  `exceptionCaught` is not called on fatal error produced on endpoint call. 

Method `writeResponse` catches all the errors and doesn't call `errCallback` on the error. 

**Version**

Specification-Version: 0.0.4
Implementation-Version: 0.0.4

**Comment by vigoo** [comment]
Currently the `HandlerTree` only considers static path segments to find the handler, and all the remaining conditions, including the method check are evaluated as input decoders which fail in case of not matching (in `EndpointServer`).

I think everything that we want to handle as `404` should be part of the tree including the methods - and only fail with `500` when the remaining input decoders are failing (for example unexpected body). (and we should generate better error response but that's out of scope of this).
