### ISSUE TITLE
Clients on Endpoints need an Error type

### ISSUE THREAD

**Issue by csar** [zio/zio-http#1986]
the executor of an http call is a Task[A], we need a bit more in case of failure. Any error from the server basically shows as a parsing error from the Schema, so now idea about the nature of the failure

The old api allowed access to the response object to perform a more elaborated handling.

I guess adding an optional error handler or to toServiceSpec would be a good starting point. Perhaps on the final executor a mapError if the type of the executor will be an IO[E,A] and E allows working with the full response object (to detect timeouts or just logging and test response from the body)

**Comment by jdegoes** [comment]
I will close this issue as it's fixed in my PR (#1881) that will be merged shortly.
