### ISSUE TITLE
HTTP model for Methods

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#2]
Create representation of HTTP methods defined in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4)

Put them inside `zio.http.Method`.

- [ ] GET
- [ ] HEAD
- [ ] POST
- [ ] PUT
- [ ] OPTIONS
- [ ] TRACE

**Comment by env0der** [comment]
Here is a PR: https://github.com/zio/zio-http/pull/9
