### ISSUE TITLE
Apps created from endpoints do not correctly fall back on other apps

### ISSUE THREAD

**Issue by ccerbusca** [zio/zio-http#2001]
When creating apps from endpoints and then combining the apps together, requests to the first endpoint in the chain will succeed, while requests to subsequent endpoints will always fail. In the reproducer below, get requests to `/test` will succeed while requests to `/test2` will fail. 

Small reproducer:
```scala
import zio.*
import zio.http.codec.HttpCodec.*
import zio.http.endpoint.*
import zio.http.{ Middleware, Server }

object Main extends ZIOAppDefault {

  val endpoint =
    Endpoint
      .get("test")
      .out[String]
      .implement(_ => ZIO.succeed("Success1"))

  val endpoint2 =
    Endpoint
      .get("test2")
      .out[String]
      .implement(_ => ZIO.succeed("Success2"))

  override def run =
    Server
      .serve((endpoint.toApp ++ endpoint2.toApp) @@ Middleware.debug)
      .provide(
        Server.defaultWithPort(8080)
      )

}
```

**Expected behaviour**
GET requests to the `/test2` endpoint should succeed

**Additional context**
Happens on the latest snapshot version of `zio-http` with `Scala 3.2.2`

**Comment by jdegoes** [comment]
@vigoo This seems reasonable even though it conflicts with other work we've done. 

Endpoints have enough information to provide good NotFound errors. Yet sometimes users will want to combine them with manual routes. 

Maybe we need something like `toApp` and `toHandler`? The handler has to handle every request, the app doesn't. 

Any other ideas?

**Comment by vigoo** [comment]
@jdegoes I think `toApp` should create a `Http` which does not handle the routes that `Endpoint` does not specify, and should not manually create 404 responses (but it still should create other error responses for failures).

This way it would work equivalent to hand-written `Http` apps. 

Currently `Http`s which are not handling a given request are handled explicitly in the server (in the netty channel handler), generating a 404 response. I just got the idea that maybe the server should not work with `Http[Any, Response, Request, Response]` but `Handler[Any, Response, Request, Response]` internally, and any `Http` can be automatically converted to that by `http.toHandler(default = Response.notFound)` (but this change is not required to solve this issue)

**Comment by jdegoes** [comment]
@vigoo Okay, agreed!
