### ISSUE TITLE
Apps are ignored if they are installed after the first request is processed

### ISSUE THREAD

**Issue by johnsonjii** [zio/zio-http#2003]
Because the App in the NettyDriver is stored in an AtomicReference and is carefully updated in the driver's addApp() method it seems that the app should be able to be updated dynamically. Unfortunately, after the first request has been processed by the server, the app can no longer be updated.

```
import zio._
import zio.http._
import zio.http.model.{Method, Status}
import zio.http.netty.client.NettyClientDriver
import zio.test._

object DynamicAppTest extends ZIOSpecDefault {

  val httpApp1: App[Any] = Http.collect[Request] {
    case Method.GET -> !! / "good" => Response.ok
  }.withDefaultErrorResponse

  val httpApp2: App[Any] = Http.collect[Request] {
    case Method.GET -> !! / "better" => Response.status(Status.Created)
  }.withDefaultErrorResponse

  val layer =
    ZLayer.make[Client & Server](

      ClientConfig.default,
      NettyClientDriver.fromConfig,
      Client.live,

      ServerConfig.live,
      Server.live,
    )

  def spec = suite("Server")(

    test("Should allow dynamic changes to the installed app") {
      for {
        port <- Server.install(httpApp1)
        okResponse <- Client.request(s"http://localhost:$port/good")
        _ <- Server.install(httpApp2)
        createdResponse <- Client.request(s"http://localhost:$port/better")
      } yield assertTrue(
        okResponse.status == Status.Ok &&
            createdResponse.status == Status.Created) // fails here because the response is Status.NotFound
    }.provideLayer(layer)
  )
}
```

Note that reversing lines 33 and 34 causes the test to succeed.

It appears that the reason is because the AtomicReference is read once and stored in a lazy val in ServerInboundHandler. This means that after the lazy val is referenced the first time, the contents of the AtomicReference are never again referenced. Following the first request any changes to the AtomicReference are ignored.

**Comment by jdegoes** [comment]
This needs to be fixed (it was working originally and broken-by-optimization).
