### ISSUE TITLE
Unable to use `NettyDriver` in Scala 2.12

### ISSUE THREAD

**Issue by frekw** [zio/zio-http#2006]
**Describe the bug**
It seems like there's currently an issue with using the `NettyDriver` in Scala 2.12. This has forced Tapir to drop Scala 2.12 support for zio-http. I'm not that well-versed in 2.12, but it seems like the root cause of the issue being that the `NettyDriver` trait is `private[zio]` but the companion object defining the ZLayers not having any access modifiers, resulting in the following error:

```
[error] /Users/adamw/projects/tapir/server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala:65:7: object NettyDriver in package server cannot be accessed in package zio.http.netty.server
```
I think there are good reasons to keep `NettyDriver` private, but perhaps we can move the constructors to the `zio.http.netty.server` package object instead, or at least expose them from it?

**Comment by jdegoes** [comment]
Sounds good.

**Comment by frekw** [comment]
Hah you beat me to it @vigoo :)

Would be greatly appreciated if we could get a new release of zio-http once this is merged. That'll allow me to re-add support for Scala 2.12, which in turn means that I'll be able to re-add Scala 2.12 support for zio-http in Tapir.

The reason why I'm asking is because @ghostdogpr is gearing up to release Caliban 2.1 which contains a lot of changes and I would love it if we could get an upgraded zio-http version in there (it's still on 2.0.0-RC10). But that requires support for 2.12! 🙏
