### ISSUE TITLE
Logger does not propagate into `Http`

### ISSUE THREAD

**Issue by calvinlfer** [zio/zio-http#2016]
**Describe the bug**
This is the same issue as https://github.com/zio/zio-http/issues/1352
When using an SLF4J logger with ZIO HTTP, the logger logs in the correct format only outside an Http, but inside the Http the logger format is the default one.

**To Reproduce**
Steps to reproduce the behaviour:

```scala
import zio.*
import zio.http.*
import zio.http.model.*

object Repro extends ZIOAppDefault {
  val logger = Runtime.removeDefaultLoggers >>> SLF4J.slf4j(format)

  val app = Http.collectZIO[Request] { case Method.GET -> !! =>
    ZIO.logInfo("this is a message") *> // this is logged in the default format
      ZIO.succeed(Response.ok)
  }

  def run =
    val program =
      for
        _   <- ZIO.logInfo("Starting app") // this logs fine
        app <- Server.serve(app.withDefaultErrorResponse)
      yield app

    program.provide(
      logger,
      Server.live,
      ZLayer.succeed(ServerConfig.default.port(9000))
    )
}
```

**Expected behaviour**
Both "Starting app" and "this is a message" should be logged in the SLF4J format.

This is with zio-http 0.0.4 and Scala 3.2.2

**Additional context**
If you do the following then it will correctly.
```scala
Server.serve(app.withDefaultErrorResponse.provideSomeLayer(logger))
```

I see that @adamgfraser actually fixed this in an earlier version (https://github.com/zio/zio-http/pull/1379) but I no longer see an HttpRuntime

**Comment by vigoo** [comment]
You need to set up the logging earlier than initializing the zio-http server. 

For example in the above example 

```scala
program.provide(Server.live, ZLayer.succeed(ServerConfig.default.port(9000))).provide(logger)
```

would work.

**Comment by vigoo** [comment]
I would not consider it as a bug - we cannot really enforce this initialization order as the logger is not part of the environment. @jdegoes what do you think?

**Comment by adamgfraser** [comment]
This is why configuration like logging should be done as part of the `bootstrap` layer.

**Comment by calvinlfer** [comment]
Ahh okay, I understand now. This does work as intended so this is not an issue for me
```scala
object Repro extends ZIOAppDefault {
  val logger = Runtime.removeDefaultLoggers >>> SLF4J.slf4j(format)
   
  override val bootstrap: ZLayer[ZIOAppArgs, Any, Any] = logger
  // ... same as above
}
```
