### ISSUE TITLE
Adding more options to the SSL configuration

### ISSUE THREAD

**Issue by user5100** [zio/zio-http#2039]
**Is your feature request related to a problem? Please describe.**
Hi all, I would need to have more parameterization of the SSL context than it is currently available.  Basically I would need the server to also use a trustStore, to enable/disable mutual authentication between client and server, and to define other additional options, including setting a custom cipher suite.

**Describe the solution you'd like**
The solution I would need should allow the following options to be added to the ssl configuration:
- Add an option to directly pass objects of type javax.net.ssl.keyManagerFactory and javax.net.ssl.trustManagerFactory (both for both client and server contexts)
- Add an option to allow the creation and parameterization of a javax.net.ssl.SSLEngine, so as to indicate enabled cipher suites, enabled ssl protocols, client authentication, etc...
- Allow the SSL context to be changed during application execution (although I do not know if it is already possible to do this)

**Describe alternatives you've considered**
none

**Additional context**
Thank you for the support

**Comment by jdegoes** [comment]
We need to think of a way to do this in such a fashion as to minimize the imprint of the JVM in the public API, for Scala Native, etc.

**Comment by LannyRipple** [comment]
Could also use this feature.  My company has implemented a custom KeyStore to be update-aware of short-term credentials injected into K8S pods.  No telling what else they are doing under the hood but we're supposed to use it to initialize a KeyManagerFactory for SSLContext initialization.  We'd like zio-http instead of our current akka-http but this is a showstopper short of forking zio-http for an in-house workaround.

**Comment by jdegoes** [comment]
@LannyRipple How would you like to specify this? `KeyManagerFactory` and `SSLContext` are not Netty-specific so could be used in ZIO HTTP.

**Comment by LannyRipple** [comment]
I'm a bit at a loss there.  We aren't using Scala Native and such so for us it's just adding to ClientSSLConfig and modifying ClientSSLConverter to do the needful and not worrying that our zio-http would be leaking JVM types.  Sadly there's no way my team will agree to us maintaining a fork (I don't blame them).

Looking at my company's example code (SSL/PKI newbie here) it looks like we need
```scala
keyStoreInstanceName: String
keyStoreInputStreamtoLoad: => InputStream
// keyManagerFactoryAlgorithm -- going with default for now
// sslContextInstanceVersion: String -- going with latest.  suspect this doesn't change much
```
Looks like the exact same pattern for TrustStoreFactory which you would want for mTLS setup.  The following certainly leaks JVM intent but I think stays away from JVM specifics until you would be down at the Netty/Jetty/Other-JVM-Lib level.
```scala
ClientSSLConfig.FromJavaxNetSsl.builder()
  .keyStoreFactoryInfo(keyStoreInstanceName, keyStoreInputStreamThunk)
  .trustStoreFactoryInfo(trustStoreInstanceName, trustStoreInputStreamThunk)
  .build()
```
Or maybe the InputStreams are just the paths and Netty handles the reads at SslContext creation.

**Comment by constantinos-p** [comment]
Hi, I see the requirement says:  _for both client and server contexts_ 
Was the server side "symmetrical" SSLConfig implemented? 
Similarly to @LannyRipple my company is also  moving from akka to zio. 

Using akka http we could create the `SslConfig` and pass it to the akka server which is pretty standard (shown below).
Are you guys planning to support these on server side? I could open an MR myself if you want.

```
def fromConfig(config: KeystoreConfiguration): SSLContext = {
    val ks = KeyStore.getInstance(config.`type`)

    val keyStream = (config.file, config.binary) match {
      case (_, Some(binary)) =>
        new ByteArrayInputStream(Base64.getDecoder.decode(binary.getBytes(StandardCharsets.UTF_8)))
      case (Some(filePath), None) => new FileInputStream(filePath)
      case _ => throw new IllegalArgumentException("Either file or binary must be provided for SSL keystore")
    }

    ks.load(keyStream, config.password.toCharArray)

    val kmf = KeyManagerFactory.getInstance("SunX509")
    kmf.init(ks, config.password.toCharArray)

    val tmf = TrustManagerFactory.getInstance("SunX509")
    tmf.init(ks)

    val sslContext: SSLContext = SSLContext.getInstance("TLSv1.2")
    sslContext.init(
      kmf.getKeyManagers,
      tmf.getTrustManagers,
      new SecureRandom
    )

    sslContext
  }  
```
