### ISSUE TITLE
timeoutWith does not take effect

### ISSUE THREAD

**Issue by mykytamykhailenko** [zio/zio-http#2041]
I have following piece of code:

```
      response <-
        Client.request(url + s"/$domain",
          headers =
            Headers(
              Seq(
                Header("Authority", vStatInfo),
                Header("Cookie", s"$session=${conf.sessionToken}"))))
          .mapError(RequestFailure)
          .timeoutFail(FailedToCollectTraffic)(5.seconds)
```

But for some reason, this code never fails
Could you describe why it never times out?

**Comment by vigoo** [comment]
Client interruptability was fixed in https://github.com/zio/zio-http/pull/1994 and now we have tests for it which are passing. 

Is it possible that you are running the above code in an uninterruptible region?

**Comment by mykytamykhailenko** [comment]
I think I have made a mistake😅
```
      _ <- ZIO.logInfo("Start....")

      response <-
        Client.request(url + s"/$domain",
          headers =
            Headers(
              Seq(
                Header("Authority", vStatInfo),
                Header("Cookie", s"$session=${conf.sessionToken}"))))
          .mapError(RequestFailure)
          .timeoutFail(FailedToCollectTraffic)(5.seconds)
          
          _ <- execute(response)
          
          _ <- ZIO.logInfo("Success....")
```

I execute this code on a separate fiber, so when the code fails when executing `execute`, I won't see the last log message.
Also, I won't see any exception because the faulty code is executed on a separate fiber.
So yes, in fact the `timeoutFail` did work, I just could not see it.

Anyway, thank you for your support!
