### ISSUE TITLE
EncoderDecoder.encodeHeaders always adds a content-type

### ISSUE THREAD

**Issue by csar** [zio/zio-http#2044]
`EncoderDecoder.encodeHeaders` always adds a content-type and when patching the request with the MiddleWare it results in `content-type:application/json,application/json`

**To Reproduce**
Create a simple Enpoint.get and see what it is send to the host (easy to see ClientRequestEncoder::44)

**Expected behaviour**
content-type should only be added according to the body value with the explicit value from the EndpointExecutor

**Additional context**
No sure if content-type allows a list of values, but it is ugly and crashes at least with one Spring service I tried to consume

**Comment by vigoo** [comment]
Related: https://github.com/zio/zio-http/issues/1506
