### ISSUE TITLE
Unify headers

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2050]
Currently, ZIO HTTP has duplication and inconsistency in how it exposes headers.

1. We have typed structures like `Cookie[T]`, and random parts of headers such as Credentials.
2. We have some APIs that deal with header names and values as `String`.
3. We have some APIs that deal with header names and values as `CharSequence`.
4. We have typed representations of most header values in `zio.http.model.headers.values`.

We need to unify these and provide a standardized way of consuming, producing, and transforming headers, one which allows optimization, via pre-encoding structured information / strings into bytes.

**Comment by jdegoes** [comment]
Perhaps we should have `Header` that has a name and a value (we have a weird one that is a subtype of `Headers`, but we could dispense with that).

In which case, we could have all our existing header values extend `Header`, and move them into the companion object of `Header`, as a way to organize them and aid discovery (we could put the raw source in traits to avoid bloating a single file).

Then we could have a `Header.Custom` that lets you provide a custom key/value header.

For the built-in headers, such as `Header.ContentType`, we could pre-encode the header name and ensure that every header of that type uses the same key, to avoid any unnecessary allocations. 

For the custom header, we could have a method, maybe, `.optimize` or something, that caches the pre-encoded name and value, for use in high-performance situations where constant headers are needed.

**Comment by jdegoes** [comment]
A really nice feature would involve being able to do something like: `headers.get(ContentType)` and have it give you `Option[ContentType]`.

In order to do this (continued in next post)...

**Comment by jdegoes** [comment]
We could have something like this:

```scala
sealed trait HeaderType {
  type HeaderValue
}
```

Then for each header type:

```scala
sealed trait ContentType
object ContentType extends HeaderType {
  type HeaderValue = ContentType
}
```

Then `Headers#get` becomes:

```scala
sealed trait Headers {
  def get(headerType: HeaderTYpe): Option[headerType.HeaderValue] = ???
```

Moreover, `HeaderType`, extended by all companion objects, could have parse / render methods inside it, with a uniform type signature, enabling `Headers#get` to be "lazy" and not have to parse anything unless specifically requested by the user.

**Comment by vigoo** [comment]
Sounds nice, I was thinking of something similar.

**Comment by jdegoes** [comment]
Examples of data types we should unify with headers, delete, or move into header value companion objects:

 - `MediaType` (could this live inside `ContentType` and other related types, at least, organizationally??)
 - `Cookie` (too many cookies running around!)

Maybe others, as well.

**Comment by jdegoes** [comment]
`CookieDecoder` / `CookieEncoder` should go into `Cookie` header companion object.

**Comment by jdegoes** [comment]
`Decompression` should go somewhere. In companion object of config, or companion object of header, depending on what it's used for.
