### ISSUE TITLE
Simplify package structure

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2052]
With numerous other simplifications in the works, we are almost at a place where we can radically simplify the package structure, enabling users to know and care about very few packages.

- zio.http.headers.values will be reduced to 1 sealed trait + companion object, and moved into `zio.http`
- zio.http.headers "helpers" can be moved to an internal trait
- `zio.http.model` will contain only `Method`, `Status`, `Scheme`, `Version`, and `HttpError`, which can be moved into `zio.http`

This will mean that `zio.http.model` and subpackages won't exist and users can get most of what they need by importing `zio.http.*`.

**Comment by jdegoes** [comment]
Depends on #2055

**Comment by vigoo** [comment]
Same as https://github.com/zio/zio-http/issues/1454
