### ISSUE TITLE
`decoderResult` is not honored before executing the HttpApp

### ISSUE THREAD

**Issue by alphaho** [zio/zio-http#2056]
**Describe the bug**
When the client sends a request with the header size larger than the configured `maxHeaderSize`, netty will get a failure DecoderResult like `failure(io.netty.handler.codec.http.TooLongHttpHeaderException: HTTP header is larger than 1 bytes.)`, 
but the ZIO Http's HttpApp will still be executed and gets an empty request body.

**To Reproduce**
Steps to reproduce the behaviour:

```scala

import zio.Scope
import zio.http._
import zio.http.model._
import zio.test._

object NettyMaxHeaderLengthTest extends ZIOSpecDefault {
  override def spec: Spec[TestEnvironment with Scope, Any] =
    test("should get a failure instead of an empty body") {
      for {
        port <- Server.install(
                  Http
                    .collectZIO[Request] { request =>
                      request.body.asString.map { body =>
                        val responseBody = if (body.isEmpty) "<empty>" else body
                        Response.text(responseBody)
                      } // this should not be run, as the request is invalid
                    }
                    .withDefaultErrorResponse // it should execute the logic within this line
                )
        url     = s"http://localhost:$port"
        headers = Headers.userAgent("a looooooooooooooooooooooooooooog header")

        res  <- Client.request(url, headers = headers, content = Body.fromString("some-body"))
        data <- res.body.asString
      } yield {
        assertTrue(res.status == Status.InternalServerError && data == "<empty>")
      }
    }.provide(
      Client.default,
      Server.live,
      ServerConfig.live(ServerConfig(maxHeaderSize = 1))
    )
}

```

**Expected behaviour**
As the request is invalid, the HttpApp should not be executed. And the error handling logic should be executed (the `withDeafultErrorResponse` in the above snippet)

**Screenshots**
![image](https://user-images.githubusercontent.com/666504/226922961-3f9789b2-f538-489d-904e-1098af48e069.png)

**Additional context**
This above snippet was run with zio-http `0.0.4` and `0.0.5`. But it can also be reproduced in the earlier versions(e.g., `2.0.0-RC10`).

**Comment by jdegoes** [comment]
Oops sorry, wrong issue!
