### ISSUE TITLE
Make header based logging in requestLogging middleware case insensitive

### ISSUE THREAD

**Issue by giordanoj** [zio/zio-http#2060]
Currently does a case sensitive lookup.  I think typically HTTP headers are treated as insensitive.  This logger is great in general though :) 

See `zio.http.middleware.RequestLogging`

**Comment by giordanoj** [comment]
I'm open to grabbing this if people agree.  I've never contributed though, so it is quite possible I make a mess.

**Comment by vigoo** [comment]
Thanks for reporting and offering help! Looking forward for the pull request!
