### ISSUE TITLE
allow users to handle the decoding errors

### ISSUE THREAD

**Issue by alphaho** [zio/zio-http#2065]
**Is your feature request related to a problem? Please describe.**
As discussed in #2063, we would need a better way to allow users to handle the decoding errors, so that they can return different response based on their needs, which is not possible at the moment.

**Describe the solution you'd like**
Having new combinators to handle Http-intrinsic errors, e.g., a decoding error due to the header being too large.

**Describe alternatives you've considered**
(Thanks @vigoo for summarizing the alternatives)
1. Update `Http` to be modelled by `Either[DecodingError, Response] => ZIO[R, Response, Response]`
2.  model decoding errors in the `Request` class and do the check within the Http app
3. be able to produce a `Response` in the exception callback of the server.

**Comment by jdegoes** [comment]
These errors can now be handled as defects, which can be surfaced into the typed error channel if desired. 

We may need more combinators to make this process easy, but for now, will close. Thanks for reporting!

cc @vigoo

**Comment by vigoo** [comment]
My previous PR did not really solve this (no way to customize the reponse), so I'm reopening.
