### ISSUE TITLE
Allow specifying different status codes for an error ADT in Endpoint

### ISSUE THREAD

**Issue by ccerbusca** [zio/zio-http#2091]
Currently `.outError` on Endpoint is not very flexible when working with an ADT modeling different kinds of errors that could map to different status codes. It would be nice to have a method  `.outErrorWith` that takes a function that maps the ADT to a status code.

Something like

```scala
Endpoint
  .get("example")
  .out[String]
  .outErrorWith[Error] {
     case Error.Example1 => Status.BadRequest
     case Error.Example2 => Status.NotFound
     case _              => Status.InternalServerError
  }
```

**Comment by dpennell** [comment]
@vigoo Thanks for implementing this so quickly!
