### ISSUE TITLE
Server Doesn't Start with 3.0.0-RC1 and `ZIOHttpInterpreter`

### ISSUE THREAD

**Issue by ASRagab** [zio/zio-http#2110]
## Description

A possible 3.0.0-RC1 regression. When using the zio tapir integration, server does not seem to start and reports no errors when serving http routes constructed by `ZIOHttpInterpreter`. Works without issue in 0.0.5.

## Reproduction

The following gist has a minimal repro:
https://gist.github.com/ASRagab/d74409042bc080bb8ec88972a3eaade3

It can be run using `scala-cli`:
```shell
scala-cli run https://gist.github.com/ASRagab/d74409042bc080bb8ec88972a3eaade3
```

Updating the `zio-http` dependency will reproduce the error. Let me know if you have other questions.

**Comment by vigoo** [comment]
We need a new version of tapir, in progress here: https://github.com/softwaremill/tapir/pull/2850

**Comment by calvinlfer** [comment]
Hey @vigoo, Can I please have your help to confirm if I set up the test layers correctly in that Tapir PR?

**Comment by vigoo** [comment]
@calvinlfer looks good to me. Is anything in the Tapir test suite using zio-http as a client? The client is now streaming the body (in many cases) so that can be a difference. If it is only using it as a server it should work just like before.

**Comment by calvinlfer** [comment]
Thank you so much for looking @vigoo 🙏🏽 
They seem to be using the sttp client but the backend is based on the JDK HTTP client wrapped by FS2 using Cats Effect IO so I don't believe this should be an issue

**Comment by vigoo** [comment]
This should be done now by https://github.com/softwaremill/tapir/pull/2857
