### ISSUE TITLE
Streaming multipart hangs for binary files above a certain threshold unless rechunking the body stream

### ISSUE THREAD

**Issue by jgranstrom** [zio/zio-http#2127]
**Describe the bug**
Note: using `3.0.0-RC1+9-429c3938-SNAPSHOT` which includes https://github.com/zio/zio-http/pull/2116

Sending a multipart binary file that is above a certain size, close to the StreamingForm buffer of `8192`, I assume minus some header size, will cause the stream to hang indefinitely. 

**To Reproduce**
Test server:
```
Server.serve(
    Http.collectZIO {
      case req @ Method.POST -> !! => (for {
        form <- req.body.asMultipartFormStream
        _ <- form.collectAll
      } yield Response.text("done")
        ).catchAll(e => ZIO.succeed(Response.text(e.toString)))
    }
  )
```

Sending an image with size `8155` is fine:
`http --multipart localhost:8000 "file@./8155.png"`
Sending an image with size `8156`, or any size above that hangs indefinitely:
`http --multipart localhost:8000 "file@./8156.png"`

Creating the form manually with a custom buffer size, such as:
`form <- StreamingForm(req.body.asStream, boundary, 8193)`
Will now happily process one more byte, so `8156` will work, but anything above that will hang

Creating the form manually by first rechunking the body stream, such as:
`form <- StreamingForm(req.body.asStream.rechunk(1024), boundary)`
Seems to handle arbitrary sizes without hanging, although difficult to test exhaustively.

**Expected behaviour**
Any file size to be handled by streaming form without hanging. If rechunking the body stream is required for the form processing to work properly, it should probably be done by `asMultipartFormStream`

**Comment by andrzejressel** [comment]
So I've decided to take a look at it and it seems to be going deeper and just setting rechunk does not fix entirelly

So I've run `MultipartFormDataStreaming`, I've hardcoded `3000` in `asMultipartFormStream` and I've done rechunking `StreamingForm.fields`. While it works with files slightly above 3000 (like  32K), it completelly broke when I've send 80 MB file.

By broke I mean that that after waiting for several seconds I got these logs:
```
Starting to read multipart/form stream
Finished reading multipart/form stream, received 0 bytes of data
```

So I guess my file was silently dropped somewhere in the code.

**Comment by andrzejressel** [comment]
All right, so error with exec is because, exe is not detected as binary (for some reason it's set as `non-binary`).

In any case @jgranstrom I believe the issue is on your code side (although without getting deeper it can be hard co debug). As Scaladoc says
```
The result is a stream of FormField objects, where each FormField may be a
StreamingBinary or a Text object. The StreamingBinary object contains a
stream of bytes, which **has to be consumed asynchronously by the user to get
the next FormField from the stream**.
```

So you can't just iterate over formfields. To get next fold field you have to handle fold content (even if it's sending it to /dev/null).

Your code should look something like this:
```
            formFields <- form.fields.mapZIO {
              case sb: FormField.StreamingBinary =>
                sb.data.runDrain.as(sb)
              case other                         =>
                ZIO.succeed(other)
            }.run(ZSink.collectAll)
```

I've tested it with my big exe file and it works fine - still kinda slow, but maybe it can be improved somewhere else.

**Comment by andrzejressel** [comment]
I'm testing it again and is seems to be failing only when `Server.Config.default.enableRequestStreaming` is not set (that's why for some reason it war working with example in repository).

**Comment by jgranstrom** [comment]
Since it doesn't reliably reproduce without a server, I used this test suite in [`ServerSpec`](https://github.com/zio/zio-http/blob/main/zio-http/src/test/scala/zio/http/ServerSpec.scala) which reproduces it consistently:
```scala
      suite("streaming form") {
        val boundary = Boundary("X-INSOMNIA-BOUNDARY")
        val app = Http.collectZIO[Request] { case req =>
          req.body.asMultipartFormStream
            .flatMap(f => f.collectAll)
            .map(form => Response.text(form.map("file").asInstanceOf[FormField.Binary].data.size.toString))
        }

        test("this succeeds"){
          val bytes = Chunk.fill[Byte](8000)(0)
          val form = Form(Chunk(FormField.Binary("file", bytes, MediaType.image.png)))
          val res = app.deploy.body.mapZIO(_.asString).run(
            headers = Headers(Header.ContentType(MediaType.multipart.`form-data`, Some(boundary))),
            body = Body.fromMultipartForm(form, boundary)
          )
          assertZIO(res)(equalTo("8000"))
        } +
          test("this times out") {
          val bytes = Chunk.fill[Byte](8200)(0)
          val form = Form(Chunk(FormField.Binary("file", bytes, MediaType.image.png)))
          val res = app.deploy.body.mapZIO(_.asString).run(
            headers = Headers(Header.ContentType(MediaType.multipart.`form-data`, Some(boundary))),
            body = Body.fromMultipartForm(form, boundary)
          )
          assertZIO(res)(equalTo("8200"))
        }
      },
```

**Comment by andrzejressel** [comment]
Weird, it does repro for me in `MultipartFormDataStreaming` when I remove `Server.Config.default.enableRequestStreaming`.

EDIT: This is so weird, I'm starting to think Queues are to blame for this ...
