### ISSUE TITLE
Endpoint input decoding error handling

### ISSUE THREAD

**Issue by rhueara-ca** [zio/zio-http#2143]
**Describe the bug**
For the Endpoint API, I could not find a way to handle input decoding errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a endpoint and add an implementation to it:
```
val postResource = Endpoint
  .post("resource")
  .in[ResourceObject]
  .out[Unit](Status.NoContent)
  .outErrors[CustomFailure](
    HttpCodec.error[CustomFailure.Duplicate](Status.Conflict),
    HttpCodec.error[CustomFailure.Unexpected](Status.InternalServerError),
  )
val postResourceRoute = postResource.implement { (rs: ResourceObject) =>
  CreateResource(rs).map(_ => ())
}
```
2. Start the application
3. Send a request to "/resource" with an invalid JSON to be decoded into a `ResourceObject` instance (for example "{")
4. The server does not send back any response. When catching the error at `App` level, what is catched is `Cause[Response]` with value `Empty`

**Expected behaviour**
When catching the error at `App` level, an error related to malformed body is catched (maybe the existing `HttpCodecError.MalformedBody` error). Or some other way to handle decoding errors via the `Endpoint` API.

**Comment by jdegoes** [comment]
This should be catchable (after conversion to request handler) via `catchAllCause` as a defect, namely some variation of `HttpCodecError`.

/bounty $75

**Comment by rhueara-ca** [comment]
I'll try to push a fix for this soon.
