### ISSUE TITLE
Different behaviour between CustomAuthProviding and CustomAuth

### ISSUE THREAD

**Issue by ex0ns** [zio/zio-http#2159]
**Describe the bug**

The behavior between CustomAuth and CustomAuthProviding  is very different (and is probably related to the usage of the Context vs Simple middleware), in the first case, when not route are matching the middleware is not executed and the returned error is 404 (Http.empty). In the second case, as we first evaluate the middleware before being able to execute the route, the middleware is executed and returns a Unauthorized response.

**To Reproduce**
```scala
//> using lib "dev.zio::zio-http:3.0.0-RC1"
//> using scala "2.13"
//> using mainClass "Main"

import zio._
import zio.http._

object Main extends ZIOAppDefault {
  val priv = Http.collect[Request] { case Method.GET -> !! / "api" / "private" =>
    Response.text("private")
  }

  val auth = RequestHandlerMiddlewares.customAuth { headers =>
    headers.header(Header.Authorization).isDefined
  }

  // this auth middleware intercept ALL path, same for customAuthProvidingZIO
  val auth2 =
    RequestHandlerMiddlewares.customAuthProviding[Any, Header.Authorization] { headers =>
      headers.header(Header.Authorization)
    }

  val config = ZLayer.succeed(Server.Config.default.port(7070))
  // replace auth with auth2 in the next line
  val runner = Server.install(
    (priv.tapZIO(resp => Console.printLine(s"Handler: ${resp.status}")) @@ auth)
      .tapZIO(resp => Console.printLine(s"Middleware ${resp.status}"))
      .withDefaultErrorResponse
  )

  val serverFork = (runner *> ZIO.never).fork
  val client =
    Client.request("http://localhost:7070/test").map(_.status).debug("Should be not found")

  def run =
    serverFork.zipPar(client).provide(Client.default, Server.live, config)
}
```

**Expected behaviour**
In both case, if a route does not exist, the middleware should not be executed and the status not changed.
The error raised here is a bit more bigger than it seems because if we were to concatenate another Http application AFTER our middleware, it will never be executed

**Additional context**

I tried many other implementation of the `CustomAuthProviding` but I currently don't see a way out (mostly because I don't really understand how CustomAuth is able to determine if a route exist or not).

I don't think that we would be able to implement the following line when using a context (taken from the CustomAuth middleware):

```scala
Http.fromHttpZIO[Request](route.run(_).map(self(_))).withErrorHandler(route.errorHandler)
```
I tried to implement a version that would default to an `Http.empty`:
```scala
final def customAuthProviding[R0, Context: Tag](
    provide: Headers => Option[Context],
): RequestHandlerMiddleware.WithOut[
```

But it has the same issue (reversed) where a 401 is never returned and a 404 is always returned, also we need a way to deal with the empty Handler:
```scala
provide(request.headers) match {
  case Some(context) => handler.provideSomeEnvironment[R0](_.union[Context](ZEnvironment(context)))
  case None          => ???
}
```

And I was not able to fill the gaps here.

On the other hand, and I think that this is the most important part here, the current implementation of `CustomAuth` does not protect any endpoint as the verification is made AFTER making the actual execution of the call:

```scala
  private var mut = 0 // I know this is a bad idea, this is to illustrate the issue
  val priv        = Http.collect[Request] { case Method.GET -> !! / "api" / "private" =>
    mut += 1
    Response.text("private")
  }

  val auth   = RequestHandlerMiddlewares.customAuth { _ => false }
  val config = ZLayer.succeed(Server.Config.default.port(7070))
  val runner = Server.install(
    (priv @@ auth).withDefaultErrorResponse,
  )

  val serverFork = (runner *> ZIO.never).fork
  val client     =
    Client.request("http://localhost:7070/api/private") *> ZIO.succeed(assert(mut == 0))

  def run =
    serverFork.zipPar(client).provide(Client.default, Server.live, config)
```

The `mut` variable is modified even if the authentication is failing.
This is only the case because we are using an Http that does not involve ZIO (and is hence simplified before jumping into the ZIO runtime), if we were to change the `collect` to `collectZIO` we would not observer this behavior.

Sorry for this lengthy post without solution, here is a summary of related issues:
- when running CustomAuth with a non-zio HttpApp, the body is always executed, even if the authentication failed
- when running CustomAuth with a zio HttpApp, the body is not executed and the behavior seems correct
- when running CustomAuthProviding with a non-zio HttpApp, the returned error is always Unauthorized, even if the route does not exists
- when running CustomAuthProvidingwith a zio HttpApp the returned error is always Unauthorized, even if the route does not exists

**Comment by jdegoes** [comment]
The body should definitely not execute if the auth fails, and in addition, the behavior on ZIO vs non-ZIO should be the same.

/bounty $150

**Comment by ex0ns** [comment]
I think that we need to be really careful when changing this semantic, because those middleware are using the outcome of the function (returning Some or None) to return a response, this means that this middleware can only be used at the last position of a `++`, in other words, in the current state:

```scala
    ((priv @@ auth2) ++ Http.collectZIO[Request] { case req => ZIO.succeed(Response.text("ok"))})
```

will NEVER return `ok`.

The workaround I have, because all my protected routes share the same prefix, is to use the following construct (simplified to make it more readable):

```scala
  val prefix = !! / "api" / "private"
  val priv = Http.fromHttp[Request] { 
    case req @ _ -> `prefix` / _ =>
      Http.collect[Request] { case Method.GET -> `prefix` / "test" =>
        Response.text("private")
      } @@ auth2
    case _ => Http.empty
  }
```

I would be glad to integrate that into zio-http (will open a PR tonight) but I think that we can't really get past the addition of a `prefix` or something similar to only protect a subsets of the routes (and not becoming a catch-all or catch-nothing).

we already had this issue in the early days of zio-http and did a similar fix, because we HAVE to be able to make a difference between a Http.empty and an failed middleware

**Comment by ex0ns** [comment]
I have re-tested the original snippet on RC2 and this behave as expected (NotFound wih both auth and auth2). Thanks
