### ISSUE TITLE
Unable to handle errors from Http.fromFile

### ISSUE THREAD

**Issue by mniswander-ca** [zio/zio-http#2167]
**Describe the bug**
When using `Http.fromFile` or `Http.fromFileZIO` I could not find any way to handle errors from the Http app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an Http app using `fromFile` with a test file to serve. E.g.
```
object FileServer extends ZIOAppDefault:
  val app = Http
    .collectHttp[Request] { case Method.GET -> !! / "test.txt" =>
      Http
        .fromFile(File("src/main/resources/test.txt"))
    }
    .mapError { t =>
      // No errors ever appear here
      Response.text(t.toString)
    }

  val run =
    Server.serve(app.withDefaultErrorResponse).provide(Server.default)
```    
3. Disable read permissions on test file
4. Start the application 
5. Send a request the test endpoint
6. The server does not send back any response, instead it results in a netty crash.

**Expected behaviour**
Errors should be able to be caught and handled at the App level.

**Comment by 987Nabil** [comment]
@jdegoes I think I broke the reward system by opening a second PR. Can you fix this manually? 🤔
