### ISSUE TITLE
Replace !! with a plain word, or remove it completely if possible

### ISSUE THREAD

**Issue by swoogles** [zio/zio-http#2174]
**What is not easy to do right now?**
Define paths without a bizarre symbolic operator - `!!`

**Describe the solution you'd like**
Either go back to calling it `root`, or get rid of it entirely, if there's not some technical blocker for that.

**Why is it important?**
This is a needless source of confusion for people new to the library.

**Additional context**
It used to be called `root`, and that was fine!

**Comment by adamgfraser** [comment]
I will do this.

**Comment by adamgfraser** [comment]
Ah I see. If you try to use a plain word the compiler thinks you are trying to bind a new pattern variable.

**Comment by jgulotta** [comment]
You can start with a capital letter e.g. `Root`. Those are not treated as new pattern variables but as values to compare against, same as using backticks

**Comment by adamgfraser** [comment]
I like that!

**Comment by jgulotta** [comment]
Similarly, maybe `~~` should be renamed to `Empty` as well?

**Comment by adamgfraser** [comment]
I was thinking the same thing!

**Comment by adamgfraser** [comment]
That one does run slightly more risk of name clashes with other data types with an `Empty` case.

**Comment by swoogles** [comment]
Heck, `EmptyPath` or any verbose alternative is still a legibility improvement over `~~`

**Comment by jgulotta** [comment]
The name clashing is most probable when using wildcard imports (which I personally recommend against) but it's always possible to disambiguate via import rename or use `zio.http.Empty`directly, as that is also a stable identifier for the purposes of pattern matching

**Comment by 987Nabil** [comment]
I think wild card imports are quite common in the ZIO community. I like `EmptyPath` or I'd also be fine with `Path.Root` and `Path.Empty`
