### ISSUE TITLE
ZIO HTTP CLI: Add comprehensive test case and fix bugs

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2191]
For every possible endpoint combination including method (GET, PUT, POST, DELETE), including query parameters of different types, and headers of different types, and body content of different types, we need a test to verify that the correct CLI representation is generated.

This implies a very comprehensive test suite, which will no doubt uncover bugs that have to be fixed.

**Comment by pablf** [comment]
I would like to /attempt #2191 if none is working on it.

**Comment by feliciien** [comment]
Hello we can work together if you want my discord  youknowsthevibes send me
a text message
