### ISSUE TITLE
Improve multipart vs alternation API of `Endpoint`

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2195]
## Current situation
After implementing multipart form-data support for `Endpoint` #2140 / #2158, all variants of out have a mandatory field `name` (except the one without any params) which makes 100% sense for multipart, but the methods are actually all alternating the codecs. For example

```scala
  def out[Output2: Schema](
    name: String,
    status: Status,
    mediaType: MediaType,
  )(implicit alt: Alternator[Output, Output2]): Endpoint[Input, Err, alt.Out, Middleware] =
    Endpoint(
      input,
      output =
        (self.output | HttpCodec.content(name, mediaType)(implicitly[Schema[Output2]])) ++ StatusCodec.status(status),
      error,
      doc,
      mw,
    )
```

This method, having a media type and a name, seems to make only sense in the context of multipart. But the codec is added as an alternation. In fact all `out` methods are alternating. So I think you can not use them to create multipart outs at all.

## Idea

I think the `out` methods should only handle alternation. And there should be a specific method for multipart codec that takes var args. Why? Because currently, the order of the methods called on an Endpoint object does not matter. It results always in the same endpoint. If we would use a version of out that creates only a single `Http.Content` at a time, but uses `++` instead of `|` to add the codec, the order of the calls will change the resulting Endpoint and it will be harder to reason about it

I suggest something that looks like this when using it.

```scala
Endpoint.get(...).outMultipart(Status.Ok)(
	multipart[Int]("age", myMediaType),
	multipart[String]("username", myOtherMediaPart)
)
```

This offers

- a clear api that lets the user know what he creates
- keeps the guarantee, that the order of the build steps does not influence the resulting Endpoint
- removes the mandatory name from the alternation outs
- gives the bundle of multipart data exactly one status code

## Alternative

No alternation for `out`. Calling int multiple times means multipart. In this case we still need methods without name. But how could I model an API that return 200 with content and 204 without. Or another content for 201?
In that case status would also not make any sense btw. Because you can not change the status for different parts of the multipart answer, can you?

RFC @jdegoes @vigoo

**Comment by jdegoes** [comment]
I think `out` can always do alternation, like you suggest. This implies that we remove the `name` variants, because they are not useful. The optional media type can still be useful in the future (e.g. if you specify XML, then we would not support JSON encoding/decoding, only XML).

Then I think we can have `HttpCodec.multipart(part[Int]("age", myMediaType))`

where:

```scala
final case class MultipartBuilder[...](...) {
  def part(...): MultipartBuilder[...](...) = ...
  def partStream(...): MultipartBuilder[...](...) = ...
}
object MultipartBuilder {
  def empty = ...
  def part[A: Schema](name: String, mediaType: MediaType): MultipartBuilder[...] = ...
  def partStream[A: Schema](name: String, mediaType: MediaType): MultipartBuilder[...] = ...
}

object HttpCodec {
  def multipart[...](builder: MultipartBuilder[...]): ...
}
```

So in the end, the API for multipart would be something like:

```scala
endpoint.out(HttpCodec.multipart(
  partStream[Byte]("image", MediaType.Png)
    .part[String]("name")))
```

Although we could have a shortcut for that:

```scala
endpoint.outMultipart(
  partStream[Byte]("image", MediaType.Png)
    .part[String]("name"))
```

Thoughts?

**Comment by vigoo** [comment]
I've just realized that originally I wanted to add an `outMultipart` to keep the `out`s behaving as alternations, but then realized that there is no need (but of course the API could be improved).

To do multipart output, you can today write this:

```scala
endpoint.outCodec(
  HttpCodec.contentStream("image/png", MediaType.image.png) ++
  HttpCodec.content[String]("title") ++
  HttpCodec.content[Int]("width") ++
  HttpCodec.content[Int]("height") ++
  HttpCodec.content[ImageMetadata]("metadata"),
)
```

**Comment by jdegoes** [comment]
@vigoo Yes, I think that's pretty much what we need.

So maybe we have less work to do here, we just remove names from the `out` variants and direct multi-part use cases to `outCodec`.

**Comment by 987Nabil** [comment]
I like that too. 👍 Should that be done before the next RC? Else we would change the API and then back again.

**Comment by jdegoes** [comment]
Yes, before the next RC.

/bounty $25
