### ISSUE TITLE
`doc` string interpolation for `Endpoint` documentation

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2202]
This would be purely to support syntax highlighting for the interpolator in IntelliJ.
There are some pre configured. I guess we could open a PR in the IntelliJ to support this.

**Comment by rishi-raj-jain** [comment]
/attempt #2202

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clkl5kmcu000el30fp7d0gaav/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ayusham001** [comment]
/attempt #2202


<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clkl5kmcu000el30fp7d0gaav/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by rishi-raj-jain** [comment]
Can someone guide me to where is the Endpoint documentation!?

Is it https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/endpoint/Endpoint.scala?

**Comment by pranjalg13** [comment]
/attempt #2202

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clkl5kmcu000el30fp7d0gaav/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
