### ISSUE TITLE
Improve test coverage for `Endpoint`

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2204]
The current test coverage of the `Endpoint` API is not very high. A lot of the overloaded methods are not used in any test.
This means as well, that some use cases the API is build for are fragile, in the sense that it might break while implementing new features. (see #2195)

Even now, the `EndpointSpec`is already quite big. Maybe we can split it into multiple files based on use case and just aggregate the specs in `EndpointSpec`.

**Comment by danieletorelli** [comment]
Hello, I'm on it :)

**Comment by ghost** [comment]
/attempt #2204

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clkl5jdub0012l60fhn5be9le/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
