### ISSUE TITLE
Client proxy mTLS support

### ISSUE THREAD

**Issue by danestig** [zio/zio-http#2211]
I need to send HTTP traffic though a proxy that requires mutual TLS authentication. There currently is no way to provide the required certificates to the client to do this.

**Comment by rajcspsg** [comment]
Hi @adamgfraser 

This would be the approach that I would follow for this issue

1. create new SslConfig for client.
2. create a new field in ZClient for proxy SSLConfig.
3. copy the proxySSL config into `createChannel` function in NettyConnectionPool

Does it seem correct approach to proceed?

**Comment by adamseres** [comment]
Hi,

Thanks for working on this issue, I also need this feature to use zio-http.

I think that the ClientAuth is not what we need. I've never used it, but as far as understand, ClientAuth is used to configure the server connection to indicate the server's SSL requirement from the client.
https://netty.io/4.1/api/io/netty/handler/ssl/ClientAuth.html

Mutual TLS requires a keyManager in addition to the already implemented trustManager.
keyManager function has several implementations, I think it makes sense to support the same as for trustManager.

### certFile

    val keyCertChainInputStream: InputStream = ???
    val keyInputStream: InputStream = ???
    val keyPassword: String = ???

    SslContextBuilder
      .forClient()
      .trustManager(new File(serverCertPath))
      .keyManager(keyCertChainInputStream, keyInputStream, keyPassword)
      .build()


### keystore

    val keystoreInput: InputStream = ???
    val keyPassword: String = ???
    val keystore: KeyStore = KeyStore.getInstance(KeyStore.getDefaultType)
    val keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm)

    keystore.load(keystoreInput, keyPassword.toCharArray)
    keyManagerFactory.init(keystore, keyPassword.toCharArray)

    SslContextBuilder
      .forClient()
      .trustManager(new File(serverCertPath))
      .keyManager(keyManagerFactory)
      .build()

**Comment by rajcspsg** [comment]
Thanks @adamseres .
I'll update my PR with new implementation shortly.
