### ISSUE TITLE
Provide `Request` as part of Environment

### ISSUE THREAD

**Issue by domdorn** [zio/zio-http#2214]
I'd like to be able to access the `Request` through the Environment, e.g. like

```scala
import zio.{ZIO, ZIOAppDefault}


import zio.http._

object FormHandler extends ZIOAppDefault {

  val app = Http.collectZIO[Request] {
        case Method.GET -> !! / "text" =>
          for {
            req <- ZIO.service[Request]
            _ <- ZIO.debug(req)
          } yield Response.text("done")


    case Method.POST -> !! / "form" =>
      for {
        req <- ZIO.service[Request]
        _ <- ZIO.debug(req)
      } yield Response.text("done")

  }

  val run = Server.serve(app.withDefaultErrorResponse).provide(Server.default).exitCode
}
```

imho, this would be way more straightforward, meaning this was the way I tried to do it without looking through the docs.

**Comment by vigoo** [comment]
`collectZIO`s parameter is a partial function from `Request` to `Response` so you always have the access as the partial function's parameter. Having it in the environment as well seems redundant to me

**Comment by domdorn** [comment]
does it hurt to have it in the environment as well? It would allow me to express my actions/controllers as 

```
val someAction: ZIO[Request, SomeErrorType, Response]
```

**Comment by jdegoes** [comment]
This has performance implications that we can't easily solve. I do like the idea of it, but it would have to wait for a later version of ZIO HTTP (and ZIO, e.g. ZIO 2.2).
