### ISSUE TITLE
`Request` is missing `hasFormMultipartContentType`

### ISSUE THREAD

**Issue by domdorn** [zio/zio-http#2215]
a `Request` already has a `hasFormUrlencodedContentType` helper method, 
but is missing a `hasFormMultipartContentType` to do a proper check before calling `req.body.asMultipartForm`

**Comment by domdorn** [comment]
@abcpro1 did you check your code with a real request? cause a real request does not simply use the content-type, it also includes a boundary parameter in the content-type that marks how body parts are separated, so a strict `stringA == stringB` comparison does not work, it rather has to be something like `actualContentType.startsWith(...)` check.
See this for further info:
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by abcpro1** [comment]
nope, didn't. I'll check and come back.
