### ISSUE TITLE
URL.decode on a URL without a path or ending slash fails to "get"

### ISSUE THREAD

**Issue by aappddeevv** [zio/zio-http#2238]
**Describe the bug**
URL.decode does not produce a valid zio URL representation.

**To Reproduce**
```
val url = URL.decode("https://blah.com?m=1&k=4")
```
Results in a bad request being sent to the server e.g. `client.request(url)`.

However, `URL.decode(..).withPath("/")` then works.

**Expected behaviour**
A valid URL even if the URL string does not have a trailing slash in the string url.

**Screenshots**
NA

**Comment by Vivek7038** [comment]
can you suggest me the fix i should do , i can instatly fix . what should be the url?
just want some clarity on these

**Comment by vigoo** [comment]
Seems like `java.net.URI`'s parser which this relies on cannot parse this properly - it treats everything after the scheme as the authority. So if we want to fix this we need to write our own URL parser.

**Comment by de-laz** [comment]
@vigoo @aappddeevv  I don't really have enough context on this issue but shouldn't the given example be `val url = URL.decode("https://blah.com?m=1&k=4")` instead of `val url = URL.decode("https://blah.com&m=1&k=4")`? The domain and parameters are separated by an "&" instead of "?", not sure if that's important.

**Comment by aappddeevv** [comment]
Good catch. The query parameters follow a '?' per the http spec so my example that I typed in by hand may have been mistyped or the machine generated URL from a commercial server (not mine) that was being used was bad...let me check.

**Comment by aappddeevv** [comment]
Typo in my example on my part...fixed the text above.

Maybe the issue is that the rendering of the URL in the the layer that translates it to the execution engine (e.g. netty) does not handle `Path.empty` correctly.

**Comment by aappddeevv** [comment]
I'm concerned that there may be other factors that affected the issue I had and the resolution, this small scala-cli program seems to give the error I would expect given that the query params are invalid, but it shows that the call goes out as expected although it does not work if I use https but that seems to be another matter.

```scala
//> using dep dev.zio::zio-http:3.0.0-RC2
//> using scala 3.3.0

import zio.*
import zio.http.*

val program = for {
  res <- Client.request("http://www.google.com?blah=hah&hah=blah")
  data <- res.body.asString
  _ <- Console.printLine(data)
} yield ()

object Main extends ZIOAppDefault:
  def run =
    program
      .provide(
        Client.default,
      )
```

**Comment by vigoo** [comment]
@de-laz good catch :) with the fixed string decoding/encoding this works:
```scala
          val url = "https://blah.com?m=1&k=4"
          assertTrue(URL.decode(url).map(_.encode) == Right(url))
```

The above example sends the expected HTTP request to google.
![image](https://github.com/zio/zio-http/assets/2292489/1a511380-1da2-48ad-898d-dafc1d78103f)

and it responds with a 404 with some HTML body.

The URL is good with https too.
First when testing with https it seemed like I always get a `io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException` but sometimes it worked. Digging into this, I noticed that it depends on which host the `DnsResolver` picks.

If I always pick the first one it always works with both http and https (the scheme has nothing to do with the dns resolving phase of course). If I pick the last one which is an IPv6 address, it fails. 

Is this the same error you got? 
Maybe we should filter IPv6 addresses in the DNS resolver?
