### ISSUE TITLE
Unexpected behavior of `Client.get` 

### ISSUE THREAD

**Issue by ex0ns** [zio/zio-http#2268]
**Describe the bug**

When using the `get` or `post` method available in the companion object of `Client` it is (as far as I know) not possible to make a query using the `Client.default` layer.
Indeed, the URL is assigned to URL.empty in https://github.com/zio/zio-http/blob/480cd69f1f95035b1a7397308f41875d0112aac3/zio-http/src/main/scala/zio/http/ZClient.scala#L571 and it's not possible, without using the `request` method to set it to another value.

**To Reproduce**

```scala
//> using scala "2.13"
//> using lib "dev.zio::zio-http:3.0.0-RC2"

import zio._
import zio.http._

object Repro extends ZIOAppDefault {

  override def run =
    Client
      .get("/index.html")
      .orElse(Client.get("http://localhost:8080/index.html"))
      .debug
      .provide(Client.default)

}
```

This fails with 
```
AIL> Die(java.lang.IllegalArgumentException: Absolute URL is required,Stack trace for thread "zio-fiber-4":
        at <empty>.Repro.run(Repro.scala:57)
        at <empty>.Repro.run(Repro.scala:58)
        at <empty>.Repro.run(Repro.scala:59)
        at <empty>.Repro.run(Repro.scala:60))
timestamp=2023-06-17T10:10:40.979494216Z level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" java.lang.IllegalArgumentException: Absolute URL is required
        at zio.http.ZClient$ClientLive.$anonfun$requestAsync$29(ZClient.scala:697)
        at zio.ZIO$.$anonfun$fail$1(ZIO.scala:3146)
        at zio.ZIO$.$anonfun$failCause$3(ZIO.scala:3155)
        at <empty>.Repro.run(Repro.scala:57)
        at <empty>.Repro.run(Repro.scala:58)
        at <empty>.Repro.run(Repro.scala:59)
        at <empty>.Repro.run(Repro.scala:
```        
        
**Expected behaviour**

The client should make a request when using `get` or `post` accessor.
I could not find any usage of `Client.get` or `Client.post` in the zio-http codebase, and I hence think that those method should be refactored because it's pretty confusing right now. However I think we could push that even further, what is the reason of having `URL` stored inside a ZClient ?

**Comment by vigoo** [comment]
@ex0ns is this still valid after @jdegoes 's refactor?

**Comment by ex0ns** [comment]
I don't think it does because the accessors for get and post have been remove and only `ZClient.request` remains, so that should not be an issue anymore.
