### ISSUE TITLE
Automatic and overridable handling of `zio-schema` `ValidationError`s

### ISSUE THREAD

**Issue by williamareynolds** [zio/zio-http#2274]
**Is your feature request related to a problem? Please describe.**

`zio-schema` offers a [`validate` annotation](https://github.com/zio/zio-schema/blob/main/zio-schema/shared/src/main/scala/zio/schema/annotation/validate.scala), which takes a [`Validation` ](https://github.com/zio/zio-schema/blob/main/zio-schema/shared/src/main/scala/zio/schema/validation/Validation.scala). There is a method, [`Schema#validate[A](value: A)`](https://github.com/zio/zio-schema/blob/main/zio-schema/shared/src/main/scala/zio/schema/Schema.scala#L150), which executes the validators and returns a chunk of [`ValidationError`](https://github.com/zio/zio-schema/blob/main/zio-schema/shared/src/main/scala/zio/schema/validation/ValidationErrors.scala). 

Currently, `zio-http` does not execute these validations. Moreover, failure to decode a body results in an empty 400-status response. The errors aren't catchable as failures or defects in the implement method or on the route, and they become indiscernible at the app level (empty response with 400 status). As such, third party callers get no feedback as to how their requests aren't valid.   

**Describe the solution you'd like**

I think the ideal behavior is as follows:
  * Schema validations are executed by default or using an argument to `Endpoint#in`
  * The status code of failures due to decoding or validation are controllable by `Endpoint#outError` or `Endpoint#outErrors` methods
  *  The errors of validation and decoding are catchable at some point when writing an endpoint implementation, either via handling on Route or within the `Endpoint#implement` method callback
  *  HttpCodecErrors can generally be rewritten to other structures by the implementer

**Describe alternatives you've considered**

I think this is just a young feature set in this library at this point, and so it's not surprising that these capabilities aren't available. One thing I certainly have considered is that `zio-schema`'s errors could be given their own schemata such that they could be returned directly by the Endpoint API rather than casting to an `HttpCodecError`. I think this is either very challenging or demands changes to how `ValidationError` is written to support serialization, I'm not sure.

I suppose it's also possible that the intended use of the Endpoint API is for localized microservice interaction, and that exposing this to a third-party isn't desirable. I think this would heavily limit the usability of this API though, and I certainly envisioned it as a sort of `Servant`/`Tapir`-like API descriptor for providing cross-service type-safety, and allowing me to provide a generated client to third-party consumers.

**Additional context**

Ideally, I'd be able to do something like this:

```scala
case class Person(
  @validate(Validation.minLength(2))
  name: String
  @validate(Validation.greaterThan[Int](18))
  age: Int
) derives Schema

case class CustomError(
  messages: Chunk[String]
) derives Schema

val endpoint1 = Endpoint
  .post(literal("person")
  .in[Person](validate = true)
  .out[Unit](Status.NoContent)
  .outErrors(
    // Should MalformedBody be differentiated from UnprocessableEntity?
    HttpCodec.error[HttpCodecError.InvalidBody](Status.UnprocessableEntity) ,
    HttpCodec.error[CustomError](Status.UnprocessableEntity),
  )

val route1 = endpoint1.implement { person =>
    person.mapError {
      case e: HttpCodecError.MalformedBody => 
        CustomError(Chunk(e.details, e.cause.map(_.getMessage).getOrElse("")))
    }.unit
  }

// ------- OR --------

val route2 = endpoint1.implement { _ => ZIO.unit }.mapError {
      case e: HttpCodecError.MalformedBody => 
        CustomError(Chunk(e.details, e.cause.map(_.getMessage).getOrElse("")))
  }
```

**Comment by williamareynolds** [comment]
I'm already looking into this issue, and I'll try to put up a PR with some draft solutions soon.

**Comment by jdegoes** [comment]
/bounty $250 

To add auto-validation (if present on the original `zio.schema.Schema`) and conversion to `HttpCodecError`, with test cases.

**Comment by williamareynolds** [comment]
/attempt #2274

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clkl5eu3l0002l60fgr74s3qs/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
