### ISSUE TITLE
`Response.fromSocketApp` erases headers.

### ISSUE THREAD

**Issue by fomkin** [zio/zio-http#2278]
I tried to use WebSocket subprotocols, but they don't work. The idea of subprotocols to take list of protocols sent by client in `sec-websocket-protocol` header, chose one, and send it back with same header. Receiving protocol from client is OK, but sending back is trouble, because looks like `Response.fromSocketApp` erases the header.

See:
1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism
2. https://datatracker.ietf.org/doc/html/rfc6455

**Comment by vigoo** [comment]
@fomkin the handshake including the subprotocol selection is implemented by Netty (see https://netty.io/4.0/api/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandler.html)

You can configure this handler including the subprotocols using the `WebSocketConfig` part of the server config:
https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/WebSocketConfig.scala#L24

Could you tell more about what is not working, maybe provide a reproducer?

**Comment by fomkin** [comment]
Looks like it should solve problem in my case, but what if acceptance of the protocol is decision of request handler?
