### ISSUE TITLE
RequestHandlerMiddlewares.metrics misbehave when two apps combine

### ISSUE THREAD

**Issue by mhodovaniuk** [zio/zio-http#2294]
**Describe the bug**
When we `++` two `Http` with `@@ RequestHandlerMiddlewares.metrics` there is an issue that if a handler sits in the second `Http`, the middleware from the first `Http` still reports the route with 404 status [here](https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/internal/middlewares/Metrics.scala#L117).

**To Reproduce**
[Unit test](https://github.com/zio/zio-http/compare/main...mhodovaniuk:zio-http:main):
1. `http_requests_total with two path label mappers` - fails, but it should not
2. `http_requests_total with two path label mappers reverse order` - passes.

**Comment by jdegoes** [comment]
This is now impossible in the new design, so fixed.
