### ISSUE TITLE
Logger doesn't propagate to Http (again)

### ISSUE THREAD

**Issue by heaven-born** [zio/zio-http#2303]
Looks like [this issue](https://github.com/zio/zio-http/issues/1352) is back in `3.0.0-RC2`

The steps to reproduce are the same as for the original issue.

ZIO-HTTP Version  3.0.0-RC2
ZIO Version: 2.0.15
Scala Version: 3.3.0

**Comment by vigoo** [comment]
I don't think there is any issue - see https://github.com/zio/zio-http/issues/2016 for explanation

Please reopen if you have a reproducer
