### ISSUE TITLE
QueryCodec::optional should not recover from validation errors

### ISSUE THREAD

**Issue by senia-psm** [zio/zio-http#2311]
`queryCodec.optional` succeeds not only on absent query parameter, but also on any validation errors produced by `transformOrFailLeft`.

```scala
  val a: QueryCodec[String] = query("a").transformOrFailLeft[String](s => Left("error"), x => x)

  val test: Endpoint[Option[String], Nothing, String, EndpointMiddleware.None] =
    Endpoint
      .get("test")
      .query(a.optional)
      .out[String]
```

See minimal reproducer here: https://github.com/senia-psm/zio-http-2311

**Expected behaviour**
Endpoint `test` should fail if query parameter `a` is provided.

**Actual behaviour**
Endpoint `test`  never fails.

`zio-http` version - `3.0.0-RC2`
`scala` version - `3.3.0`

**Comment by senia-psm** [comment]
It would be nice to have a method like this `def recover(f: HttpCodecError => Either[String, T])`

**Comment by reminia** [comment]
/attempt #2311 can I have a try on this issue?

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clkl4r1sk0002l20f1yeqz747/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by reminia** [comment]
Looks like it's expected behavior from the code. No matter whether transformation on the arg is Left or Right, since it's optional, the transformation result doesn't matter.  @jdegoes  can u help verify whether it's by desgin?

https://github.com/zio/zio-http/blob/4123b171724add70d5c75afbd2ef13385291d362/zio-http/src/main/scala/zio/http/codec/HttpCodec.scala#L276

**Comment by adamgfraser** [comment]
@reminia `optional` should only recover in cases where the value does not exist, not in cases where the value exists but just could not be properly parsed.

**Comment by reminia** [comment]
@adamgfraser per my understanding, if this is the case, the user should write something like `query("a").optional. transformOrFailLeft` but not swapping the two, as optional at the last means arg is not important from the design of the endpoint, why not just give out the correct response?

**Comment by adamgfraser** [comment]
@reminia Because it is the wrong semantics of `optional`. `optional` says "this value may or may not be there, if it's not that's fine". But it results in extremely confusing behavior if the client calls the server providing this information but mistakenly encodes it incorrectly and then the server just says `None` instead of failing with the parsing error.

`optional` should only recover from cases where the value is not provided at all and not any other error. You may be able to work around it by using other operators but that should not be necessary.

**Comment by reminia** [comment]
@adamgfraser 
Plan to implement the optional as below with a assumption that If a transform exists before optional, that means the parameter must exist 

Consider a case:
1. query by:` query("a").transform[String](value => value)(value => value).optional`
2. request without a 

Should it be failed or successful?  I think it should be failed.

```scala
// the original optional
private final def _optional: HttpCodec[AtomTypes, Option[Value]] =
    Annotated(
      self
        .orElseEither(HttpCodec.empty)
        .transform(_.swap.toOption)(_.fold[Either[Unit, Value]](Left(()))(Right(_)).swap),
      Metadata.Optional(),
    )

  final def optional: HttpCodec[AtomTypes, Option[Value]] = {
    self match {
      case _: Atom[_, _] => self._optional
      case _             => self.transform[Option[Value]](value => Option(value))(option => option.get)
    }
  }
```

**Comment by senia-psm** [comment]
@reminia 
This one should succeed without `a` and with `a`: `query("a").transform[String](value => value)(value => value).optional`
This one should succeed without `a`, but fail with `a`: `query("a").transform[String](value => ???)(value => ???).optional`

**Comment by reminia** [comment]
@senia-psm  for case #1, for me it's a conflict at the logic as false encoding is also a case of correct encoding. Why correct encoding can tolerate a parameter doesn't exist but a false encoding cannot? 
for case #2, not understand, what is ???.

**Comment by senia-psm** [comment]
@reminia `Predef.???`

on 1: we need to know the reason why it is invalid and recover from 1 of the reasons on `optional`.

**Comment by adamgfraser** [comment]
@reminia I think the example of `query("a").transform[String](identity)(identity).optional` should definitely succeed regardless of whether the value is present and shows that the "parameter must exist if there is a transform before the optional" approach is not sound. Will take a look at this issue.
