### ISSUE TITLE
The ability to send WebSocket messages in batches

### ISSUE THREAD

**Issue by szlepermarcin** [zio/zio-http#2314]
From version `3.0.0-RC2`, the WebSocket protocol handling API has changed (overall, the change has been very positive). 
This change resulted in the loss of the ability to send multiple messages and flush them all at once. 
In the previous versions (`0.0.4` and `0.0.5`), it was possible to optimize sending in this way 
```scala
  val channel: Channel[WebSocketFrame] = ???
  def send(messages: Chunk[WebSocketFrame]) = messages match {
    case ch if ch.isEmpty => ZIO.unit
    case ch =>
      ZIO.foreachDiscard(ch.init)(m => channel.write(m)) *> channel.writeAndFlush(chunk.last, await = true)
  }
```
In my use case, this optimization led to even a few percent increase in performance,  so my question is: would it be possible to add a feature that somehow enables way for such optimization in next versions?

**Comment by adamgfraser** [comment]
Will take a look at this.

**Comment by szlepermarcin** [comment]
One more important thing regarding the example above - the `await = true` flag set when the last message was sent is a protection in case that the WS client is slow or does not read the messages at all, without this protection we can have nasty effect of a heap or direct buffer memory "leak"
