### ISSUE TITLE
Convert metrics from HandlerAspect to Middleware

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2320]
Currently `metrics` is a `HandlerAspect` that performs metrics computation.

This is not ideal, because a `HandlerAspect` does not have access to a `RoutePattern`. So instead, it takes a sort of "normalize" or "canonicalize" function:

```scala
pathLabelMapper: PartialFunction[Request, String] = Map.empty,
```

This "path label mapper" is intended to turn a request into a path label.

However, if implemented as a `Middleware`, then we have explicit access to the `RoutePattern`, which we can render in a string such as `/users/{user-id}`, and we do not have to have any concept of path label mapper.

This ticket is to refactor metrics from HandlerAspect into Middleware and to take advantage of the `RoutePattern` that the middleware will then have access to.

**Comment by lookingformira** [comment]
mr https://github.com/zio/zio-http/pull/2334
