### ISSUE TITLE
Bounded body consumer

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#2372]
**Is your feature request related to a problem? Please describe.**

My initial naive approach was to use `Handler.fromZIO(request.body.asString)` to decode inputs, however as the docs state
> Note that attempting to decode a large stream of bytes into a string could result in an out of memory error.

**Describe the solution you'd like**

I would love a **safe** version of this that limits the maximum allowed size.

`Handler.fromZIO(request.body.asStringBounded(4098))`

**Describe alternatives you've considered**

For now I am doing this:
```scala
Handler.fromZIO(
  request.body.asStream
    .runFoldZIO(Chunk.empty[Byte]) { case (acc, byte) =>
      if (acc.size >= 4098) ZIO.fail(new Exception("Too large input"))
      else ZIO.succeed(acc.appended(byte))
    }
    .map(_.map(_.toChar).mkString)
)
```

**Comment by guersam** [comment]
I'm not sure if it deserves a dedicated method yet, but I'd suggest using chunks instead of raw bytes for better performance:

```scala
Handler.fromZIO(
  request.body.asStream
    .chunks
    .runFoldZIO(Chunk.empty[Byte])((acc, bytes) =>
      ZIO.succeed(acc ++ bytes)
        .filterOrFail(_.sizeIs < 4098)(new Exception("Too large input"))
    )
    .map(_.asString)
)
```

If it will be a built-in feature, it would be better if the server can return a `413 Request Entity Too Large` response automatically.
