### ISSUE TITLE
WebSocketConfig.withForwardCloseFrames does not forward Close frames

### ISSUE THREAD

**Issue by webberaj81** [zio/zio-http#2375]
**Describe the bug**
When creating a WebSocketConfig with `withForwardCloseFrames(true)`, Close frames are not forwarded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a SocketApp with a Handler that maps `Read(WebSocketFrame.Close)` to some observable behavior, e.g., `Console.printLine`
2. Provide this SocketApp a ZClient configured with a WebSocketConfig using withForwardCloseFrames(true)
3. Connect this client to a Server serving a SocketApp.
5. Have this Server send a Close frame to the client
6. Notice that the client does not invoke the behavior mapped to the `Read(WebSocketFrame.Close)` event

**Expected behaviour**
Methods have functionality consistent with their naming 

**Additional context**
`WebSocketConfig.withForwardCloseFrames(false)` does forward the Close frames to the client, which is contradictory to it's name, and to the behavior of its sibling method, `WebSocketConfig.withForwardPongFrames`, which requires `true` to be made visible to the Client/Server

To put this another (more readable) way, this is what the WebSocketClient from the example code would need to be to see Close frames and Pong frames, both of which are not available by default:
```scala
  val run: ZIO[Scope, Throwable, Any] =
    ZIO.scoped {
      app.provideSome[Scope](
        ZLayer.succeed(
          Client.Config.default.withWebSocketConfig(
            WebSocketConfig
            .default
            .withForwardCloseFrames(false) // <- FALSE To see them
            .withForwardPongFrames(true), // <- TRUE To see them
          ),
        ) ++ ZLayer.succeed(NettyConfig.default)
          ++ DnsResolver.default >>> Client.live
        )
    }
}
```

**Comment by webberaj81** [comment]
/attempt #2375

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllewwyxv000emk0f615oleg7/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Syed-Taha381** [comment]
val run: ZIO[Scope, Throwable, Any] =
  ZIO.scoped {
    app.provideSome[Scope](
      ZLayer.succeed(
        Client.Config.default.withWebSocketConfig(
          WebSocketConfig
            .default
            .withForwardCloseFrames(false) // Set to true to forward Close frames initiated by server
            .withForwardPongFrames(true),
        ),
      ) ++ ZLayer.succeed(NettyConfig.default)
        ++ DnsResolver.default >>> Client.live
    )
  }
}

Try that

**Comment by an0nym3sh** [comment]
/attempt #2375

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllewwyxv000emk0f615oleg7/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
