### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by sxh-lsc** [zio/zio-http#2377]
I can see some issues have discussed this question,but I still face with this problem,how can I fix it? I use the newest version "dev.zio" %% "zio-http" % "3.0.0-RC2"

**Comment by sxh-lsc** [comment]
solve by 
`    val config = Server.Config.default
      .port(8081)
      .copy(requestStreaming = RequestStreaming.Enabled)`

**Comment by ujjaldey** [comment]
> solve by ` val config = Server.Config.default .port(8081) .copy(requestStreaming = RequestStreaming.Enabled)`

Thanks. It resolved my issue.
