### ISSUE TITLE
IntCodec cannot take negative values

### ISSUE THREAD

**Issue by Ellzord** [zio/zio-http#2378]
**Describe the bug**
it's not possible to have negative int query params.

```scala
  case object IntCodec extends TextCodec[Int] {
    def apply(value: String): Int = Integer.parseInt(value)

    def describe: String = "an integer"

    def encode(value: Int): String = value.toString

    def isDefinedAt(value: String): Boolean = {
      var i = 0
      var defined = true
      while (i < value.length) {
        if (!value.charAt(i).isDigit) {
          defined = false
          i = value.length
        }
        i += 1
      }
      defined && i >= 1
    }

    override def toString(): String = "TextCodec.int"
  }
```

Due to the code above and that `TextCodec` is a sealed trait it's not possible to take a negative integer value as a query param. You also aren't able to create your own. The only workaround is to have as a string and parse yourself - this means that if you tried to generate any documentation in the future it would be wrongly typed.

This is quite an opinionated approach, what if -100 was to go back 100 items for example.

**Comment by jdegoes** [comment]
/bounty $100 

We can allow parsing of negative values. Since they are, after all, ints.

**Comment by yashug** [comment]
@jdegoes can this condition inside while loop solves our problem ?

```!value.charAt(i).isDigit && (i == 0 && value.charAt(i) != '-')```

**Comment by danieletorelli** [comment]
/attempt #2378

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllewwbkd0002mk0ffotbtw3e/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by davidtboc** [comment]
/attempt #2378 - I think isDefinedAt needs to be modified to account for a potential minus sign at the beginning of the string.


</p>
</details> 

def isDefinedAt(value: String): Boolean = {
  if (value.isEmpty) return false

  var i = 0
  if (value.charAt(0) == '-') {
    if (value.length == 1) return false // just a minus sign without digits
    i = 1
  }

  var defined = true
  while (i < value.length) {
    if (!value.charAt(i).isDigit) {
      defined = false
      i = value.length
    }
    i += 1
  }
  defined
}



<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllewwbkd0002mk0ffotbtw3e/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
