### ISSUE TITLE
Smart content-type response headers for static files

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-http#238]
When serving static files, it would be nice if the `content-type` header was automatically filled for common file types (ex: `.js` files get `application/javascript`, etc). 

http4s does this here: 
https://github.com/http4s/http4s/blob/main/core/src/main/scala/org/http4s/StaticFile.scala#L240
https://github.com/http4s/http4s/blob/main/core/src/main/scala/org/http4s/MimeDB.scala

When the content-type is not filled, browsers might refuse to load javascript files.

**Comment by ayakovlenko** [comment]
The links are broken. Stable links:

- [MimeDB.scala](https://github.com/http4s/http4s/blob/a17311508c0360080d9bea3bf0fbdc898efe4ad5/core/shared/src/main/scala/org/http4s/MimeDB.scala)
  - Generated by [MimeLoader.scala](https://github.com/http4s/http4s/blob/a17311508c0360080d9bea3bf0fbdc898efe4ad5/project/MimeLoader.scala) from [jshttp/mime-db](https://github.com/jshttp/mime-db)
- [StaticFile.scala](https://github.com/http4s/http4s/blob/a17311508c0360080d9bea3bf0fbdc898efe4ad5/core/jvm/src/main/scala/org/http4s/StaticFile.scala)

**Comment by kaushik143** [comment]
We currently serve static files by converting the file content into ZStream of content. Great if we have a middleware that can attach `content-type` header  smartly as  @ghostdogpr  mentioned

API suggestion
`app @@ smartContentType(url, headerValue)`

Spec
- Add middleware smartContentType
- Modfiy [FileStreaming](https://github.com/dream11/zio-http/blob/main/example/src/main/scala/FileStreaming.scala) example to showcase usage of smartContentType header

**Comment by olivierdeckers** [comment]
I'm interested in taking a stab at this.
How should this be implemented as a middleware? 
The middleware would need access to the file to parse the mimetype, which is not supported as far as I can tell.

Why don't we add a method on HttpApp instead that parses the mimetype and returns the file content as a ZStream?

**Comment by olivierdeckers** [comment]
I just realized we don't need to get the mime type from the file if we base ourselves on the file extension in the url.

Does this resemble what you had in mind? https://github.com/olivierdeckers/zio-http/commit/8abfa9274fd222c59e7c2bdde6bff18ed31c723a

**Comment by vigoo** [comment]
I think this is done (`Http.fromFile` etc are using `MimeDb` to set the content type)
