### ISSUE TITLE
Improve test coverage for Endpoint - Part 2

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2388]
Improve test coverage for Endpoint and clean up tests.

**Comment by ghost** [comment]
/attempt #2388

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllevk7cq000dl40fd3xjalw3/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Syed-Sheharyar** [comment]
## It's terrible that nobody with Bounty on GitHub supports Pakistan which has 3rd most freelancers, remote workers, and developers willing to work online and earn some in return.

**Comment by Nailer** [comment]
/attempt #2388

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllevk7cq000dl40fd3xjalw3/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
