### ISSUE TITLE
Client hangs when attempting reading response body out of Scope

### ISSUE THREAD

**Issue by myazinn** [zio/zio-http#2399]
**Describe the bug**
When HTTP client reads a response out of response Scope, it can't receive any new data from upstream due to a closed connection. However, the data stream itself is not closed and just waits for a new data, causing consumption to hang indefinitely.

**To Reproduce**
Steps to reproduce the behaviour:
1) Run simple HTTP server with infinite streaming response
```scala
package example

import zio.http._
import zio.stream.ZStream
import zio._

object StreamingResponse extends ZIOAppDefault {
  def run: Task[Nothing]        = Server.serve(app).provide(Server.default)
  private def app: HttpApp[Any] = Routes(
    Method.GET / "stream" ->
      handler(
        Response(
          status = Status.Ok,
          body = Body.fromStream {
            ZStream
              .iterate(1)(_ + 1)
              .tap { i =>
                ZIO.when(i % 10000 == 0)(ZIO.debug("sent 10k numbers"))
              }
              .map(_.toString)
          },
        ),
      ),
  ).toHttpApp
}

```
2) Run a client, that will read data from server
```scala
package example

import zio._
import zio.http._

import java.util.concurrent.atomic.AtomicInteger

object SimpleClient extends ZIOAppDefault {
  def run: RIO[Scope, Any]               = program.provideSome[Scope](Client.default)
  def program: RIO[Scope & Client, Unit] = for {
    client <- ZIO.service[Client]
    request = client.request(Request.get("http://localhost:8080/stream"))
   //    res <- request // this one works as expected. It consumes data and prints it to console infinitely
    res <- ZIO.scoped(request)
    counter = new AtomicInteger(0)
    _ <- res.body.asStream.runForeach { _ => // this line should've fail with an error, but it does nothing
      ZIO.when(counter.incrementAndGet() % 10000 == 0)(ZIO.debug("Received 10k bytes"))
    }
  } yield ()

}
```

**Expected behaviour**
Since I'm reading data out of scope, I'd expect stream to fail with any meaningful error. 

**Additional context**
I get that no one should ever do it. However, it might be a common mistake if a person doesn't know what Scope is doing in this particular case / is new to ZIO and doesn't know how to work with Scopes. Handing indefinitely is an unexpected result, _especially_ since it might actually work sometimes because all data was read into internal buffer before the Scope was closed, as shown [here](https://scastie.scala-lang.org/XDhkGSnwSiGzrKWNGV88pA).
UPD: I guess it is related to https://github.com/zio/zio-http/issues/2383 and https://github.com/zio/zio-http/issues/2297 and internally it's the same issue. However, it might help others to find their case, so maybe it worth keeping it open

**Comment by jdegoes** [comment]
/bounty $100 to not hang but to produce some sort of defect error.

**Comment by lackhoa** [comment]
/attempt #2399 Looks fun! I’ll try maybe for a day to do this.

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cllp83dth0002l50f01hpncpn/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by gaeljw** [comment]
For anyone coming here, I had a similar issue (client hanging forever) because I was indeed not using the `Scope` correctly. 

With zio-http 3.0.0-RC4.

```diff
val handler: Response => IO[E, A] = ???
val theResult = for {
    response <- client.request(request).mapError(ex => ...)
    result <- handle(response)
} yield result
-theResult.provide(Scope.default)
+ZIO.scoped(theResult)
```

(For some context, I don't know much about `Scope`, probably a silly mistake)
