### ISSUE TITLE
ignore does not exist

### ISSUE THREAD

**Issue by TomTriple** [zio/zio-http#2409]
**Describe the bug**
The docs in https://github.com/zio/zio-http/blob/main/docs/dsl/routes.md?plain=1#L141 propagate using `Routes#ignore`, which does not exist. 

**Expected behaviour**
We should add that operator or remove that paragraph from the docs

**Comment by vigoo** [comment]
It was renamed to `sandbox`:
https://github.com/zio/zio-http/blob/main/zio-http/src/main/scala/zio/http/Routes.scala#L85-L91

**Comment by TomTriple** [comment]
Ok, I updated my current PR to also refer to `sandbox` https://github.com/zio/zio-http/pull/2408/files#diff-71fbeea67d6b0353132589c242d8f9a02c8fa9fad3c1043853dbb3e7c690088f
