### ISSUE TITLE
Flaky ClientHttpsSpec Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-http#2479]
<img width="1890" alt="image" src="https://github.com/zio/zio-http/assets/20825463/ef3f68b2-5402-4a59-9fde-a191be96632d">

**Comment by Kartik1397** [comment]
I would like to give this a try because I enjoy troubleshooting/debugging.
/attempt #2479

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr2l8fd50004l90f13dmic8z/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by thekumbhaj** [comment]
I Believe able to fix it , wanna try once.
/attempt #2479 

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr2l8fd50004l90f13dmic8z/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Kartik1397** [comment]
Update:

Issues I found with ClientHttpsSpec.scala
- Certificate of https://sports.api.decathlon.com/groups/water-aerobics was expired on _Tuesday, 14 November 2023 at 12:37:59_ hence `test("respond Ok")` and  `test("respond Ok with sslConfig")` are failing, if I replace url with https://www.google.com they pass.
- I'm able to fix `test("should respond as Bad Request")` by replacing https://www.whatissslcertificate.com/google-has-made-the-list-of-untrusted-providers-of-digital-certificates/ with a test server url which always response with 400 Bad Request

**Comment by kyri-petrou** [comment]
/attempt #2479

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr2l8fd50004l90f13dmic8z/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
