### ISSUE TITLE
Type `Scheme` is too restrictive and the parser is wrong

### ISSUE THREAD

**Issue by FabioPinheiro** [zio/zio-http#2489]
**Describe the bug**
CORS middleware not working with `origin: chrome-extension://appid`

**To Reproduce**
Steps to reproduce the behaviour:
1. Make any request that call CORS middleware 'curl 'http://localhost:8080/' -v -X 'OPTIONS' -H 'access-control-request-method: POST'  -H 'origin: chrome-extension://appid''

**Expected behaviour**
To return `HTTP/1.1 204` instead of a `HTTP/1.1 404`

---

**Additional context**

The ZIO type `Scheme` is too restrictive...
It must support
`scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )`
[URI -> RFC from IETF](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1)
[URL -> RFC from IETF](https://datatracker.ietf.org/doc/html/rfc1738#section-2.1)

In ZIO:
```scala
scala> zio.http.Scheme.decode(new java.net.URI("chrome-extension://appid").getScheme)
val res1: Option[zio.http.Scheme] = None

zio.http.Header.Origin.parse("chrome-extension://appid")
val res2: scala.util.Either[String,zio.http.Header.Origin] = Left(Invalid Origin header
```
Because in `zio.http.Header.Origin` we have
`case Right(url) if url.host.isEmpty || url.scheme.isEmpty => Left("Invalid Origin header")`

Also this is clear a bug...

```scala
zio.http.Header.Origin.parse("abc://appid")
val res4: scala.util.Either[String,zio.http.Header.Origin] = Right(Value(wss,appid,None))
```

**Comment by FabioPinheiro** [comment]
The parsing is done by the string size for efficient I suppose
```scala
scheme.length match {
  case 5 => Scheme.HTTPS
  case 4 => Scheme.HTTP
  case 3 => Scheme.WSS
  case 2 => Scheme.WS
  case _ => null
}
```

**Comment by jdegoes** [comment]
/bounty $75

For fix and test case, but only if not already fixed.

**Comment by 987Nabil** [comment]
This is already fixed
