### ISSUE TITLE
Avoid printing secrets

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2508]
There a different places, where we use plain strings to keep credentials like passwords in memory. To avoid accidental printing to logs/console, we should use a dedicated data structure that will just print `***` when toString is called on it.

**Comment by 987Nabil** [comment]
Should use `zio.Config.Secret`

**Comment by jdegoes** [comment]
/bounty $75

To use `zio.Config.Secret` everywhere for passwords.

**Comment by 987Nabil** [comment]
/attempt #2508

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr2kkbc20014l40f2c98p2l5/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
