### ISSUE TITLE
rendering of script html template is broken

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2521]
For code like
```scala
script(s"""myCoolJsMethod("myStringInput")""")
```

rendering this will cause the quotes to be escaped. This is not the correct behaviour for script.
We might need to special case script, since I think it is the only tag for which the content should not be escaped.

**Comment by ezhil56x** [comment]
Hello @987Nabil 👋🏻
I'm interested to work on this 🙋🏻
I couldn't find [Contributor's guide](https://zio.dev/about/contributing) for this repo, link is broken on [README.md](https://github.com/zio/zio-http#readme)

**Comment by 987Nabil** [comment]
Hey @ezhil56x I think this is the right link
https://zio.dev/contributor-guidelines

Anyhow, just fork, clone and open a PR. I am sure you'll just be doing fine 🙂
