### ISSUE TITLE
SSL Spec broken

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2532]
The `ClientHttpsSpec` is broken, since the SSL certificate of `https://sports.api.decathlon.com/groups/water-aerobics` is not valid anymore.

We should use some other site that might not just stop working. (maybe google or github?)

I tried it, but ended up with other errors and had no time to dig deeper.

**Comment by jczuchnowski** [comment]
This doesn't seem to a problem anymore in the current codebase.
