### ISSUE TITLE
Please can you add htmx attributes to zio html

### ISSUE THREAD

**Issue by THM068** [zio/zio-http#2539]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
I have been working with htmx in zio and I have to manually create the attributes from htmx.  I would like zio to include by default e.g
`object HtmxAttributes {

  final def hxGet: PartialAttribute[String] = PartialAttribute("hx-get")
  final def hxTrigger: PartialAttribute[String] = PartialAttribute("hx-trigger")
  final def hxTarget: PartialAttribute[String] = PartialAttribute("hx-target")

}`

**Describe alternatives you've considered**
Manually adding them like the above example

**Additional context**

**Comment by jdegoes** [comment]
This must be done in a separate subproject, which can be contained inside this repo. `zio.http.htmx` or similar.

/bounty $250

**Comment by neo773** [comment]
Can I get assigned to this?

**Comment by jdegoes** [comment]
No, but you can try to complete it before someone else!
