### ISSUE TITLE
Better default error handling and customization of error handling

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2545]
Currently we have `Route.handleErrorCause(f: Cause[Err] => Response)` that gives access to the `Err` and it's cause.
We would like to have a variant, that also let's one access (parts of) the request.

This could be used to handle errors based on the context of the request not only by the user,
but also by methods such as `Route.sandbox`, to give more meaningful error messages.

We also want to some way to customize error handling with some kind of provided behaviour.
This could be used for example to enable things like printing routes on error pages or giving back the closest matching route(s).

Writing a more detailed default error should consider unwanted side effects. Like returning back headers or query parameters to the caller, could lead to leaking security related information. And bodies can be "Read only once" and might not be readable anymore when handling the error.

**Comment by jdegoes** [comment]
@987Nabil You did this one, right?
