### ISSUE TITLE
Requests are incorrectly(?) executed on Netty's event loop executor

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-http#2577]
**Describe the bug**

I'm not sure if this a bug or a feature, but I thought to open this issue just to discuss this behaviour.

Currently, effectful requests are being executed on Netty's executor until a yield operation (or similar) occurs (see reproducer below). I'm not sure whether this is by design (minimize executor context switching) or whether this is a bug. The main issue with this (assuming it's by design) is that with ZIO 2.1-RC1 which uses virtual threads for JDK21+, blocking effects might end up being executed on Netty's event loop group executor which uses platform threads, potentially leading to thread starvation.

Having a look through the code, a simple solution I see would be to "force" the program to be run on ZIO's executor by changing [this line](https://github.com/zio/zio-http/blob/badb929383cdb41d5f88558e60b5e49878c250f4/zio-http/src/main/scala/zio/http/netty/NettyRuntime.scala#L52C5-L52C42) to something like:

```scala
    rtm.unsafe.runOrFork(ZIO.descriptorWith(d => program.onExecutor(d.executor)))
```

Having said that, I don't fully understand the heuristics behind `runOrFork` to know whether in cases that the effect can be run without forking should be executed on ZIOs or Netty's executor. I'm not too sure on the performance implications of doing so, but perhaps in JDK21+ & ZIO 2.1+ all effects should be run with `rtm.unsafe.fork`?

**To Reproduce**

```scala
import zio.*
import zio.http.*

object Main extends ZIOAppDefault {
  private def threadName =
    ZIO.succeed(Response.text(Thread.currentThread().getName))
  def run =
    Server.serve {
        HttpApp(Routes(
          Method.GET / "foo" -> handler(threadName),
          Method.GET / "bar" -> handler(ZIO.yieldNow *> threadName),
        ))
      }
      .provide(Server.defaultWithPort(8080))
}
```

And then:

```shell
curl http://localhost:8080/foo
# KQueueEventLoopGroup-2-2

curl http://localhost:8080/bar 
# ZScheduler-Worker-0
```

**Comment by jdegoes** [comment]
I would expect we need to handle this by detecting if ZIO is using virtual threads and using fallback behavior.

**Comment by kyri-petrou** [comment]
@jdegoes after doing some more digging on this issue, I think that `rtm.unsafe.runOrFork` should be changed to `rtm.unsafe.fork` (well, once [this is resolved too](https://github.com/zio/zio/issues/8751)). The main reasoning for this is that we're [already checking here](https://github.com/zio/zio-http/blob/351f6edf197e85f2176c3a26b9d6bbb533811d76/zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala#L95) whether a response can be written immediately (meaning, the effect is an `Exit`). This means that endpoints returning simple values (such as in benchmarks) won't be affected by this change.

A strong usecase against the current behaviour of `runOrFork`, which is forking on the first async effect is Caliban. In GraphQL, there are 3 stages in which a request is processed:
- Parsing
- Validation
- Execution

Both Parsing and Validation are purely CPU-bound / synchronous tasks, and depending on the size/complexity of the query they can take up to a few milliseconds to execute. Having CPU-heavy work like this running on Netty's Event Loop group executor causes severe performance degradation.

To prove this, here's a small repro:

```scala
package example

import zio._
import zio.http._

object Foo extends ZIOAppDefault {
  val test1 =
    Method.GET / "test1" -> handler(
      ZIO.succeed(Response.text(scala.util.Random.alphanumeric.take(100).mkString)),
    )

  val test2 =
    Method.GET / "test2" -> handler(
      // Yielding to force async
      ZIO.yieldNow *> ZIO.succeed(Response.text(scala.util.Random.alphanumeric.take(100).mkString)),
    )

  // Create HTTP route
  val app = Routes(test1, test2).toHttpApp

  // Run it like any simple app
  override val run = Server.serve(app).provide(Server.default)
}
```

### Test results:

Test 1: No yielding
```
Running 10s test @ http://127.0.0.1:8080/test1
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.74ms   16.02ms 169.05ms   85.31%
    Req/Sec     2.65k     1.10k   13.83k    89.00%
  Latency Distribution
     50%   10.02ms
     75%   23.92ms
     90%   36.85ms
     99%   70.81ms
  316499 requests in 10.03s, 61.27MB read
  Socket errors: connect 0, read 387, write 0, timeout 0
Requests/sec:  31558.14
Transfer/sec:      6.11MB
```

Test 2: With yielding

```
Running 10s test @ http://127.0.0.1:8080/test2
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.89ms    5.47ms 113.90ms   82.91%
    Req/Sec     5.29k     2.49k   11.71k    59.25%
  Latency Distribution
     50%    4.05ms
     75%   10.11ms
     90%   15.54ms
     99%   19.94ms
  632376 requests in 10.03s, 122.43MB read
  Socket errors: connect 0, read 395, write 0, timeout 0
Requests/sec:  63025.41
Transfer/sec:     12.20MB
```

As you can see, `test2` which forces the fiber to be forked is performing better on every aspect (even with the added overhead of yielding!), with double the throughput and an incredibly better p99.

**Comment by jdegoes** [comment]
@kyri-petrou Sounds good!

/bounty $100
