### ISSUE TITLE
Make the client compatible with Scala.js

### ISSUE THREAD

**Issue by williamareynolds** [zio/zio-http#2579]
**Is your feature request related to a problem? Please describe.**
One of the greatest benefits of the Endpoint API is that both a client and a server can be generated from the same code, thus ensuring proper functionality between microservices. If the Client and related Endpoint API code could be compiled with Scala.js, the same Client code could also be used to build a web application. This would really make it possible to do full-stack application development with ZIO in the cleanest possible way.

**Describe the solution you'd like**
My understanding is that zio-http and its client are not Scala.js compatible because of its dependency on Netty. One of the old [project cards](https://github.com/zio/zio-http/projects/4#card-83543384) mentions separating the Client into another project. If it was moved to a new subproject it might be a bit easier to complete this work, and would be useful for anyone intending only to use client functionality (which I'd also love for some of my batch job work).

**Describe alternatives you've considered**
I've seen inklings of eliminating the tight coupling to netty a few times in Discord. I'm not sure there are any alternatives. It may also be possible to separate the Endpoint API and use it to generate a client from another library, but that seems like a similarly difficult approach that just pulls in a new dependency.

**Additional context**
A quick discord search will show that this has come up a few times, but I think this is the first issue about it.

**Comment by 987Nabil** [comment]
/attempt #2579

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clr2ipp0h000fl50f0x3yi9u0/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
