### ISSUE TITLE
Fix for #2468

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2582]
The pull request #2468 has a reproducer for a bug that needs to be fixed in ZIO HTTP.

This ticket is for (a) fixing the bug, and (b) adding the reproducer to the test suite to ensure it's fixed and that it stays fixed.

**Comment by ishqDehlvi** [comment]
/attempt #2582

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clqyfafm60004l80fc965rpm2/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ishqDehlvi** [comment]
How can I reproduce the whole bug??
