### ISSUE TITLE
Endpoint API too strict when chosing the response encoding from the Accept header

### ISSUE THREAD

**Issue by gregor-rayman** [zio/zio-http#2607]
**Describe the bug**
When the endpoint can encode the response to `application/json` but not to other content type, it fails to chose the appropriate encoder when it is not the first one in the `Accept` header. 

**To Reproduce**
Steps to reproduce the behaviour:

Run this simple zio-http server:

```
import zio._
import zio.http._
import zio.http.endpoint.Endpoint
import zio.schema.{DeriveSchema, Schema}
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
object Main extends ZIOAppDefault {

  final case class Person(name: String, age: Int)
  implicit val schema: Schema[Person] = DeriveSchema.gen[Person]

  val dummy = Endpoint(Method.GET / "dummy").out[Person]
  val dummyRoute = dummy.implement {
    Handler.fromFunction(_ => Person("John", 42))
  }

  val app: HttpApp[Any] =
    Routes(
     dummyRoute
    ).toHttpApp

  override val run =
    Server.serve(app).provide(Server.default)
}
```
Access the endpoint with the following curl request. All attempts should respond successfully with a JSON-encoded response.

* `curl http://localhost:8080/dummy` - works
* `curl http://localhost:8080/dummy -H 'Accept: */*'` - works
* `curl http://localhost:8080/dummy -H 'Accept: application/json'` - works
* `curl http://localhost:8080/dummy -H 'Accept: text/plain'` - fails with 500 internal server error. This is expected, even though error 400 would be more appropriate
* curl http://localhost:8080/dummy -H 'Accept: application/json, text/plain'` - works
* curl http://localhost:8080/dummy -H 'Accept: text/plain, application/json'` - fails again with status 500, but this time it should work
* curl http://localhost:8080/dummy -H 'Accept: obscure/unknown, application/json' - fails, this time with status 400

**Expected behaviour**

When the `Accept` header contains the supported content type (even */*), the response should work, even if the content type is not the first one. 

**Additional context**

I guess that the issue is somewhere around the method `HttpCodec.encoderDecoder`. I guess there are two issues: 
1) It really checks only the first `mediaType`, so that it the cases where `application/json` is not the first one, it either picks the wrong encoder (for text/plain), or returns an error (for obscure/unknown).
2) it picks an unsuitable encoder when requested. In the example above it picks text/plain even though that one cannot encode a case class. So it seems that the among the considered encoders are also unsuitable ones. That would explain the status 500 instead of 400.

**Comment by kyri-petrou** [comment]
/attempt #2607

<div id="algora" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;4 ZIO bounties <br/> + 0 bounties from 0 projects | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clrjbpexc001ljw0f7d4hqsed/cancel-attempt) |
