### ISSUE TITLE
Support custom encoding and decoding for Endpoint parameters (in, out, error)

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2625]
1. Introduce `HttpContentCodec`, a new data type that builds on ZIO Schema's notion of `BinaryCodec`, but also adds crucial information on the mime-type for a given binary codec.
    
    ```scala
    package zio.http.codec
    
    final case class HttpContentCodec[A](choices: ListMap[MediaType, BinaryCodec[A]] /* order is priority during encoding */ )
      def ++ (that: HttpContentCodec[A]): HttpContentCodec[A] = ??? // Right one wins (overrides left) if conflict
    
      def lookup(contentType: Header.ContentType): Option[BinaryCodec[A]] = ???
    
      def decodeRequest(request: Request): Either[String, A] = ???
      def decodeResponse(response: Response): Either[String, A] = ???
      def encodeRequest(value: A): Either[String, Request] = ???
      def encode(value: A): Either[String, Response] = ???
    }
    object HttpContentCodec{
      // Derive http codec from schema:
      implicit def fromSchema[A](implicit schema: Schema[A]): HttpContentCodec[A] = ??? // Add all ZIO Schema media types
    
      // Codecs for all the standard types?
      
    }
    ```
2.  Modify `HttpCodec.Content` so that it no longer embeds `Schema`, but rather, so that it uses `HttpContentCodec` directly, which is much more flexible.
    
    ```scala
    private[http] final case class Content[A](
        codec: HttpContentCodec[A],
        name: Option[String],
        index: Int = 0,
      ) extends Atom[HttpCodecType.Content, A] {
    ```
3. Modify all constructors of `Content` (mostly, I think, they appear in `ContentCodecs.scala`) to account for the refactoring of `HttpCodec.Content`.
4. Update all downstream code, particular the encoding/decoding part of `Endpoint`.
5. Change the constructors of `HttpCodec` to require `HttpContentCodec` for the `Err`, `In`, and `Out` types, rather than `Schema`. For convenience and backward compatibility, we could provide a Schema-based variant of all these constructors. Or we could go "all-in" on `HttpContentCodec`.

These changes, taken collectively, will ensure that users can choose whatever way they want to map Scala data types to and from requests and responses.

**Comment by guersam** [comment]
@jdegoes Could you elaborate a use case enabled by `HttpContentCodec` that isn't supported by `Schema`? It will be helpful for implementation.

**Comment by 987Nabil** [comment]
@jdegoes we still need to put the `Schema` somewhere. Else we lose the ability to use it for meta analysis (OpenAPI generation for example). I would suggest as an additional field of `HttpContentCodec`
