### ISSUE TITLE
Fix broken build

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2628]
CI is failing and needs to be fixed.

**Comment by guptadeepak8** [comment]
hey @jdegoes can you pls  give more context to this

**Comment by jdegoes** [comment]
CI is failing. You can fork, submit a blank PR, and inspect the failure and fix it (if you want to take this issue).

**Comment by kyri-petrou** [comment]
@jdegoes issue is with the sbt-github-actions plugin. It's incompatible with the latest release of the graalvm action. Are you happy to disable the plugin until it's fixed?

If yes I can create a PR

**Comment by Akshay-SL** [comment]
/attempt #2628

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clrgkp12v0006ju0fhqgcndmy/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by jigarh12** [comment]
/attempt #2628 I am in waiting list if Akshay-SL gets assigned


<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clrgkp12v0006ju0fhqgcndmy/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by jdegoes** [comment]
@kyri-petrou It would be best to fix the plug-in.

**Comment by guptadeepak8** [comment]
hey, @jdegoes Build was successful for me #2633

**Comment by jdegoes** [comment]
@guptadeepak8 Your branch is out of date, you will probably see it if you update.

**Comment by kyri-petrou** [comment]
/attempt #2628

<div id="algora" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;4 ZIO bounties <br/> + 0 bounties from 0 projects | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clrgkp12v0006ju0fhqgcndmy/cancel-attempt) |
