### ISSUE TITLE
`Server.serve` to log basic server info when mounted

### ISSUE THREAD

**Issue by guersam** [zio/zio-http#2632]
Currently `Server.serve` runs silently and it's fine in simple cases. However, when there are dependencies that take time to initialize before server runs, it's difficult to determine whether the server is running or not, so I usually replace `Server.serve` with this snippet: 

```scala
Server.install(httpApp).flatMap(port => ZIO.logInfo(s"ZIO HTTP server is running at port $port") *> ZIO.never)
```

But doing this every time is cumbersome, and it's easy to forget to add `*> ZIO.never` at the and so that the server stops immediately.

It would be convenient to add a default log message to `Server.serve` which can easily be turned off.

**Comment by 987Nabil** [comment]
Maybe we could first print something like `starting server ...` and at the end what you suggested.
