### ISSUE TITLE
Flaky ScalaJS test

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-http#2645]
Leaving this one here as it happened to me on more than one occasion, and it might need to be addressed. It seems that one of the ScalaJS tests is flaky (see the most recent failure [here](https://github.com/zio/zio-http/actions/runs/7600546320/job/20698924294))

The test suite fails with the following:

```scala
+ ClientSpec
  + HTTP
    - Get
      ✗ Result was false
      string.startsWith("<!doctype html>")
      string = "<!doctype ht"
      at /home/runner/work/zio-http/zio-http/zio-http/js/src/test/scala/zio/http/JSClientSpec.scala:14 

[info] 
[info]     - ClientSpec / HTTP / Get
[info]       ✗ Result was false
[info]       string.startsWith("<!doctype html>")
[info]       string = "<!doctype ht"
[info]       at /home/runner/work/zio-http/zio-http/zio-http/js/src/test/scala/zio/http/JSClientSpec.scala:14 
[info] 
[info] Done
[error] Failed tests:
[error] 	zio.http.JSClientSpec
```

**Comment by kyri-petrou** [comment]
Looking at some other PRs, this seems to be a relatively common occurrence, e.g., https://github.com/zio/zio-http/actions/runs/7599763437/job/20697157555?pr=2643

**Comment by urbit-pilled** [comment]
I think this is due to Google rate-limiting, we could try another site.

**Comment by urbit-pilled** [comment]
/attempt

<div id="algora" />

| [Algora profile](https://console.algora.io/@/urbit-pilled) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @urbit-pilled | &nbsp;&nbsp;&nbsp;1 ZIO bounty <br/> + 1 bounty from 1 project | <div align="center">JavaScript, Scheme, <br />Scala & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clsd1gepr0004la0fwookdj9n/cancel-attempt) |
