### ISSUE TITLE
Improve Endpoint API `BadRequest` handling

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2650]
Currently we only return a http 400, if the endpoint API can't decode the request. That is not very helpful to the user/dev. They can't know what exactly went wrong.

**Improvement**
- Make it possible to return a json or html body (setting or accept header) that let's the caller know what was missing/went wrong
- Make it possible to configure logging of missing request data, that is rendered in a way that is helpful to the developer

**Comment by swoogles** [comment]
This would be extremely valuable 👍

**Comment by jdegoes** [comment]
I think we need two changes:

1. If the user does not handle the error explicitly, then we encode an error in a content-type acceptable to the HTTP client, perhaps defaulting to `application/json`. Moreover, we use a format that is [somewhat standardized](https://stackoverflow.com/questions/12806386/is-there-any-standard-for-json-api-response-format) for returning error details. The main consideration, however, is just making sure that when users don't handle encoding/decoding errors, we do something that helps end-users diagnose and fix their encoding/decoding issues.
2. We need an operator that lifts encoding/decoding errors (currently defects) into `E`, and we need to document that, show how it's used, and make it common practice to deal with it.

**Comment by 987Nabil** [comment]
@jdegoes sounds good to me. I would still have a variant of that 2. operator that just logs the codec errors in a standard way. Will be helpful in development.

**Comment by jdegoes** [comment]
All right, so we have:

1. If the user does not handle the error explicitly, then we encode an error in a content-type acceptable to the HTTP client, perhaps defaulting to application/json. Moreover, we use a format that is [somewhat standardized](https://stackoverflow.com/questions/12806386/is-there-any-standard-for-json-api-response-format) for returning error details. The main consideration, however, is just making sure that when users don't handle encoding/decoding errors, we do something that helps end-users diagnose and fix their encoding/decoding issues.
2. We need an operator that lifts encoding/decoding errors (currently defects) into E, and we need to document that, show how it's used, and make it common practice to deal with it.
3. We need another operator that logs the codec errors in a standard way, useful for development.

The operators should be defined probably on `Handler` all the way up to `Routes` (including `Route`).

Make sense & agreed? cc @swoogles @atooni

**Comment by 987Nabil** [comment]
/attempt #2650

<div id="algora" />

| [Algora profile](https://console.algora.io/@/987Nabil) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @987Nabil | &nbsp;&nbsp;&nbsp;27 ZIO bounties <br/> + 0 bounties from 0 projects | <div align="center">Scala</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clsd19ek2001jlb0f5lecvtus/cancel-attempt) |

**Comment by feliciien** [comment]
/attempt #2650

<div id="algora" />

| [Algora profile](https://console.algora.io/@/feliciien) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @feliciien | 4 bounties from 1 project | <div align="center">MDX, Rust, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clsd19ek2001jlb0f5lecvtus/cancel-attempt) |
