### ISSUE TITLE
Html.fromString Behavior Change

### ISSUE THREAD

**Issue by eltimn** [zio/zio-http#2651]
**Describe the bug**
I'm not sure if this is a bug or if it was intentional, but `Html.fromString` now encodes the string, so the browser just shows the escaped text instead of the rendered html.

I believe it was [this commit](https://github.com/zio/zio-http/commit/61fa20b15e8e3210c37561c8e005df423dcc3d48#diff-eaeb9cdca05316230a5f8a646e0e77b0f55204715fd479c95878b3dead921c3cR37) that caused the behavior change.

If it was not intentional, then I think the easiest fix would be to change `Html.fromString` to:

```
implicit def fromString(string: CharSequence): Html = Html.Single(Dom.raw(string))
```

I wasn't able to test this as sbt is giving me some trouble.

I did figure out I could use `Html.fromDomElement(Dom.raw(myString))` instead so as long as that doesn't change, I'm good to go. Just thought you would want to know about the behavior change.

**To Reproduce**
Create a Route that uses `Html.fromString`:
```
Method.GET / "" -> handler(
  Response.html(
    Html.fromString(
      """<div class="container1 container2"><a href="http://zio.dev">ZIO Homepage</a></div>"""
    )
  )
)
```

I created a [git repo](https://github.com/eltimn/zio-http-string) that has a route like that, it also includes a route using `formDomElement`:

**Comment by jdegoes** [comment]
/bounty $50 for adding `Html.raw`.

I think it's safer that `Html.fromString` perform escaping to prevent code injection attacks.

**Comment by Bhavyajain21** [comment]
/attempt #2651

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clsd18ycg0008lf0fsck9omtf/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
