### ISSUE TITLE
asMultipartForm method consuming a lot of heap memory

### ISSUE THREAD

**Issue by zeffd** [zio/zio-http#2660]
**Describe the bug**
When uploading a file using `multipart/form-data` we have to get the `Form` using `asMultipartForm` method from request body. And using debugging and live memory stats I understood that when `asMultipartForm` function is called:
If I'm uploading ~ 500MB of file => the heap consumption is more than 4GB, which is a lot in comparison to file size.

**Screenshots**
<img width="957" alt="Screenshot 2024-02-01 at 12 10 19 PM" src="https://github.com/zio/zio-http/assets/24843511/5c9490a8-b203-4ab1-bf43-32c59187dc37">

**Additional context**
 - OS: macOS
 - Java 17
 - `zio-http` version: `3.0.0-RC4`

**Comment by 987Nabil** [comment]
@zeffd Could you please provide a code example? I want to avoid that someone tries to fix this bug and is looking at the wrong place because he sets up the server slightly different or something like that.

**Comment by zeffd** [comment]
Hello @987Nabil I just used this example [given here](https://github.com/zio/zio-http/blob/aecd87cbf019b37535d0170bce0e1ddce184dfb8/zio-http-example/src/main/scala/example/MultipartFormData.scala#L9)
and server config I tried with `RequestStreaming` enabled and disabled both ways like that:
`Server.defaultWith(config => config.port(8080).requestStreaming(RequestStreaming.Disabled(Int.MaxValue)))`
`Server.defaultWith(config => config.port(8080).requestStreaming(RequestStreaming.Enabled))`
and the result is same.

**Comment by alexander-klimov** [comment]
> Hello @987Nabil I just used this example [given here](https://github.com/zio/zio-http/blob/aecd87cbf019b37535d0170bce0e1ddce184dfb8/zio-http-example/src/main/scala/example/MultipartFormData.scala#L9) and server config I tried with `RequestStreaming` enabled and disabled both ways like that: `Server.defaultWith(config => config.port(8080).requestStreaming(RequestStreaming.Disabled(Int.MaxValue)))` `Server.defaultWith(config => config.port(8080).requestStreaming(RequestStreaming.Enabled))` and the result is same.

AFAIK both of these servers would run with streaming enabled. The difference is that the first option would forbid streaming requests that exceed `Int.MaxValue` in size, but smaller streaming requests would go through just fine.

**Comment by jdegoes** [comment]
/bounty $250 (assuming the issue is verified)

**Comment by oliverqx** [comment]
/attempt #2660

<div id="algora" />

| [Algora profile](https://console.algora.io/@/oliverqx0) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @oliverqx | 1 bounty from 1 project | <div align="center">TypeScript, Python</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clsd15dm8000llb0fddvex876/cancel-attempt) |

**Comment by kyri-petrou** [comment]
/attempt #2660

<div id="algora" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;5 ZIO bounties <br/> + 0 bounties from 0 projects | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clsd15dm8000llb0fddvex876/cancel-attempt) |
