### ISSUE TITLE
Improve `Request` query param handling

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2662]
`Request` has a lot of methods via `HeaderOps` that can query or manipulate headers.

The same is not true for query parameters. To have a unified and easier API on `Request`, we should add such methods.
For example `Request#query` or `Request#queryTo`.

Maybe we can use the same design as for `HeaderOps` and enable the same features for response.

**Comment by jdegoes** [comment]
/bounty $100 for a similar level of convenience as `HeaderOps` (`QueryOps`?).
