### ISSUE TITLE
ZIO HTTP Doesn't Match GET Requests That Have a Body

### ISSUE THREAD

**Issue by khajavi** [zio/zio-http#2677]
## Steps to Reproduce:

Define routes using ZIO HTTP, as shown in the code snippet:

```scala
Routes(
    Method.POST / "foo" -> Handler.fromResponse(
      Response.text("POST method called!")
    ),
    Method.GET / "foo" -> Handler.fromResponse(
      Response.text("GET method called!")
    ),
)
```

Make a GET request to the defined route with a request body, for example:

```
curl -X GET http://127.0.0.1:8080/foo -d "bar"
```

## Expected Behavior:

I expect the ZIO HTTP to correctly match the GET request to the corresponding route handler, returning the response:

`GET method called!`

## Actual Response:

`POST method called!`

**Comment by kyri-petrou** [comment]
/attempt #2677

<div id="algora" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;6 ZIO bounties <br/> + 0 bounties from 0 projects | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clsjjz6170004l40f7vdketms/cancel-attempt) |

**Comment by kyri-petrou** [comment]
@khajavi I can't seem to be able to reproduce the issue. I'm running server the following and I get the correct response when I execute the curl command

```scala
object Foo extends ZIOAppDefault {
  val app = Routes(
    Method.POST / "foo" -> Handler.fromResponse(
      Response.text("POST method called!")
    ),
    Method.GET / "foo" -> Handler.fromResponse(
      Response.text("GET method called!")
    ),
  ).toHttpApp
  
  def run = Server.serve(app).provide(Server.default)
}
```

Is there potentially something else that you didn't include in the issue that could cause this bug?

<img width="415" alt="image" src="https://github.com/zio/zio-http/assets/67301607/01678aad-3e7b-4e77-818e-500cc01e3f4a">

**Comment by khajavi** [comment]
@kyri-petrou Sorry! I tried again and found out that my mistake was using `-x` instead of `-X` when using the curl command!
