### ISSUE TITLE
Improve Routes DSL to support complex URI template patterns

### ISSUE THREAD

**Issue by w0rxbend** [zio/zio-http#2679]
**Is your feature request related to a problem? Please describe.**
Extend capabilities of ZIO HTTP routes to cover use cases described in [RFC 6570 - URI Template](https://www.rfc-editor.org/rfc/rfc6570)
The issue that I came across is that the current ZIO Route DSL does not support defining complex use cases such as the following:
- multiple path variables in the same path segment, e.g, `http://example.com/people/{firstName}-{lastName}/SSN`
- extractor and literal within the same path segment, e.g `http://example.com/people/{firstName}-some-literal/SSN` or  `http://example.com/people/some-literal-{firstName}/SSN`

Just for reference: https://docs.micronaut.io/latest/guide/#routing, Many other frameworks, including Spring, Quarkus, dotnet, actix-web, implement the URI template specification. But no single scala HTTP library is capable of that.

It would be nice to have the flexibility to define complex routes via Route DSL and Endpoint DSL to have a well-designed and documented API.

![image](https://github.com/zio/zio-http/assets/8176996/f09ad15f-0432-4b57-9754-7a2724ad0a96)

It seems that it is not possible right now to define a route that will follow [Resource Oriented API with custom methods](https://aip-dev.github.io/aip.dev/136) (more details [here](https://cloud.google.com/apis/design/custom_methods))

I remember that something similar was discussed in the zio-http discord channel - https://discord.com/channels/629491597070827530/819703129267372113/1162396036237623326 but without proper resolution.

**Describe the solution you'd like**
I want to have DLS that provide an ability to define
 - multiple path variables in the same path segment:
```scala
POST / "virtual-machines" / string("vmId") / "instances" / PathCodec.combined(string("instanceId"), literal("_"), string("some_other_var"))
```
- extractor and literal within the same path segments
 ```scala
POST / "virtual-machines" / string("vmId") / "instances" / PathCodec.combined(string("instanceId"), literal(":reboot"))
```

**Describe alternatives you've considered**

@erikvanoosten, probably you have some ideas, coz I remember [discussion](https://discord.com/channels/629491597070827530/819703129267372113/1162443016544456794) in discord about problem related to this issue.

**Additional context**
https://softwaremill.community/t/paths-components-without-separator/317

**Comment by jdegoes** [comment]
/bounty $750 for solution that does not impact performance and remains "zero allocation" and efficient, as well as backward compatible.

**Comment by bradovitt** [comment]
/attempt #2679

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx18fc5i001zjy09bx7vlek5/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by kyri-petrou** [comment]
/attempt #2679

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | 18 ZIO bounties | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx18fc5i001zjy09bx7vlek5/cancel-attempt) |
