### ISSUE TITLE
Compilation bug when using `disableAutoTrace` and `ZLayer.makeSome` in Scala 3

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-http#2700]
Tested with both 2.0.21 and 2.1-RC1, the code below gives a compilation error in Scala 3 (works fine in Scala 2.x)

```scala
import zio.*
import zio.stacktracer.TracingImplicits.disableAutoTrace

object Foo {
  def foo(using Trace): Unit = ZLayer.makeSome[Unit, Unit](ZLayer.succeed(()))
}
```

Error:
```
scala: [error] <empty>.Foo.foo.x(main.scala:5)
[error]  
[error]  No automatically generated traces are permitted here. Add an implicit parameter
[error]  to pass through a user generated trace or explicitly call `newTrace`
[error]  to force generation of a new trace.
[error]  
[error]  copy/paste:
[error]    (implicit trace: Trace)  <- no existing implicit parameter list
[error]    , trace: Trace           <- existing implicit parameter list
[error]    (newTrace)                       <- I know what I'm doing, generate a new trace anyway
[error]    
```

**Comment by mobley-trent** [comment]
/attempt #2700

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mobley-trent) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mobley-trent | 3 bounties from 2 projects | <div align="center">Python, Rust, <br />Jupyter Notebook</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx18d59o0017mp09v6f2i6se/cancel-attempt) |

**Comment by kyri-petrou** [comment]
I have no idea how this happened, but I'm fairly certain I opened this issue in the wrong repo (should have been opened in zio instead). Closing and I'll reopen there in case the issue is still around, although I think it might be resolved with some of the latest ZLayer macro changes
