### ISSUE TITLE
UserAgent regex broken in ScalaJS

### ISSUE THREAD

**Issue by swoogles** [zio/zio-http#2707]
**Describe the bug**

This blows up when its referenced in the browser.
 
https://github.com/zio/zio-http/blob/28c9de1d09b9d8da903dd80edda4a5c4277a5b88/zio-http/shared/src/main/scala/zio/http/Header.scala#L4151

**To Reproduce**
On snapshot - [3.0.0-RC4+77-66867e7f-SNAPSHOT/](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-http_2.13/3.0.0-RC4+77-66867e7f-SNAPSHOT/)

```
object Main extends ZIOAppDefault{
  def run =
    ZIO.succeed(Header.UserAgent)
}
```

<img width="1720" alt="Screenshot 2024-02-27 at 4 40 59 PM" src="https://github.com/zio/zio-http/assets/2054940/f6e97e46-bdc4-4c47-a9d1-2779633d4205">

**Comment by 987Nabil** [comment]
Is this actually a zio http error? It seems like valid scala code is producing invalid js code. Is this a scalajs bug?

**Comment by jamesward** [comment]
Regex's that are used in both JS and the JVM, must be compatible with both. No way around there being two different Regex engines.

**Comment by 987Nabil** [comment]
@jamesward that's my point. I as a lib dev should not make sure that my regex works for both. That should be the scala js compiler/transpiler

**Comment by jamesward** [comment]
I agree. But unfortunately I don't think Scala has any plans to write their own Regex engine. So the reality for now is that users have to write Regex that works on their target platforms.

**Comment by swoogles** [comment]
Related (Almost decade-old) thread-
https://github.com/scala-js/scala-js/issues/997#issuecomment-54197139

**Comment by 987Nabil** [comment]
Okay 🙄  At least the issue is clear now.

One way around would be to not use regex at all for the header parsing but `RichTextCodec`

**Comment by russwyte** [comment]
Would zio-parser be a viable option? One possible win would be that it is invertible.

**Comment by 987Nabil** [comment]
`RichTextCodec` is similar to zio parser and we would not have another dependency.

**Comment by pablf** [comment]
/attempt #2707

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/pablf) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @pablf | &nbsp;&nbsp;&nbsp;24 ZIO bounties <br/> + 1 bounty from 1 project | <div align="center">Scala, Rust</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx18by6c000ump09j6v3fo4b/cancel-attempt) |
