### ISSUE TITLE
JsonSchema.fromZSchemaMulti Fails for Sequences of Custom Types in Primitive Formats

### ISSUE THREAD

**Issue by sangwoo-sean** [zio/zio-http#2715]
The `JsonSchema.fromZSchemaMulti` function exhibits unexpected behavior when generating JSON schemas for sequences (like `Chunk`, `List`, etc.) of custom types that are represented in primitive formats. This issue is not confined to opaque types but extends to any custom type that is presented as a primitive value in the schema.

**Reproducer** ([Scastie Link](https://scastie.scala-lang.org/guersam/oINpuafLS06cZnafk4Z6uw))

```
import zio.http.endpoint.openapi.JsonSchema
import zio.schema.*

opaque type IntString = Int
given Schema[IntString] =
  Schema[String].transformOrFail(
    str => str.toIntOption.toRight("invalid format").asInstanceOf[Either[String, IntString]],
    is => Right(is.toString)
  )

// Works as expected
JsonSchema.fromZSchemaMulti(Schema[IntString])         // ok
JsonSchema.fromZSchemaMulti(Schema[Option[IntString]]) // ok

// Fails
JsonSchema.fromZSchemaMulti(Schema[List[IntString]])   // fails
JsonSchema.fromZSchemaMulti(Schema[Chunk[IntString]])  // fails
```

checked in version v3.0.0-RC4

**Comment by sangwoo-sean** [comment]
It appears that issue #2543 has addressed this matter, though it's uncertain if it's considered fully resolved.

**Comment by jdegoes** [comment]
/bounty $50 for test cases proving it's resolved (or not).

**Comment by guersam** [comment]
I confirmed that it works with RC8. ([scastie](https://scastie.scala-lang.org/vmNKHFt2SJu93VJwaFamTw))

Before (RC4)
![image](https://github.com/zio/zio-http/assets/969120/6b79d0c3-1e72-4a95-b7cd-9b5dcc97e48d)

After (RC8)
![image](https://github.com/zio/zio-http/assets/969120/481fea0c-5f2a-447e-abec-454f9aed129a)
