### ISSUE TITLE
Use `@description` zio-schema annotation at types for generating OpenAPI docs

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2722]
Currently we can handover docs explicitly in the in/out methods of the Endpoint API or use `??` on a content codec to add docs to the type while generating OpenAPI. We should also respect the `@description` annotation of zio-schema for the type, if it exists.

This is already working for fields, but not for top-level types.

**Comment by fernanluyano** [comment]
I think this is a bug instead of an enhancement. Assuming this issue of not populating a description like below. Since it's required by OAS 3.1
![Screenshot 2024-03-15 at 1 04 47 PM](https://github.com/zio/zio-http/assets/7608751/68499af4-81ea-4314-8bc8-faaf689fe61a)

**Comment by 987Nabil** [comment]
@fernanluyano this is related, but not the same. The error you describe comes due to the fact that the field is optional and therefor left out when serialising the open API. Is should be non optional with a default value.

This is, that we want to have a different source for the docs. And this is not a bug.

**Comment by mobley-trent** [comment]
/attempt #2722

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mobley-trent) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mobley-trent | 3 bounties from 2 projects | <div align="center">Python, Rust, <br />Jupyter Notebook</div> | <div align="center">﹟2700</div> | [Cancel attempt](https://console.algora.io/api/bounties/clx18ahx80028l809d4srumsn/cancel-attempt) |

**Comment by mobley-trent** [comment]
is this issue still open @987Nabil ?

**Comment by 987Nabil** [comment]
@mobley-trent Hey 👋 Sorry, I actually just opened a PR for this. Should have written here something first I guess 😅
