### ISSUE TITLE
Header.Authorization.Unparsed with empty authScheme cause code to hang forever

### ISSUE THREAD

**Issue by gaeljw** [zio/zio-http#2742]
**Describe the bug**

When using client code sending a request with an `Authorization` header with no scheme (`Header.Authorization.Unparsed("", "some-key")`), the client code hangs forever.

**To Reproduce**

Reproduction repository: https://github.com/gaeljw/ziohttp3hanging

Run `sbt test`.

The test hangs forever.

_Note that sometimes the test may fail with a pact server issue like `Cause: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connexion refused: localhost/[0:0:0:0:0:0:0:1]:33523`, ignore this case, and just retry. It's not the issue I care about for now._

**Expected behaviour**

The test should succeed with output like:
```
[info] MyWsClientPactTest:
[info] MyWsClient
[info] - should retrieve a model
[info] Run completed in 3 seconds, 99 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

It does when changing the `headers` value in `MyWsClient` to any of these 3 other variants:
```diff
- val headers: Headers = Headers(Header.Accept(MediaType.application.json), Header.Authorization.Unparsed("", "plop-key"))
+ val headers: Headers = Headers(Header.Accept(MediaType.application.json), Header.Custom("Authorization", "plop-key"))
+ val headers: Headers = Headers(Header.Accept(MediaType.application.json), Header.Authorization.Unparsed("something", "plop-key"))
+ val headers: Headers = Headers(Header.Accept(MediaType.application.json))
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

The issue appears when upgrading from zio-http 0.0.5 to 3.0.0-RC4.

**Comment by daredevil3435** [comment]
/attempt #2742 
1. Issue involves changing value of `val headers`, right? 
2. I have macos

**Comment by gaeljw** [comment]
@daredevil3435 

> Issue involves changing value of `val headers`, right?

Not sure what you mean by that? The issue is fixed if I declare `val headers` differently. But the point is to not have to do so or at the very least fail with an explicit error rather than having the code just hanging.

**Comment by daredevil3435** [comment]
> @daredevil3435
> 
> > Issue involves changing value of `val headers`, right?
> 
> Not sure what you mean by that? The issue is fixed if I declare `val headers` differently. But the point is to not have to do so or at the very least fail with an explicit error rather than having the code just hanging.

I'm kind of new here so it is quite overwhelming for me, and I do have many questions to ask, so I'm sorry about that. But can you explain me what exactly needs to be done?

**Comment by gaeljw** [comment]
No offense but if I knew what needs to be done, I'd probably do it.

I've provided a reproduction case, the goal is that the code in the reproduction case doesn't hang when you run it.

Can you expand on what is unclear to you?

**Comment by daredevil3435** [comment]
> No offense but if I knew what needs to be done, I'd probably do it.
> 
> I've provided a reproduction case, the goal is that the code in the reproduction case doesn't hang when you run it.
> 
> Can you expand on what is unclear to you?

I think it's my mistake that without prior knowledge I shouldn't have commented on this issue. sorry for the inconvenience.
