### ISSUE TITLE
Endpoints from cases classes where the last field is an Option[Int] or Option[Long] result in BadRequest

### ISSUE THREAD

**Issue by russwyte** [zio/zio-http#2766]
**Describe the bug**
Endpoints from cases classes where the last field is an Option[Int] or Option[Long] result in BadRequest when the request body is pretty printed json.

**To Reproduce**
See [this issue and PR](https://github.com/zio/zio-schema/issues/675)

That PR should be acted on and a new version of zio-schema should be released this project should update its dependency to reflect the new version.

**Expected behaviour**
Valid  and correctly encoded JSON should not result in BadRequest.

**Screenshots**

**Comment by jdegoes** [comment]
/bounty $150 for fixing this, either here or in upstream, and adding test here to ensure it works.

**Comment by russwyte** [comment]
@jdegoes I actually fixed the root cause (via zio-schema PR) [here](https://github.com/zio/zio-schema/issues/675):

**Comment by russwyte** [comment]
Here is the upstream fix 
https://github.com/zio/zio-schema/pull/676
