### ISSUE TITLE
Many binary MediaTypes marked as NotBinary

### ISSUE THREAD

**Issue by dwischolek-modulon** [zio/zio-http#2771]
**Describe the bug**
Many content types in that I think should be regarded binary are defined as NotBinary in MediaTypes.scala.
For example:
"application/vnd.ms-excel"
"application/vnd.ms-cab-compressed"
...
This leads to multipart form entries being decoded, becoming unusable in the process.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build simple file upload with multipart/form-data
2. upload .xls file
=> file data is interpreted as FormField.Text and content garbled.

**Expected behaviour**
.xls file form field would be regarded as FormField.Binary

In general, I think if such a huge list of MimeTypes is even needed, the default behavior should be for the entries to be Binary so that no data is lost due to conversion. At least there should be a way for the user to override individual entries.

**Comment by guersam** [comment]
As discussed in #934, the media types are written by hand, not autogenerated from a reliable source. Until it's resolved, please feel free to open PRs to fix misclassified types (although I'm not a maintainer :sweat_smile: ).
