### ISSUE TITLE
Improving benchmarks

### ISSUE THREAD

**Issue by Khepu** [zio/zio-http#280]
Hello,

I noticed it has been a while since the `BENCHMARKS.md` file was updated. Is it possible that you could run these tests again? There are a couple of other issues with it in its current state. One of the most important ones is that there is no mention of the version used for the competing frameworks. This makes your benchmarks unreliable and unverifiable at best... Another minor issue with it is that the transfer rate of your library with regards to JSON files has been omitted. Lastly, while all results are sorted by performance one stands out: Finagle. I firmly believe that ranking the results properly would provide a better understanding of the options one has and how to weigh them.

**Comment by ShrutiVerma97** [comment]
#941
