### ISSUE TITLE
Multiple Strings to a single Handler

### ISSUE THREAD

**Issue by Rich2** [zio/zio-http#2815]
Request for a more succinct version of

```
val routes: Routes[Any, Response] = Routes(
    Method.GET / "" -> handHome,
    Method.GET / "index.html" -> handHome,
    Method.GET / "index.htm" -> handHome,
    Method.GET / "index" -> handHome
```

So personally my preference would be to for both a general solution to map from a collection of Strings to a Routes collection. But also a specific case as I imagine a good proportion of web sites will want to cover the standard Home page entry points.

I'm just starting to try out ZIO, so apologies, I don't think I can give a more detailed view that would be of value.

**Comment by GrigoriiBerezin** [comment]
I'm not sure that it is a good way to implement such method, but it can be represented like so:
```
val routes: Routes[Any, Response] = Routes(Method.GET / anyOf("", "index.html", "index.htm", "index") -> handSome)
```
Do we need method for that in library?

**Comment by kyri-petrou** [comment]
> I'm not sure that it is a good way to implement such method, but it can be represented like so:
> 
> ```
> val routes: Routes[Any, Response] = Routes(Method.GET / anyOf("", "index.html", "index.htm", "index") -> handSome)
> ```
> 
> Do we need method for that in library?

I like this approach, but I would perhaps consider using `|` or `||` instead?

```scala
Method.GET / ("" | "index.html" | "index.htm" | "index") -> handSome
```

**Comment by jdegoes** [comment]
The disadvantage of `|` is that it would have to be an extension method on a string. Whereas a method like `anyOf` requires no extensions. But either could work.

/bounty $75

**Comment by Anshgrover23** [comment]
Could you please specify what should I do in the pull request because I do not think its required to change code
/claim #2815
