### ISSUE TITLE
Stream body with environmentment access or scope

### ISSUE THREAD

**Issue by guersam** [zio/zio-http#2817]
Currently `Body.fromStream*` and `Response.fromServerSentEvents` fix the `R` type of the output stream to be `Any`. It blocks or makes difficult to implement some use cases such as: 

- A Server Sent Event response stream might want access internal modules via environment.
- Use a resourceful ZIO effect with a stream body, i.e. A temporary file `RIO[Scope, File]` that should be deleted after the stream terminates.

There are some workarounds like `ZIO.environmentWith(stream.provideEnvironment)`, but it does not go well with `Scope` because the stream outlives the handler in the current design.

**Comment by asr2003** [comment]
/attempt #2817

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx172ojw0008mc099vd2xenz/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by guersam** [comment]
Just throwing out an idea here: what do you all think about introducing something like ~~`Response.scoped`~~ `Handler.scoped`? I know releasing 3.0.0 final is our main focus right now, so I want to make sure any changes due to this issue won't break things when it's implemented after the release.

@jdegoes @987Nabil

**Comment by guersam** [comment]
There's a potential breakage in `Body.StreamBody` and `Body.from*Stream*` constructors which require `Stream[Any, Throwable, A]`. I wonder if a new major release is required to introduce this kind change.
