### ISSUE TITLE
Nesting routes work strange when handling errors

### ISSUE THREAD

**Issue by jiramares** [zio/zio-http#2823]
When I am nesting routes as described at https://zio.dev/zio-http/dsl/routes it works until I need call `handleError`.

This server:
```
val routes = literal("to") / Routes(
    Method.GET / "other" ->  handler(ZIO.fail(MyErrors.IdFormatError)),
    Method.GET / "do" / string("id") -> handler { (id:String, _: Request) => Response.text(s"GET /to/do/${id}") }
).handleError(_ match
    case MyErrors.IdFormatError => Response.badRequest
)

def run = Server.serve(routes.toHttpApp).provide(Server.defaultWithPort(8090))

enum MyErrors:
    case IdFormatError
```

When started and invoked `curl -i http://localhost:8090/to/do/45` outputs:
```
HTTP/1.1 500 Internal Server Error
warning: 199 ZIO HTTP "Exception in thread &quot;zio-fiber-37&quot; java.lang.RuntimeException: Expected path segment &quot;do&quot; but found "
content-length: 0
```

But when the route leading to error (that I have to deal with) is removed:
```
val routes = literal("to") / Routes(
    Method.GET / "do" / string("id") -> handler { (id:String, _: Request) => Response.text(s"GET /to/do/${id}") }
)

def run = Server.serve(routes.toHttpApp).provide(Server.defaultWithPort(8090))
```

Everything works fine and the result of `curl -i http://localhost:8090/to/do/45` is:
```
HTTP/1.1 200 OK
content-type: text/plain
content-length: 18

GET /to/do/45
```

**Comment by jdegoes** [comment]
/bounty $75 for fix and reproducer test case.

**Comment by Anshgrover23** [comment]
/attempt #2823


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx171stf0004jl09l6xb4gr2/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
