### ISSUE TITLE
3.0.0-RC7 regression when enabling compression serving static content

### ISSUE THREAD

**Issue by gcsolaroli** [zio/zio-http#2854]
**Describe the bug**
When enabling compression of the response (`Server.Config.ResponseCompressionConfig.default`) content served via `Handler.fromFile` is not handled correctly by browsers.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone project https://github.com/gcsolaroli/responseCompression
2. `sbt run`
3. Try to load http://localhost:8080/directory/static/index.html
4. Page doesn't load due to an "unsupported form of compression" error (label reported by Firefox)

**Expected behaviour**
The page should show an "Hello!" message.
The almost equivalent URL http://localhost:8080/resources/static/index.html correctly shows the page content; this second path is managed using `Handler.fromResource` instead of `Handler.fromFile`.

**Desktop (please complete the following information):**
 - OS: MacOS 14.5 (23F79)
 - Firefox / Safari
 - Firefox 126.0 (64-bit) / Safari 17.5 (19618.2.12.11.6)

**Additional context**
If the compression is disabled (commenting out line 14 in Main.scala) both URLs work correctly.

**Comment by kyri-petrou** [comment]
I'll take a look, I fixed a similar issue for streaming responses, must have missed this one.

By the way, does this work for you using 3.0.0-RC6? I'm able to reproduce it with that version as well

**Comment by gcsolaroli** [comment]
It was working in RC4; not sure in which version it actually appeared.

**Comment by gcsolaroli** [comment]
Just checked, and RC6 seems to work correctly. The sample project does not compile just changing zio-http version, but it's enough to add a `.toHttpApp` when "installing" `staticContent` to fix it.
