### ISSUE TITLE
Setting maxRequestSize changes type from Server to UServer.

### ISSUE THREAD

**Issue by ilya-lt** [zio/zio-http#286]
this:
Server
      .start(1108, app)
works well.

while this:
Server
      .maxRequestSize(100 * 1024)
      .start(1108, app)
 doesn't compile, I think this simple configuration function shouldn't break the start function.

**Comment by dinojohn** [comment]
start(port,app) can be used in simple cases where we have an HttpApp. Also it's not a method of the Server sealed trait. For customisations like changing maxRequestSize, you can concatenate instances of Server sealed trait and call methods like make() or start(). The HttpsHelloWorld example enables SSL in a similar pattern. Hope this helps.

**Comment by maciejbak85** [comment]
```
def startServer[R <: Has[_]](port: Int, http: HttpApp[R, Throwable], size: Int): ZIO[R, Throwable, Nothing] =
    (Server.port(port) ++ Server.app(http) ++ Server.maxRequestSize(size)).make.useForever
      .provideSomeLayer[R](EventLoopGroup.auto(0) ++ ServerChannelFactory.auto)
```
