### ISSUE TITLE
circularity in docs

### ISSUE THREAD

**Issue by TimPigden** [zio/zio-http#2865]
the link on the front git page
Learn more on the [ZIO Http homepage](https://github.com/zio/zio-http)!

is just redirected back to the same place. Where should we learn more?

**Comment by ezhil56x** [comment]
/attempt #2865

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | &nbsp;&nbsp;&nbsp;4 ZIO bounties <br/> + 27 bounties from 10 projects | <div align="center">JavaScript, TypeScript, <br />Java & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx0xpvca0002lb090m9qjk6c/cancel-attempt) |
