### ISSUE TITLE
Replace Endpoint middleware concept with Security concept

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2888]
Right now, we cannot enforce that endpoint middleware is actually implemented (it's a very complicated problem that cannot be solved in time for release). Simultaneously, we cannot document security requirements of endpoints.

To fix this issue, we should instead use a `sealed trait AuthType`, or similar, which is placed into `Endpoint`. Based on this, we can generate OpenAPI documentation, as well as potentially even leverage this information in the automatic HTTP client.

```scala
sealed trait AuthType {
  type ClientRequirements
  type ServerRequirements
}
object AuthType {
  case object Basic extends AuthType {
    type ClientRequirements = ...
    type ServerRequirements = ...
  }
  ... 
}
```

Note that endpoint auth type would still be a type parameter, albeit constrained (Z <: AuthType). The reason is to statically retain the type members inside the `AuthType` value, so they can be used by client and server.

This requires more R&D but should address all of the issues with endpoint middleware that we have, currently. The question is, can we do it in time? 😄

**Comment by 987Nabil** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/987Nabil) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @987Nabil | &nbsp;&nbsp;&nbsp;35 ZIO bounties <br/> + 1 bounty from 1 project | <div align="center">Scala</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx3duvut000fl709ggqvj6zk/cancel-attempt) |

**Comment by 987Nabil** [comment]
Will be streaming the impl. tomorrow or on the weekend
/attempt #2888

**Comment by 987Nabil** [comment]
Will be streaming the impl. tomorrow or on the weekend

**Comment by promisingcoder** [comment]
/attempt #2888

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx3duvut000fl709ggqvj6zk/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
