### ISSUE TITLE
[gen] the codegen from openapi does not respect additionalProperties which is how open products (maps/dictionaries) are defined

### ISSUE THREAD

**Issue by hochgi** [zio/zio-http#2901]
**Describe the bug**
Using a type that has an open product member, e.g:
```yaml
type: object
additionalProperties:
  type: string
```
according to openAPI spec:
https://swagger.io/docs/specification/data-models/dictionaries/
should be rendered as `Map[String, String]` but instead an empty case class with capitalized name of the field is generated.

**To Reproduce**
use e.g. the following openAPI yaml:
```yaml
info:
  title: Animals Service
  version: 0.0.1
servers:
  - url: http://127.0.0.1:5000/
tags:
  - name: Animals_API
paths:
  /api/v1/zoo:
    get:
      operationId: get_animals
      tags:
        - Animals_API
      description: Get all animals count
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animals'
openapi: 3.0.3
components:
  schemas:
    Animals:
      type: object
      required:
        - total
        - counts
      properties:
        total:
          type: integer
          format: int32
        counts:
          type: object
          additionalProperties:
            type: integer
            format: int32
```

generate with zio-http-gen, and  examine the generated component:

```scala
package dev.zoo.openapi.component

import zio.schema._

case class Animals(
  total: Int,
  counts: Counts
)
object Animals {

  implicit val codec: Schema[Animals] = DeriveSchema.gen[Animals]

}
case class Counts(
)
object Counts {

  implicit val codec: Schema[Counts] = DeriveSchema.gen[Counts]

}
```

**Expected behaviour**
The generated case class should look like:

```scala
case class Animals(
  total: Int,
  counts: Map[String, Int]
)
```

**Comment by wesleymatosdev** [comment]
/attempt #2901

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ologbonowiwi) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ologbonowiwi | 51 bounties from 6 projects | <div align="center">Rust, TypeScript, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxal8keh0004mi096uwek0ub/cancel-attempt) |

**Comment by Anshgrover23** [comment]
/attempt #2901

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxal8keh0004mi096uwek0ub/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
