### ISSUE TITLE
java.net.ConnectException finishConnect(..) failed when upgrading to zio-http 3.x

### ISSUE THREAD

**Issue by gaeljw** [zio/zio-http#2902]
**Describe the bug**

After upgrading from 0.0.5 to 3.0.0-RC8 (or 3.0.0-RC5), I'm facing errors approximately 30% of the time.

**To Reproduce**

Reproduction repository: https://github.com/gaeljw/ziohttp3hanging/tree/connect-exception (use the `connect-exception` branch).

Run `sbt test` multiple times.

The test fails ~30% of the time with following error stack:

```
[info] MyWsClientPactTest:
[info] MyWsClient
[info] - should retrieve a model *** FAILED ***
[info]   com.mycompany.Defects$ExternalServiceError: Error with an external service
[info]   at com.mycompany.MyWsClient.$anonfun$callAndHandleResponse$2(MyWsClient.scala:61)
[info]   at zio.ZIO.$anonfun$orDieWith$2(ZIO.scala:1163)
[info]   at zio.Cause.$anonfun$flatMap$2(Cause.scala:173)
[info]   at zio.Cause$$anon$2.failCase(Cause.scala:288)
[info]   at zio.Cause$$anon$2.failCase(Cause.scala:276)
[info]   at zio.Cause.loop$2(Cause.scala:221)
[info]   at zio.Cause.foldContext(Cause.scala:248)
[info]   at zio.Cause.foldLog(Cause.scala:276)
[info]   at zio.Cause.flatMap(Cause.scala:179)
[info]   at zio.ZIO.$anonfun$orDieWith$1(ZIO.scala:1163)
[info]   ...
[info]   Cause: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connexion refusée: localhost/[0:0:0:0:0:0:0:1]:35795
[info]   ...
[info]   Cause: java.net.ConnectException: finishConnect(..) failed: Connexion refusée
[info]   at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
[info]   at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
[info]   at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
[info]   at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
[info]   at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
[info]   at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
[info]   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
[info]   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[info]   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[info]   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[info]   ...
```

**Expected behaviour**

The test should always succeed.

In comparison, with version 0.0.5, it always succeeds. Checkout the branch `zio0.0.5` and run `sbt test` multiple times as well to compare.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux (Fedora)
 - Browser: N/A
 - Version: N/A

**Additional context**

For the record, this is a follow up of another issue https://github.com/zio/zio-http/issues/2742. I believe the two are not related though.

**Comment by gaeljw** [comment]
To be fair, this might be just highlighting an issue in another library than zio-http (pact4s maybe which is the main other library used in the tests).

I have no clue as how to investigate the issue though, any help appreciated.

**Comment by kyri-petrou** [comment]
>I have no clue as how to investigate the issue though, any help appreciated.

@gaeljw what about adding a small delay to the request, to ensure that the mocked server has finalized booting? You can do that by adding `.delay(500.millis)` or so [here](https://github.com/gaeljw/ziohttp3hanging/blob/b45558d89b18e7afe5dc831a562b1a05c86d3db3/src/test/scala/pact/client/MyWsClientPactTest.scala#L53C19-L53C41)

**Comment by gaeljw** [comment]
@kyri-petrou I already tried to add delay without success (not this way though, will try in doubt): the error still appears. I believe there's something else going on.

The server is supposed to be already available, the ScalaTest trait enforce it: https://github.com/jbwheatley/pact4s/blob/99a987da173d904f79486621a6ac7a3b0aeaffa4/scalatest-pact/src/main/scala/pact4s/scalatest/RequestResponsePactForger.scala#L38

Note that I also tried to write it as a ZIO Test and same results.

**Comment by gaeljw** [comment]
I confirm that even with a delay of 5 seconds, I do see errors with roughly the same apparition rate. There's something else.

**Comment by kyri-petrou** [comment]
Thanks, I'll look into it
/attempt #2902

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | 15 ZIO bounties | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxal9vjk0006lc0995w6jvcd/cancel-attempt) |

**Comment by Not-Aru** [comment]
We are experiencing a similar issue when using `ConnectionPoolConfig.Dynamic`. We started experiencing this when upgrading from RC6 to RC8. We have created a minimized reproducer here: 

```scala
object Reproducer extends ZIOAppDefault {
  private val clientLayer =
    (ZLayer.succeed(Config.default.copy(connectionPool = ConnectionPoolConfig.Dynamic(1, 512, 60.second))) ++ ZLayer
      .succeed(NettyConfig.defaultWithFastShutdown) ++
      DnsResolver.default) >>> Client.live

  private val url = URL.decode("http://0.0.0.0:8080/Test").toOption.get
  private val req = Request.post(url, Body.empty)

  private val routes =
    HttpApp(
      Routes(
        Method.POST / "Test" ->
          handler(Response.text("success"))
      )
    )

  val run: ZIO[Any with ZIOAppArgs with Scope, Throwable, Unit] = {
    for {
      _ <- Server.serve(routes).fork
      client <- ZIO.service[Client]
      _ <- ZIO.foreachParDiscard(0 to 400) { _ =>
        ZIO
          .scoped[Any] {
            client.request(req).flatMap(_.body.asArray)
          }
          .repeatN(100)
      }
    } yield ()
  }.provide(clientLayer, Server.default)
}
```

**Comment by kyri-petrou** [comment]
@Not-Aru I believe that's a separate issue. In fact, I think it might be resolved in the latest main branch. I managed to run your code without any issues, although i had to limit parallelism as it was opening too many connections to the server and netty started rejecting them.

Can you check whether the non-minimized issue you're facing is resolved in the latest snapshot? [3.0.0-RC8+22-5ea81ef6-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-http_2.13/3.0.0-RC8+22-5ea81ef6-SNAPSHOT/)

**Comment by kyri-petrou** [comment]
@gaeljw I think I found the source of your issue but at the moment I have no idea why it's happening (something to do with the DnsResolver).

As a workaround, define the URL like this in your test suite:

```scala
val url = s"http://0.0.0.0:${mockServer.getPort}"
```

One more thing, I see that you're overriding the netty version with something much much older than what zio-http is meant to be using. I would highly recommend if you have multiple dependencies using netty to use the `zio-http-shaded` package instead in order to avoid netty version conflicts

**Comment by gaeljw** [comment]
Wow, nice finding @kyri-petrou. Thanks for the work!

> I would highly recommend if you have multiple dependencies using netty to use the zio-http-shaded package instead in order to avoid netty version conflicts.

Nice, I didn't know about this one. I will check if there's a good reason to have a such old Netty version in my real project :)

**Comment by gaeljw** [comment]
For the record, on my laptop, the workaround is to use `localhost` rather than `0.0.0.0` :)
