### ISSUE TITLE
Add a hybrid `RequestStreaming` option that streams requests only if they're larger than X bytes

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-http#2908]
**Is your feature request related to a problem? Please describe.**
Currently, `zio-http` provides 2 config options for `RequestStreaming`:
1. `Disabled` (with a maximum number of bytes that the request can be before rejecting it)
2. `Enabled` (requests are streamed regardless of size)

For servers with low latency / high performance requirements, disabling streaming is a favourable option as it's more performant than streaming the requests. However, in some cases we might want to be able to be able to handle very large requests, so it would be good if `zio-http` provided an option to aggregate the response if it's less than X bytes, and stream it if it's larger than that

**Describe the solution you'd like**
Another case class extending `RequestStreaming` similar to `Disabled` but instead of failing the request it streams the bytes instead

**Describe alternatives you've considered**
Enabling streaming and using a middleware to batch the `ZStream`, but this doesn't perform as well as I would have hoped

**Comment by jdegoes** [comment]
/bounty $250 but has to ship soon because of final release coming up.

**Comment by abhi267266** [comment]
/attempt #2908

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz8f2qzr0002jt097l3hiqsk/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Ahmadkhan02** [comment]
/attempt #2908

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Ahmadkhan02) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Ahmadkhan02 | 1 bounty from 1 project | <div align="center">TypeScript, Jupyter Notebook</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz8f2qzr0002jt097l3hiqsk/cancel-attempt) |
