### ISSUE TITLE
HttpContentCodec drops an empty list field from resulting json so it is a cause for parsers to fail on the client side 

### ISSUE THREAD

**Issue by dobrynya** [zio/zio-http#2932]
HttpContentCodec drops an empty list field when serializing as JSON. So it causes parsing failures on the client side (ScalaJS with the latest Circe and ZIO-JSON. They report missing field details[0].

import zio.Chunk
import zio.http.codec.HttpContentCodec
import zio.schema.*

object HttpContentCodecTests:
  case class Master(details: List[Detail] = Nil)
  case class Detail(name: String)
  given Schema[Master] = DeriveSchema.gen
  given Schema[Detail] = DeriveSchema.gen

  val master = List(
    Master(details = Nil),
    Master(
      List(
        Detail("Detail 1")
      )
    )
  )

  private val codec: HttpContentCodec[List[Master]] = summon[HttpContentCodec[List[Master]]]

  def main(args: Array[String]): Unit = {
    val json                      = codec.defaultCodec.encode(master)
    println(json.asString) 
    // ecpected: [{"details": []},{"details":[{"name":"Detail 1"}]}]
    //  actual [{},{"details":[{"name":"Detail 1"}]}]
  }

**Comment by 987Nabil** [comment]
This is not a bug. See #2911 for workaround and further working on configuring this setting

If you can change your code in the frontend to use zio-schema, this should work as well and would be the preferred solution.
