### ISSUE TITLE
CorsConfig 'allowedHeaders' parameter generates an 'Access-Control-Expose-Headers' header 

### ISSUE THREAD

**Issue by wiki1000** [zio/zio-http#2941]
**Describe the bug**
in 3.0.0-RC9 CorsConfig 'allowedHeaders' parameter generates an Access-Control-Expose-Headers header in Http responses in lieu of the 'Access-Control-Allow-Headers' header. 

**To Reproduce**
Steps to reproduce the behaviour:

the CorsConfig is : 

```
val config: CorsConfig =
        CorsConfig(
            allowedOrigin = { case _ => Some(AccessControlAllowOrigin.All)}, 
            allowedMethods = AccessControlAllowMethods.All,
            allowedHeaders = AccessControlAllowHeaders.All,
        )
```
and after 

```
val routes = Routes(
        Method.GET / Root -> handler ( {
                println("get")
                Response.text("foo")
        } ),
        Method.OPTIONS / Root -> handler (
            (req: Request) => {
                println("option")
                
                Response.text("")  
                //.addHeader(AccessControlAllowHeaders.All)   // uncomment to solve the pb
            } )
    ) @@ cors(config)

def process = zio.http.Server
        .serve(routes)
        .provide(zio.http.Server.default)

```

The browser triggers a CORS error, which disappears if the header Access-Control-Allow-Headers
is added manually as proposed here in the example with the commented "addHeader" line. 

The following html   is provided to a Chrome Browser activating automatically CORS with the "Origin: null" header: 
```
<html>
<div
     hx-get="http://localhost:8080"
     hx-trigger="load"
     hx-swap="outerHTML">
    <p>Wait...</p>
</html>
```

**Expected behaviour**

The specified OPTIONS request response shall return among the response headers: 
`access-control-allow-headers: *

and not
`access-control-expose-headers: *

**Desktop (please complete the following information):**

 - OS: macOS 12.7.4
 - Browser Chrome 126.0.6478.127 (Official Build) (x86_64)
- ZIO 2.1.5
- zio-http 3.0.0-RC9
- openjdk 22.0.1

**Additional context**
The absence of access-control-allow-headers header is visible in the chrome console, and also in a curl request activating CORS:

```
curl  -v  -X OPTIONS --header "Origin: null"  http://localhost:8080
< HTTP/1.1 200 OK
< content-type: text/plain
< access-control-allow-origin: *
< access-control-allow-methods: *
< access-control-allow-credentials: true
< access-control-expose-headers: *
< date: Wed, 03 Jul 2024 19:01:14 GMT
< content-length: 0
```

**Comment by jgoday** [comment]
Hi @wiki1000, I was trying to reproduce your issue (successfully) and created following PR #2943.

**Comment by jdegoes** [comment]
/bounty $75

CC @jgoday

**Comment by jgoday** [comment]
/attempt #2941
The problem seems to be that the options routes, which handle the cors preflight request, were being added last, so the corsHeaders was not being correctly called 


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz8fk0xv000fl8091koqqhfm/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
