### ISSUE TITLE
Warning header loses original exception when that exception contains invalid-for-netty-headers characters

### ISSUE THREAD

**Issue by anqit** [zio/zio-http#2948]
**Describe the bug**
I am using zio-http and quill to build a REST service. I create a request handler via `Handler.fromFunctionZIO` that calls into my DB via a quill. In one instance, I forgot to `lift` a variable when creating the query (ie I did `id == someId` instead of `id == lift(someId)`. This causes quill to throw an `IllegalStateException` which is then treated as a fatal defect by the quill-created (I think? I don't think that's a relevant detail) ZIO instance. With `sandbox` turned on for my routes, the error handling mechanism attempts to turn the error into a warning response header. However, the error text for the `IllegalStateException` exception has a `\n` character in it, which fails netty's header validation (`verifyValidHeaderValueCharSequence` in `HttpHeaderValidationUtil.java` returns the index of the first `\n` in the string and not `-1`), causing the original error to be swallowed, and the warning response header to then contain the self-fulfilling meta Schrodinger's error `Validation failed for header 'warning'`. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on sandbox (`Server.serve(routes.sandbox)`)
2. Call a route handled by a ZIO via `Handler.fromFunctionZIO`
3. Have this ZIO fail fatally, and include a new line character in the exception error message

**Expected behaviour**
The original error is returned in the warning header.

**Comment by jdegoes** [comment]
/bounty $75 to only form proper warning headers (note that warning headers will probably be removed shortly).

**Comment by uurl** [comment]
/attempt #2948

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz8gdkp9000tm809w4slllv1/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
