### ISSUE TITLE
Support receiving `ServerSentEvents` in the (Endpoint) client

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2953]
Currently users can sent SSE with zio-http but not receive them. We should make this possible. For the Endpoint API as well as for the low level API. This means we need a way to decode an incoming stream of data to an SSE and integrate this in `Response` as well as in the EndpointAPI

**Comment by kyri-petrou** [comment]
Excuse my ignorance, but is client-sent SSE a thing? I thought SSE was meant to be the server sending back events in response to a `text/event-stream` request 🤔 I also can't find any reference to it anywhere

**Comment by 987Nabil** [comment]
But where is the server sending the events too? The client. And we need to be able to read them, no? Why should we not have parser logic that generates instances of `ServerSentEvent` in the Endpoint API client?

**Comment by kyri-petrou** [comment]
🤦‍♂️ I read the issue as "the server being able to receive SSE from a client"

**Comment by jdegoes** [comment]
/bounty $400 but has to come quickly due to final release.
