### ISSUE TITLE
Remove internal usage of warning header

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2955]
The warning header is currently used by zio-http. But is deprecated. I think errors should not add any info about stack traces or error messages in headers at all.
We should have error messages as opt-in in the body.
This should be a setting that can be set globally by a config, as well as by the user for a specific call to `Response.error` and similar methods.

**Comment by jdegoes** [comment]
/bounty $300 to remove warning headers and to have opt-in error messages in body.
