### ISSUE TITLE
Improve ZClient UX with regards to Scope

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2957]
Currently the Client requires a scope to close some kinds of bodies. The user has to wrap his code in `ZIO.scoped` to avoid memory leaks (which is also not documented well).
From a users perspective, this is not needed most of the time. He probably just wants to handle the body directly and clean up the request.
We should have a simpler API that does not require an explicit scope. We can let the user handover a function, that handles the response and after its execution we just clean up for the user.

This should not replace the current more powerful API, but should be promoted as the default in documentation.
For the current docs, we need to move away from using the global scope and should change most examples to this new API.

cc @kyri-petrou

**Comment by kyri-petrou** [comment]
/attempt #2957

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kyri-petrou) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kyri-petrou | &nbsp;&nbsp;&nbsp;23 ZIO bounties <br/> + 2 bounties from 1 project | <div align="center">Scala, Python, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz8gj9pt0004l409molox2i7/cancel-attempt) |
