### ISSUE TITLE
Simplify `EncoderDecoder`

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2958]
As shown in #2951 with `HttpContentCodec` we can generalize cases in `EncoderDecoder` that had special handling before.
We should investigate if more such simplifications can be made, since `EncoderDecoder` is an important part of the Endpoint API. A simple version would increase maintainability and readability. Also it would be nice, if we can reduce most use cases to some core functionality. For example, would it be possible to use `HttpContentCodec` for form data?

This is an issue that needs research and careful adjustments.

**Comment by jdegoes** [comment]
Note this will shortly be constrained by backward compatibility.
