### ISSUE TITLE
HTML Templates can't emit attributes without values

### ISSUE THREAD

**Issue by drue** [zio/zio-http#2963]
**Describe the bug**
Some HTML attributes, e.g. `required` on inputs, are boolean and do not have a value and should be rendered without an equals sign or value like this: `<input name="email" required>`

see: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

In Zio HTTP Templates, however, the `required` attribute is the same as all of the other attributes and takes a string value so it always emits an equals and quotes: `<input name="email" required="">`  which doesn't work in the browser I tried.

There are probably other HTML attributes like this and I know some popular front end libs/frameworks rely on these types of boolean attributes.

In Scalatags an empty string will render the attribute without equals or the value so maybe thats how you want to fix this, it certainly the easiest way to do so.

**To Reproduce**
render a template like `input(nameAttr:="email", requiredAttr:="")`

**Expected behaviour**
output   `<input name="email" required>`

**Comment by jdegoes** [comment]
/bounty $150 

cc @jgoday if you want to claim the bounty.

**Comment by jgoday** [comment]
/attempt #2963

Added PartialBooleanAttribute, so we can use boolean attributes without specifying a value (optionally).
```scala
input(typeAttr := "text", requiredAttr)
input(typeAttr := "text", requiredAttr := false)
```

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clz8gmqrj002jm809vyohy3u0/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
