### ISSUE TITLE
Query Parameters

### ISSUE THREAD

**Issue by mcnerneyd** [zio/zio-http#298]
Nothing particular wrong, and the answer is obvious - but we just spent a good bit of time trying to figure this out and it might be something worth including in your simple server example. It might make the experience a little less frustrating.

` case r @ Method.GET -> Root / "text" / name => Response.text(s"Hello ${name} - your account is " + r.url.queryParams.get("accountId").get.apply(0))`

(Unless there's a better way...)

Outside of that - loving the simplicity of this.

**Comment by whiskeylips** [comment]
FWIW, you can get a much cleaner (but still unsafe) bit of code with 
```r.url.queryParams("accountId").head```

Are there any contributor guidelines or should I just open a pull?

**Comment by whiskeylips** [comment]
https://github.com/dream11/zio-http/pull/309 this ticket is ready to close.
