### ISSUE TITLE
Release final version of ZIO HTTP 3.0

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#2982]
This must include:

 - closing or merging every open pull request after appropriate reviews and working with contributors or taking over their work
 - all important tickets whose completion would affect backward compatibility (some of these have separate bounties)
 - all final reviews and audits and last minute documentation fixes / additions that required for release

I will close this ticket at the end of August if no one takes it on.

**Comment by 987Nabil** [comment]
Nice time to be back from holidays 😀

**Comment by 987Nabil** [comment]
To make this clear: I make the 3.0 release my goal. I won't add an attempt tho, since there is an attempt limit and I don't want to mess with that.

**Comment by kyri-petrou** [comment]
@987Nabil just something I'd like to add re the final 3.0 release. I'm wondering whether we should make the configs in zio-http classes instead of case classes. Case classes are notoriously difficult at extending due to binary incompatibility, which makes me wonder whether we should make them into classes so that we can add more configurable properties in the future without breaking binary compatibility. WDUT?

**Comment by 987Nabil** [comment]
@kyri-petrou sounds reasonable. I know that coursier is using internally a lib, that is annotations based and generates constructors and copy methods based on versioning annotations on fields.
So if you add two fields with a new version, you get generated methods for the old version that do bot require these fields and for the new version methods with these two fields. Idk if that would work well with zio config. But maybe we can evaluate this

**Comment by kyri-petrou** [comment]
> coursier is using internally a lib, that is annotations based and generates constructors and copy methods based on versioning annotations on fields.

Just to clarify, does this lib that coursier uses works with classes or case classes? I'm guessing it works with classes right?

**Comment by sideeffffect** [comment]
Please keep using case classes. They are much much better for us users to work with.
The downsides can be mitigated by using https://github.com/com-lihaoyi/unroll

**Comment by 987Nabil** [comment]
@kyri-petrou https://github.com/alexarchambault/data-class

**Comment by nafg** [comment]
Why does Algora show a $10 bounty for this?
