### ISSUE TITLE
Remove HttpApp

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2984]
It is already deprecated and needs to be removed before 3.0.0

**Comment by varshith257** [comment]
/attempt #2984 

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;1 ZIO bounty <br/> + 5 bounties from 3 projects | <div align="center">TypeScript, Scala, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clz9kry9k000kl6097uq8ms1o/cancel-attempt) |
