### ISSUE TITLE
Integrate validation information for query params in generated OpenAPI spec

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2993]
Validation defined by zio-schema for query params is checked via impl. in https://github.com/zio/zio-http/pull/2991
But the information is not yet generated into the OpenAPISpec that is generated out of endpoint definitions

**Comment by 987Nabil** [comment]
This is blocked by #2991

**Comment by BijenderKumar1** [comment]
/attempt #2993

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/BijenderKumar1) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @BijenderKumar1 | 1 ZIO bounty | <div align="center"></div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzbws8gb000fk509mxiaxqjm/cancel-attempt) |
