### ISSUE TITLE
HTTP model for ContentType

### ISSUE THREAD

**Issue by ioleo** [zio/zio-http#3]
Create representation for common HTTP content types (see [RFC7231](https://tools.ietf.org/html/rfc7231#section-3)).

Put them inside `zio.http.ContentType`.

Aggregate issue to track progress. Please leave a comment which ones you take:
- [ ] `text/plain`
- [ ] `text/html`
- [ ] `text/csv`
- [ ] `text/xml`
- [ ] `application/json`
- [ ] `application/octet-stream`
- [ ] `application/x-www-form-urlencoded`

**Comment by jczuchnowski** [comment]
We probably need to give users the ability to define their own.

**Comment by vitaly-pushkar** [comment]
I'll work on this one as well
