### ISSUE TITLE
uuid PathCodec is broken in snapshot versions

### ISSUE THREAD

**Issue by narma** [zio/zio-http#3005]
My handler with definition
`Method.GET / "api" / uuid("entityId")` 
is stop matches and requests against `GET /api/$UUID` returns 404 instead of response

Reproducer, works with 3.0.0-RC9, but broken in latest snaphots.

```scala
//> using repositories sonatype:snapshots
//> using dep "dev.zio::zio-http:3.0.0-RC9+25-5aa5d9ec-SNAPSHOT"
/// 3.0.0-RC9 works
//>> using dep "dev.zio::zio-http:3.0.0-RC9"

import java.util.UUID
import zio.Chunk
import zio.http.codec.SegmentCodec

val c = SegmentCodec.uuid("p")
val v = UUID.randomUUID().toString()
val result = c.matches(Chunk("api", v), 1)
println(s"result = $result")
if (result == 1) then println("good") else println("not matches")
```

**Comment by varshith257** [comment]
/attempt #3005

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 5 bounties from 3 projects | <div align="center">TypeScript, Go</div> | <div align="center">﹟8970</div> | [Cancel attempt](https://console.algora.io/api/bounties/clziw4v010002ky0969lmedrq/cancel-attempt) |
