### ISSUE TITLE
Default `HttpContentCodec` implicit resolution is broken

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#3023]
Calling this
```scala
 val  endpoint =
    (Endpoint(RoutePattern.GET / "resources") ?? Doc.p("Creates a resources"))
      .out[String](MediaType.application.json)
```
Results in a content type of `*/*`, when called with accept `*/*`. A quick check revealed, that the default implicit `HttpContentCodec.fromSchema` was not used.

We need a test that makes sure, that this implicit is used by default and eliminate the implicit with higher prio.

**Comment by asr2003** [comment]
/attempt #3023

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/asr2003) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @asr2003 | &nbsp;&nbsp;&nbsp;2 ZIO bounties <br/> + 2 bounties from 2 projects | <div align="center">JavaScript, Go, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0foxaks000ll4039pe5lted/cancel-attempt) |
