### ISSUE TITLE
Improvements for HttpContentCodec

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#3029]
I think we can do the following, to avoid allocating to many codecs that are more or less all the same.

1. The different schema based constructors of `HttpContentCodec` should cache the crated instances. This will reduce the amount of codecs in the running server and also improve the efficiency of the `lookupCache`
2. Because of 1. we might want to use `ConcurrentHashMap`. I am not sure if it is needed, since a concurrent update would only lead to a cache miss. Might be okay to just keep it as is.
3. Make `HttpContentCodec` a sealed trait and have a `Filtered` subtype, that keeps a view on an actual `HttpContentCodec` instance. This way, when we call `only` to limit the codec to a certain media type, we can still use the `lookupCache` of the original codec.

**Comment by 987Nabil** [comment]
/attempt #3029

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/987Nabil) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @987Nabil | &nbsp;&nbsp;&nbsp;80 ZIO bounties <br/> + 1 bounty from 1 project | <div align="center">Scala</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0foxmtw000ejq031pcaz2g7/cancel-attempt) |

**Comment by varshith257** [comment]
/attempt #3029

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 6 bounties from 4 projects | <div align="center">TypeScript, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0foxmtw000ejq031pcaz2g7/cancel-attempt) |
