### ISSUE TITLE
[OpenAPI] The generator doesn't strip the `description` of a type when the `description` comes from the Javadoc of the type

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-http#3047]
With the following code:
```scala
/**
 * This is the Input documentation
 */
final case class Input(a: String)

val testEndpoint = 
  (Endpoint(RoutePattern.POST / "test") ?? Doc.p("This is my 'POST /test' endpoint doc"))
    .in[Input]
    .out[String](mediaType = MediaType.application.json, doc = Doc.p("this is the output doc"))

val spec: String =
  OpenAPIGen.fromEndpoints(
    title = "This is my OpenAPI doc title",
    version = "0.0.0",
    endpoints = List(testEndpoint)
  ).toJson
```

The spec will contain the following `description` for the Input type:
```json
"description": "/**\n     * This is the Input documentation\n     */"
```
While it should contain:
```json
"description": "This is the Input documentation"
```

Why is it an issue? 
Because when we then generate a TS SDK out of the generated OpenAPI spec, the generated code doesn't compile.

@geeeezmo Do you want to give this issue a try?

**Comment by 987Nabil** [comment]
~If there is both, I am not sure what the right behavior is. Should doc override or add?~
Got it wrong. It is about sanitizing the string. I am not sure, if it should be done here or in schema

**Comment by geeeezmo** [comment]
@guizmaii on what branch does this happen? I've run the test on `main` and the annotation doesn't appear in the generated spec.
