### ISSUE TITLE
[OpenAPI] `Map` fields are generating incorrect OpenAPI spec

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-http#3048]
This Endpoint definition
```scala
/**
 * This is the Input documentation
 */
final case class Input(headers: Map[String, String], body: String)

val testEndpoint = 
  (Endpoint(RoutePattern.POST / "test") ?? Doc.p("This is my 'POST /test' endpoint doc"))
    .in[Input]
    .out[Input](mediaType = MediaType.application.json, doc = Doc.p("this is the output doc"))

val spec: String =
  OpenAPIGen.fromEndpoints(
    title = "This is my OpenAPI doc title",
    version = "0.0.0",
    endpoints = List(testEndpoint)
  ).toJson

```
generates this OpenAPI spec for the `Input` type:
```json
      "Input": {
        "type": "object",
        "properties": {
          "body": {
            "type": "string"
          }
        },
        "additionalProperties": {
          "type": "string"
        },
        "required": [
          "headers",
          "body"
        ]
      },
```

The `headers` field is missing from the `properties` object and seems to be instead replaced with `additionalProperties` 🤔

@geeeezmo Do you also want to give this issue a try?

**Comment by hochgi** [comment]
It's not "replaced", since `additionalProperties` is how open dictionaries (maps) with string keys should be defined.
It should have been:
```json
      "Input": {
        "type": "object",
        "properties": {
          "body": {
            "type": "string"
          },
          "headers":{
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        },
        "required": [
          "headers",
          "body"
        ]
      },
```

**Comment by guizmaii** [comment]
@hochgi Do you have an idea where this bug can come from in zio-http code? 🤔

**Comment by hochgi** [comment]
@guizmaii I would take a look at the conversion from `JsonScema` to `SerializableJsonSchema`. But that's just a guess...

**Comment by hochgi** [comment]
@guizmaii I think my guess was in the right direction. take a look at:

https://github.com/zio/zio-http/blob/main/zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala#L1243-L1256

Also, IIUC, a `JsonSchema.Object` can have either `properties` & `required` (closed dictionary - AKA case class) or `additionalProperties` (open dictionary - AKA Map). It doesn't make sense to have both.
But it is modeled as:

https://github.com/zio/zio-http/blob/main/zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala#L1210-L1214
```scala
  final case class Object(
    properties: Map[java.lang.String, JsonSchema],
    additionalProperties: Either[Boolean, JsonSchema],
    required: Chunk[java.lang.String],
  ) extends JsonSchema
```

Perhaps we should have a different model for that:
```scala
sealed abstract class Object extends JsonSchema { … }

final case class ClosedProduct(
  properties: Map[java.lang.String, JsonSchema],
  required: Chunk[java.lang.String]
) extends JsonSchema.Object

final case class OpenProduct(
  additionalProperties: Either[Boolean, JsonSchema]
) extends JsonSchema.Object
```

Not sure how much effort would be to re-model this properly, but it should render such bugs impossible

Edit:
Now that I think about it, the `Either[Boolean, JsonSchema]` isn't needed if we re-model.
It can just be `JsonSchema`

**Comment by guizmaii** [comment]
@987Nabil An opinion on @hochgi above suggestion? 🤔

**Comment by 987Nabil** [comment]
That would not be a correct modeling of the spec. There is nothing that says the two fields are mutually exclusive. Neither in json Schema nor open API.

**Comment by hochgi** [comment]
@987Nabil in openAPI spec you are 100% spot on. But in codegen we can be more restrictive, and not allow it.
How would we even generate code for:
```yaml
schemas:
  SomeObject:
    type: object
    required:
      - foo
      - bar
    properties:
      foo:
        type: string
      bar:
        type: integer
        format: int32
      additionalProperties:
        type: string
```
perhaps something weird like:
```scala
object SomeObject {
  def apply(foo: String, bar: Int, additionalProperties: Map[String, String]): Map[String, Json] =
    Json.Obj(
      Chunk(
        "foo" -> Json.Str(foo),
        "bar" -> Json.Num(foo)
      ) ++ additionalProperties.map { case (k, v) => k -> Json.Str(v) }
    )

  def unapply(obj: Map[String, Json]): Option[(String, Int, Map[String, String])] =
    for {
      foo <- obj.get("foo").collect { case Json.Str(value) => value }
      bar <- obj.get("bar").collect { case Json.Num(value) => Try(value.intValueExact()).toOption }.flatten
      additionalProperties = obj.collect { case (k, Json.Str(v)) if k != "foo" && k != "bar" => k -> v }
    } yield (foo, bar, additionalProperties)
}
```

The thing is as I think about this, is that scala and OpenAPI have different expressive capabilities, and that any code generator should only support the commonalities that can be expressed in both.

**Comment by guizmaii** [comment]
I don't really understand this code yet but we can see that the `nestedMap` field from the tests (which is a field containing a `Map[String, Recursive]` has disappeared from the `properties` and is probably what's inside the `additionalProperties`.
All the other fields (`nestedSet`, `nestedEither`, etc.) are correctly into the `properties`

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/a76c9b26-a3f3-4305-a4ba-ffdbd3b19da3">

**Comment by 987Nabil** [comment]
To make this short. The schema object fulfills the spec. And is not used for code gen only. The code gen can ofc make runtime checks and throw exceptions, if it is not possible to generate endpoints based on the open api schema.
But the issue is also the other way: code -> open api. There is something not quite right here.

**Comment by hochgi** [comment]
@987Nabil yeah, that makes perfect sense. I guess such spec can never be derived though... right? It's only if someone declares an endpoint and manually building the schema...

**Comment by guizmaii** [comment]
> But the issue is also the other way: code -> open API

Yup, that's what I'm using to generate a TypeScript SDK 🙂
That's why I need to fix this issue. The current TS generated code is incorrect

**Comment by guizmaii** [comment]
Ok, I've isolated where the issue comes from.
It comes from the `JsonSchema.Object::addAll` method: https://github.com/zio/zio-http/blob/544adf087c2d393d08f208b60949c9ac02a53b95/zio-http/shared/src/main/scala/zio/http/endpoint/openapi/JsonSchema.scala#L1215-L1226

The `case Object(properties, additionalProperties, required) =>` is probably too generic.
I see a lof of ifs in other places of the code when pattern matching on `JsonSchema.Object`.
These kind of ifs:
```scala
// Code in `EndpointGen`

  case JsonSchema.Object(properties, additionalProperties, _)
          if properties.nonEmpty && additionalProperties.isRight =>
          
 // later in the code
   case obj @ JsonSchema.Object(properties, additionalProperties, _) if additionalProperties.isLeft =>
 
 // later in the code
  case JsonSchema.Object(_, _, _)                                                                  =>
        // properties.isEmpty && additionalProperties.isRight
```

🤔


**Edit:**
It was indeed the issue. The fix is waiting for the CI to pass.
See https://github.com/zio/zio-http/pull/3049
