### ISSUE TITLE
Revise usages of `lazy val`s

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio-http#3051]
There are a quite a few places where we use `lazy val` unnecessarily. Lazy vals come with a small overhead so we should use them only for cases that we either absolutely have to (e.g., recursive methods) or when:
1. A method is computationally expensive. If it's cheap we should use `def` instead
2. The method _might_ be called, and if called it'll be called 2+ times. If we're certain the method will be called we should use `val` instead.

**Comment by 987Nabil** [comment]
/attempt #3051

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/987Nabil) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @987Nabil | &nbsp;&nbsp;&nbsp;77 ZIO bounties <br/> + 1 bounty from 1 project | <div align="center">Scala</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0cl0hpo000eij038ifaqd3x/cancel-attempt) |
