### ISSUE TITLE
OpenAPI generation doesn't work for case classes with >22 fields

### ISSUE THREAD

**Issue by myazinn** [zio/zio-http#3064]
**Describe the bug**
I'm using `3.0.0-RC9` version.
When generating an OpenAPI from schema which describes a case class with >22 fields, invalid specification is produced which generates an error in SwaggerUI.

**To Reproduce**
Here's the code snippet
```scala
import zio._
import zio.http._
import zio.http.endpoint.Endpoint
import zio.http.endpoint.openapi.OpenAPIGen
import zio.schema.{ DeriveSchema, Schema }

object HttpApp extends ZIOAppDefault {

  override def run: ZIO[Any, Any, Any] =
    ZIO.debug(OpenAPIGen.fromEndpoints(Endpoint(Method.GET / "foo").out[BigModel]).toJsonPretty)

  private implicit lazy val bigModelSchema: Schema[BigModel] = DeriveSchema.gen

  final case class BigModel(
    f1: Boolean,
    f2: Boolean,
    f3: Boolean,
    f4: Boolean,
    f5: Boolean,
    f6: Boolean,
    f7: Boolean,
    f8: Boolean,
    f9: Boolean,
    f10: Boolean,
    f11: Boolean,
    f12: Boolean,
    f13: Boolean,
    f14: Boolean,
    f15: Boolean,
    f16: Boolean,
    f17: Boolean,
    f18: Boolean,
    f19: Boolean,
    f20: Boolean,
    f21: Boolean,
    f22: Boolean,
    f23: Boolean
  )

}
```
**Actual behaviour**
The code prints specification without components schemas
```json
{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "",
    "version" : ""
  },
  "paths" : {
    "/foo" : {
      "get" : {
        "responses" : {
          "200" : 
            {
            "content" : {
              "application/json" : {
                "schema" : 
                  {
                  "$ref" : "#/components/schemas/BigModel"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    
  }
}
```

**Expected behaviour**
It should print the referenced schema. For example, here's what it prints if we leave only 2 fields (I don't want to include result for 22 fields since it's too large)
```json
{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "",
    "version" : ""
  },
  "paths" : {
    "/foo" : {
      "get" : {
        "responses" : {
          "200" : 
            {
            "content" : {
              "application/json" : {
                "schema" : 
                  {
                  "$ref" : "#/components/schemas/BigModel"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "BigModel" : 
        {
        "type" : 
          "object",
        "properties" : {
          "f1" : {
            "type" : 
              "boolean"
          },
          "f2" : {
            "type" : 
              "boolean"
          }
        },
        "required" : [
          "f1",
          "f2"
        ]
      }
    }
  }
}
```

**Screenshots**
<img width="1714" alt="image" src="https://github.com/user-attachments/assets/8f84877e-d6ba-4dde-9197-45798963ca7e">

**Additional context**
The issue seems to be in `zio.http.endpoint.openapi.OpenAPIGen#nominal` method. When dealing with case classes with > 22 fields, zio-schema wraps `GenericRecord` into `Transform` class (idk why), which prevents it from matching and just skips it. Both Scala 2 and Scala 3 versions are affected

**Comment by narma** [comment]
/attempt #3064

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/narma) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @narma | 1 ZIO bounty | <div align="center">Scala, Ruby, <br />Clojure & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0fow6rp000cjt0322pzdt7n/cancel-attempt) |
