### ISSUE TITLE
Content-Length always reset to 0 for HEAD requests

### ISSUE THREAD

**Issue by adamw** [zio/zio-http#3080]
For a HEAD requests, where the content-length is (dynamically) set to represent whatever would be returned for a GET request, it's always reset to 0. Consider:

```scala
//> using scala 3
//> using lib dev.zio::zio-http:3.0.0-RC10

import zio.ZIOAppDefault
import zio.http.{Body, Header, Headers, Method, Request, Response, Routes, Server, Status, handler}

object ZioDemo extends ZIOAppDefault {
  val routes =
    Routes(
      Method.HEAD / "test" -> handler { (req: Request) =>
        Response(
          status = Status.Ok,
          headers = Headers(Header.ContentLength(123))
        )
      }
    )

  def run = Server.serve(routes).provide(Server.default)
}
```

Test:

```
[~]% curl -X HEAD -v localhost:8080/test
> HEAD /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< date: Mon, 02 Sep 2024 13:57:58 GMT
< content-length: 0
<
```

This used to work with RC8. For more details on content-length and HEAD requests, see [here](https://stackoverflow.com/questions/3854842/content-length-header-with-head-requests).

Blocks https://github.com/softwaremill/tapir/pull/4007.

**Comment by 987Nabil** [comment]
This is probably due to automatic content length handover while request creation. Might be zio-http or netty.

**Comment by kyri-petrou** [comment]
Something was changed in a recent version of Netty that required the content length to match the actual length of the response, otherwise it would kill the connection without sending a response.

I'm not sure if this also applies to HEAD requests, I'll check tomorrow

**Comment by 987Nabil** [comment]
Probably not. I mean that would not make sense
