### ISSUE TITLE
Unify naming for configs

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#3081]
Currently some config leaves are `kebab-case` and some are `camelCase`.

I see three options
1. All kebab
2. All camel
3. Be agnostic and accept both (I think I'd prefer this one)

**Comment by kyri-petrou** [comment]
I think we should stick with (1) since it's also compatible with bash naming OOTB and perhaps add support for fallback to camelCase in ZIO directly

**Comment by 987Nabil** [comment]
I am fine with doing it in zio directly, but I think it is okay to be graceful

**Comment by mh-lamine** [comment]
/attempt #3081

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0mm7os4001cky03zpw8ldlk/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by 987Nabil** [comment]
@mh-lamine we agreed on kebab-case for word spacing. Since this needs to be done asap, please open PR today.
