### ISSUE TITLE
Routing fails with 404 in the presence of Text segments with different names

### ISSUE THREAD

**Issue by olivierdeckers** [zio/zio-http#3086]
**Describe the bug**
tapir path parameters are modelled as Text segments. Separate subtrees are created based on the value in the Text segment, and the routing algorithm picks one of them without backtracking to the other if there is no match.

**To Reproduce**
Steps to reproduce the behaviour:
I'm using zio-http as the backend for serving some tapir endpoints. There are two paths:
/path/{id}/one
/path/{meterid}/two
This is represented in the routing tree as two different subtrees. The matching algorithm will match with the first subtree it encounters. If that subtree fails to match the request (last segment not matching), the routing does not fallback to the second subtree and instead returns a 404.

**Expected behaviour**
The two paths should be modeled as the same subtree, as they are both Text segments. Their name should not matter.
Otherwise backtracking logic should be added, which would make the routing slower.

**Additional context**
version: 3.0.0-RC8

**Comment by jdegoes** [comment]
I think you should try RC10.

**Comment by olivierdeckers** [comment]
I tested with the RC10, and that fixes the problem. Thanks!
