### ISSUE TITLE
Provide easy default layer for `TestServer`

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#3094]
Currently the docs give this example list of layers to provide
```scala
}.provideSome[Client with Driver](TestServer.layer)
  }.provide(
    ZLayer.succeed(Server.Config.default.onAnyOpenPort),
    Client.default,
    NettyDriver.customized,
    ZLayer.succeed(NettyConfig.defaultWithFastShutdown),
  )
```

This is unnecessary complex. To just run a simple test, we should have something like `TestServer.simple` of type `ZLayer[Any, Nothing, TestServer & Server]`, that gives a good default for most tests.

**Comment by jdegoes** [comment]
/bounty $50 for fix, test case, and documentation.
