### ISSUE TITLE
Default encoding of `Enpoint.outStream[X]` should be JSON array, or the Content Type should be `application/json-seq`

### ISSUE THREAD

**Issue by gregor-rayman** [zio/zio-http#3113]
**Is your feature request related to a problem? Please describe.**
Conceptually when an endpoint returns a list of X, it is the same as when it returns a ZStream[_, _, X]. Currently the default output encoding for `.out[X]` is an JSON array. For `.outStream[X]` it is however a not separated collection of JSONs. The `Content-Type` in the response is `application/json`, correct one would be `application/json-seq`.

**Describe the solution you'd like**
Either the data should be returned as a JSON array, so prefixed with `[`, separated by `,` and terminated by `]`, or the `Content-Type` should be `application/json-seq`. I'd prefer the array, because that makes the change change from `.out[List[X]]` to `.outStream[X]` an internal change of the server, without the need to change the clients.

**Describe alternatives you've considered**
A viable solution currently (RC10) is to provide custom codes for endpoints with `.outStream[X]` stream outputs.

**Comment by jdegoes** [comment]
/bounty $125 to make `.outStream[X]` return a JSON array, and a test case to prove it.

**Comment by gregor-rayman** [comment]
/attempt #3113

Implement an encoder with the data interspersed with `[`, `,`, `]`

For the decoder parse the array incrementally, not as a single JSON array

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm0wd5qm2000lla03y61itpr1/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
