### ISSUE TITLE
Multipart boundary generated by Body.fromMultipartFormUUID cannot be parsed by server

### ISSUE THREAD

**Issue by countfloyd** [zio/zio-http#3117]
Have an ZClient calling another zio-http server endpoint with a multipart form and a auto-generated boundary:

```
body <- Body.fromMultipartFormUUID(
      Form(
        FormField.Simple("name", name),
        FormField.streamingBinaryField("upload", upload, MediaType.application.`octet-stream`, None, Some(fileName)),
      )
)
```

This generates a boundary of '(((random-uuid)))'. Passing this request with this boundary format is not parsed correctly by the zio-http server at the other end. I get an error:

```
400 POST /api/attachments 1194ms
timestamp=2024-09-09T22:58:40.380718Z level=INFO thread=#zio-fiber-940828076 message="Http request served" location=XXX.Main.run file=Main.scala line=81 method=POST duration_ms=1134 url=/api/attachments response_size=126 status_code=400 response="{"name":"MalformedBody","message":"Malformed request body failed to decode: Missing multipart/form-data field (Success(name)"}" content-type="multipart/form-data; boundary=(((71126f2f-0619-41dc-8914-86b0a1b318f0)))"
```

If I specify my own boundary value (i.e. --random-uuid), it works ok.

**Comment by varshith257** [comment]
/attempt #3117

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;3 ZIO bounties <br/> + 7 bounties from 4 projects | <div align="center">TypeScript, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0wczayv0002ml03sfmx9yql/cancel-attempt) |
