### ISSUE TITLE
Optional Codecs are required in OpenApi

### ISSUE THREAD

**Issue by brndt** [zio/zio-http#3127]
When using `optional` encoding for query, the resulting OpenApi UI enforces you to pass these query params as required ones.

<img width="1418" alt="Screenshot_2024-09-10_at_21 37 50" src="https://github.com/user-attachments/assets/dd7b557f-e112-48e7-b91f-0e7c564c609c">

**Comment by jdegoes** [comment]
/bounty $125 for fixes and test cases for ALL optional elements (not just query parameters).
