### ISSUE TITLE
It would be great if one could specify more than 8 error types using the outErrors method of Endpoint

### ISSUE THREAD

**Issue by countfloyd** [zio/zio-http#3130]
Currently, the Endpoint.outErrors method can only accept up to 8 error types. Would be great to be able to add more. Right now, I have 10. Is there another way to do this without generating a huge intersection type for errors?

**Comment by jdegoes** [comment]
/bounty $75 to increase arity to 16.

**Comment by varshith257** [comment]
/attempt #3130

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;4 ZIO bounties <br/> + 9 bounties from 6 projects | <div align="center">TypeScript, Go</div> | <div align="center">﹟3141</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm17xsujq000xjt03eni0xt7e/cancel-attempt) |
