### ISSUE TITLE
Adding ?? Doc.p(...) to an Endpoint with a tag overwrites the tag

### ISSUE THREAD

**Issue by countfloyd** [zio/zio-http#3131]
Consider an endpoint:
```
  val testEndpoint =
    Endpoint(RoutePattern.POST / "api" / "test")
      .tag("My Tag")
      .in[String]
      .out[String]
      ?? Doc.p("Endpoint documentation")
```

If I look at the OpenAPI docs generated for this endpoint, the tag is missing. I think the ?? Doc call is overwriting the tag since the tag seems to be part of the endpoint's documentation.

**Comment by geeeezmo** [comment]
You can do `Doc.p("...").tag("My Tag")`, and that would keep the tag, but then another thing comes up:
the `description` for the endpoint gets replaced with `- My Tag\n`, and the path also gets the same value in `description` 🤔

**Comment by jdegoes** [comment]
/bounty $75 for fix and test cases.

These operators should all be "append-only", i.e. they do not discard existing information.
