### ISSUE TITLE
Using a handled route with error handling functions causes a ClassCastException

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-http#3134]
**Describe the bug**

Affected versions: 3.0.0-RC5+ **including 3.0.0**

This [pr](https://github.com/zio/zio-http/commit/7458b6f0ee29a2e6f9c03e61789ca8c4241c51d1#diff-9647adc8988f3499f424096635a41c9c07904f9cb3e7ed3ead01fb0c227307a1R66) introduced changes to the error handling behaviour, allowing error handling functions to be used together with routes that don't fail / use the failure channel for responses.

Problem is that the type signature lies for handled handlers. A Handled route will not fail with a `Cause[Nothing]`, but rather with a `Cause[Response]`. This can cause ClassCastExceptions at runtime.

For example trying to use `.handleErrorCauseZIO(c => ZIO.logInfo(Try(c.squash).toString()).as(Response.ok))` with a handled route will log a `class zio.http.Response cannot be cast to class scala.runtime.Nothing$`.

Root cause are this [line](https://github.com/zio/zio-http/blob/main/zio-http/shared/src/main/scala/zio/http/Route.scala#L76) which casts the cause to a `Cause[Nothing]`.

And [this](https://github.com/zio/zio-http/blob/main/zio-http/shared/src/main/scala/zio/http/RoutePattern.scala#L73) constructor of a Route using a RoutePattern and a handled handler. This function has an unused type parameter [Err] with ends up being `Nothing` unless explicitly specified.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a simple zio-http application:
```scala
package example

import zio._
import zio.http._
import scala.util.Try

object Main extends ZIOAppDefault {

  val routes = Routes(
    Method.GET / "foo" -> handler { _: Request =>
      ZIO.fail(Response.ok)
    }
  ).handleErrorCauseZIO(c => ZIO.logInfo(Try(c.squash).toString()).as(Response.ok))

  def run: ZIO[Environment with ZIOAppArgs with Scope,Any,Any] =
    Server.serve(routes).provideLayer(Server.default)

}
```
2. Run it
3. Send a http get request to http://localhost:8080/foo
4. See error in the logs

**Expected behaviour**
No Classcast exceptions should happen at runtime. I suspect one of two solutions would fit here:
1. Error type of handled routes should be Cause[Response] not Cause[Nothing].
2. When using error handling operators on Handled routes we should strip all failures and only leave interrupts and defects to be logged. IMO this has better ergonomics than options (1) and is what I would prefer here.

**Additional Notes**

Looks like this issue was already reported here https://github.com/zio/zio-http/issues/2580#issuecomment-2139543267

**Comment by jdegoes** [comment]
/bounty $125 for fix and test case (may be duplicate).

**Comment by mschuwalow** [comment]
/attempt #3134

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mschuwalow) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mschuwalow | 1 ZIO bounty | <div align="center">Scala, TypeScript, <br />Nix & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm17x5qrb000zl5033pmt7jnd/cancel-attempt) |
