### ISSUE TITLE
Create a OpenAPI to Endpoint Code Gen sbt plugin

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#3180]
- Needs to have a config to switch between automatic (on file change) and manual generation
- config for file/folder path(s) of OpenAPI files
- config for package prefix
- setting to handover a global openapi config
- setting for openapi config based on a sbt file filter

**Comment by rohitsdev4** [comment]
/attempt #3180

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm39jr2b1001imb03kx91iphi/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by rohitsdev4** [comment]
Hi @987Nabil 
I've uploaded the project addressing this issue. You can find it https://github.com/rohitsingh8885882/Projects.git

Please review the changes and let me know if any further adjustments are needed.

Thanks!
/claim #3180

**Comment by hochgi** [comment]
@rohitsingh8885882 I believe the intent was to use zio-http-gen, not openapi-generator (there's already another sbt plugin doing that...)
Probably also to be another module in this repo.

If this doesn't converge, I would also like to take a shot at this.
So I'll get in line to
/attempt #3180
 as well.


<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hochgi) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hochgi | 4 ZIO bounties | <div align="center">Scala, Java</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm39jr2b1001imb03kx91iphi/cancel-attempt) |

**Comment by WeetHet** [comment]
So, the issue was closed, the bounty was claimed but the plugin was never published and the instructions on the website are incorrect. How is this okay? Can we reopen this issue until the plugin is published properly?

**Comment by hochgi** [comment]
@WeetHet you can look at test examples on how to set this up: https://github.com/zio/zio-http-sbt/tree/main/zio-http-gen-sbt-plugin/src/sbt-test
As an outside contributor, there's not much I could do regarding publishing of this, I'm not authorized obviously.
But you could just inline the plugin sources in your build.

At the time of implementing this, I worked at a company using this, and this is exactly what we did.
