### ISSUE TITLE
Compilation error trying to `implement` `Endpoint` via a `Handler` in `3.0.1`

### ISSUE THREAD

**Issue by anqit** [zio/zio-http#3185]
**Describe the bug**
Recently upgraded `zio-http` from `3.0.0-RC8` to `3.0.1`
Previously, I could do the following:
```scala
val endpoint: Endpoint[...] = ...
val handler: Handler[...matching endpoint input and output] = ...
val route = endpoint.implement(handler)
```
This is now failing to compile with:
```shell
[error] 77 |            e.implement(h)
[error]    |                        ^
[error]    |Found:    (h : zio.http.Handler[R, MyErrorType, I, O])
[error]    |Required: I => zio.ZIO[R, MyErrorType, O]
```

I can use a workaround though, but it's not as nice as previously working functionality:
```scala
val endpoint: Endpoint[...] = ...
val handler: Handler[...matching endpoint input and output] = ...
val route = endpoint.implement(handler.apply)
```

**Expected behaviour**
ability to implement endpoints using handlers as before

**Comment by 987Nabil** [comment]
We renamed `implement` to `implementHandler`. The new `implement` takes an effect as an input.
