### ISSUE TITLE
Parsing a Basic Authorization header fails if password contains ':'

### ISSUE THREAD

**Issue by camarena** [zio/zio-http#3193]
The method `zio.http.Header.Authorization.parseBasic` fails with `Basic Authorization header value is not in the format username:password` if the password contains a ':'. `partsOfBasic.length` will be greater than 2 in that case.

```
    private def parseBasic(value: String): Either[String, Authorization] = {
      try {
        val partsOfBasic = new String(Base64.getDecoder.decode(value)).split(":")
        if (partsOfBasic.length == 2) {
          Right(Basic(partsOfBasic(0), Secret(partsOfBasic(1))))
        } else {
          Left("Basic Authorization header value is not in the format username:password")
        }
      } catch {
        case _: IllegalArgumentException =>
          Left("Basic Authorization header value is not a valid base64 encoded string")
      }
    }

```

**Comment by mobley-trent** [comment]
/attempt #3193

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mobley-trent) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mobley-trent | &nbsp;&nbsp;&nbsp;1 ZIO bounty <br/> + 10 bounties from 4 projects | <div align="center">Python, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm39j1did000smb03v9ibuq8m/cancel-attempt) |
