### ISSUE TITLE
cannot find zhttp-test in maven central

### ISSUE THREAD

**Issue by slswee** [zio/zio-http#321]
In README, the setup example via build.sbt shows 
`libraryDependencies += "io.d11" %% "zhttp-test" % "[version]" % Test`

However, cannot find zhttp-test package in maven central. 
https://search.maven.org/search?q=zhttp-test

**Comment by terdong** [comment]
Temporarily, add the following to build.sbt 
```
resolvers += "Sonatype OSS Snapshots s01" at "https://s01.oss.sonatype.org/content/repositories/snapshots" 
libraryDependencies += "io.d11" %% "zhttp-test" % "1.0.0.0-RC17+37-1c8ceea7-SNAPSHOT" % Test
```
In my case, it works.

**Comment by sumawa** [comment]
zhttp-test are available in maven central
https://search.maven.org/search?q=zhttp-test
