### ISSUE TITLE
Generating API fails when there is a recursive data type

### ISSUE THREAD

**Issue by dobrynya** [zio/zio-http#3256]
I get a java.lang.StackOverflowError when trying to generate open API documentation.

**To Reproduce**
```scala
import zio.*
import zio.http.*
import zio.http.codec.Doc
import zio.http.endpoint.Endpoint
import zio.http.endpoint.EndpointMiddleware.None
import zio.http.endpoint.openapi.*
import zio.schema.*

case class TreeNode(id: Int, children: List[TreeNode]) derives Schema

val tree = TreeNode(1, List(TreeNode(2, List(TreeNode(3, Nil))), TreeNode(4, Nil)))

val endpoint: Endpoint[Unit, Unit, ZNothing, TreeNode, None] =
  Endpoint(Method.GET / "tree").out[TreeNode](Doc.p("Returns a tree"))

object TreeApi extends ZIOAppDefault:
  private val openAPI = OpenAPIGen.fromEndpoints(endpoint)

  override def run: ZIO[ZIOAppArgs & Scope, Any, Any] =
    (Routes(endpoint.implement(_ => ZIO.succeed(tree))) ++ SwaggerUI.routes("/api/swagger-ui", openAPI))
      .serve
      .provide(Server.defaultWithPort(8088))
```

**Expected behaviour**
Documentation should be generated and published without errors.

**Additional context**
An application without generating open API documentation works as expected.
Environment: JVM 17, scala 3.6.2, zio 2.1.13, zio-http 3.0.0-RC9 (I cannot use v. 3.0.1 as my scalajs code cannot be compiled)

**Comment by 987Nabil** [comment]
@dobrynya since your Scala js can't compile with 3.0.1, can you also create an issue for that?

**Comment by dobrynya** [comment]
> @dobrynya since your Scala js can't compile with 3.0.1, can you also create an issue for that?
Hi Nabil

I created an [issue](https://github.com/zio/zio-http/issues/3142) ealier for inability to compile my code.
At this very moment upgrading to zio-http 3.0.1 also does not help to compile :( So I wait for the next release to try again. 

Nevertheless upgrading to zio-http 3.0.1 in a separate project resolves this issue. So I thing we may close this ticket.
