### ISSUE TITLE
Document usage of ZIO Http Test API

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#333]
The new ZIO Test module can be used to test ZIO Http applications.
Should add some documentation about how to use the testing module.

**Comment by JeroenKnoef-TomTom** [comment]
Is the `zhttp-test` module actually available somewhere? The [example](https://dream11.github.io/zio-http/docs/index#testing) uses [this class](https://github.com/dream11/zio-http/blob/release/next/zio-http-test/src/main/scala/zhttp/test/test.scala). Just for testing, I included that class in my project so it works but that's no solution of course. Thanks for clarifying.

**Comment by tusharmath** [comment]
I don't think we need the test module anymore. We should be able to simply call `Http` as a function, passing a request and expecting a ZIO of response.
