### ISSUE TITLE
Route composition not working

### ISSUE THREAD

**Issue by ohuu** [zio/zio-http#334]
Here is my simple server

```scala
package example

import zio._
import zhttp.http._
import zhttp.service.Server

object HelloWorld extends App {
  val a = Http.collect[Request] { case Method.GET -> Root / "a" => Response.ok }
  val b = Http.collect[Request] { case Method.GET -> Root / "b" => Response.ok }

  val app = a <> b

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    Server.start(8090, app).exitCode
  }
}
```

`cURL http://localhost:8090/a` works just fine, however `cURL http://localhost:8090/b` is not found. Am I missing something?

**Comment by amitksingh1490** [comment]
use combine `+++` operator instead of orElse `<>` operator i.e.`val app = a +++ b`

**Comment by ohuu** [comment]
Many thanks that worked. I may have misunderstood the docs but perhaps the composition section needs updating?
