### ISSUE TITLE
Logging middleware and document creation of middlewares

### ISSUE THREAD

**Issue by kuzkdmy** [zio/zio-http#339]
It looks that it is not so obvious how to create server middleware
From api example there exists only authentiate middleware but it is not a good example
We really need to have out of box Logging middleware, the same as http4s server has
Next critical middleware is prometheus middleware, but this is another story
And sure we need to have a pure documentation how to create server middleware
Thanks.

**Comment by tusharmath** [comment]
will be fixed in #403

**Comment by girdharshubham** [comment]
Thanks for raising this GH issue @kuzkdmy.
Logging middleware is being tracked in issue #436
