### ISSUE TITLE
Incorrect behaviour of getBodyAsString

### ISSUE THREAD

**Issue by floatfield** [zio/zio-http#350]
Seems that current implementation of `getBodyAsString` isn't able to extract let's say utf-8 chars from request body (as it simply converts every byte to a char, which is not the case when a symbol doesn't fit one byte). Maybe it's possible to extract somehow charset from headers and make a string using `String(byte bytes[], Charset charset)` constructor?

**Comment by ShrutiVerma97** [comment]
@floatfield This was fixed in #287. Will get updated in the next release.

**Comment by dinojohn** [comment]
Fix included in the latest release.
