### ISSUE TITLE
Support for Compression

### ISSUE THREAD

**Issue by nguyenvietyen** [zio/zio-http#358]
I intend to use zio-http as a client, but the question probably also applies to zio-http as a server.

Question: what is the intended philosophy for handling compression? 

I dug into the code and GH issues repo and could not find any reference to it. Is there an intent to add support for gzipped data? Or is compression expected to be "manually" handled by the dev using zio-http?

**Comment by tusharmath** [comment]
Generally, you don't want to have your application server or micro-service handle compression also. There should be a layer of Nginx or some other reverse proxy in front of you application server for best performance.

However, adding compression to ZIO Http should be fairly straight forward :)

**Comment by girdharshubham** [comment]
#1098 brings in this feature

**Comment by tusharmath** [comment]
Fixed in #1098
