### ISSUE TITLE
Request with empty path ignoring query parameters

### ISSUE THREAD

**Issue by GrigoriiBerezin** [zio/zio-http#422]
For example, if I want to get response from www.site.com?q=param, the actual request would be on www.site.com, which is not correct.

**Comment by GrigoriiBerezin** [comment]
#421 pull request with fixing this bug

**Comment by girdharshubham** [comment]
Thanks for creating this issue @GrigoriiBerezin. This has been fixed in #529 which is a part of the [v1.0.0.0-RC18](https://github.com/dream11/zio-http/releases/tag/v1.0.0.0-RC18) release.

Closing this issue.
