### ISSUE TITLE
Add Authentication middleware 

### ISSUE THREAD

**Issue by kaushik143** [zio/zio-http#431]
# Description
Add middleware which will check if the request is Authenciated otherwise it will send a Response status of 401

#API suggestion

```scala
HttpApp @@ authenticate(authFunction)

val authFunction: List[Headers] => ZIO[R, E, boolean]
```

# Spec
- Add authentication middleware
- Update [AuthenciationScala](https://github.com/dream11/zio-http/blob/main/example/src/main/scala/Authentication.scala) example 
- Add test case for authentication middleware

**Comment by tusharmath** [comment]
I think authentication can focus on more specialized middlewares, for eg:

**Basic Auth**
```scala
app @@ basicAuth(uname, password)
```

**JWT Auth**

```scala
app @@ jwtAuth(jwtConfig)
```
