### ISSUE TITLE
Circuit breaker middleware

### ISSUE THREAD

**Issue by kaushik143** [zio/zio-http#435]
# Description
The basic idea behind the circuit breaker is very simple. You wrap a protected function call in a circuit breaker object, which monitors for failures. Once the failures reach a certain threshold, the circuit breaker trips, and all further calls to the circuit breaker return with an error, without the protected call being made at all. Usually, you'll also want some kind of monitor alert if the circuit breaker trips.

# API suggestion

```scala
app @@ circuitBreaker(thresholdReached, fallbackApp)
```

# Spec
- Allow configuring fallbackApp 
- Allow configuring threashldReached function
- Add example app showing use case of circuitBreaker middleware 

# Power 🦾 
This is real power Just imagine you able to fall back to a different app in case your current app is failing

**Comment by rysh** [comment]
I have a question: I was thinking of creating a method or extension method of “app", what does the "@" in API suggestion mean?

**Comment by rysh** [comment]
I am now thinking of creating a tiny spec based on the following.
https://resilience4j.readme.io/docs/circuitbreaker

**Comment by rysh** [comment]
I implemented it and created the PR here.
https://github.com/dream11/zio-http/pull/757

**Comment by tusharmath** [comment]
Circuit breaker isn't something that one implements on the server, it's a client behaviour. 
https://microservices.io/patterns/reliability/circuit-breaker.html
