### ISSUE TITLE
Logging middleware

### ISSUE THREAD

**Issue by kaushik143** [zio/zio-http#436]
# Description
In our HttpApp we came across many cases where we want to log requests and responses to understand what's going inside our application.

# API suggestion
```scala

app @@ log(requestLogger, responseLogger, options)

final case class RequestLogger(logMethod: Boolean, logHeaders: Boolean, level: Int)
final case class ResponseLogger(logMethod: Boolean, logHeaders: Boolean, level: Int)

sealed trait Options
object Options {
 case class SKIP(when: (req, res) => Boolean)
}
```

Spec
- Create Domain for RequestLogger, ResponseLogger, and Options taking care of all the basic options
- Add middleware that allows us to configure requestLogger, responseLogger, and options
- Add example showing the use of log

**Comment by jgoday** [comment]
I would like to try to implement if possible

**Comment by tusharmath** [comment]
@jgoday I think the logging middleware should integrate with ZIO Logging properly, maybe something simple like — 

```scala
import zio.logging.{Logging}
import zhttp.middleware.{log}

app @@ log(Logging.info(_))
```

What do you think?

**Comment by jgoday** [comment]
> @jgoday I think the logging middleware should integrate with ZIO Logging properly, maybe something simple like —
> 
> ```scala
> import zio.logging.{Logging}
> import zhttp.middleware.{log}
> 
> app @@ log(Logging.info(_))
> ```
> 
> What do you think?

Sure, I have created a PR with zio-logging that follows the original issue suggestions, so log level is defined with the RequestLogger/ResponseLogger domain objects
```scala
val requestLogger = RequestLogger(logMethod=true, logHeaders=true, level=LogLevel.Debug)
  val responseLogger = ResponseLogger(logMethod=true, logHeaders=true, level=LogLevel.Info)
  val options = Options.Skip(
    { case ((_, url, _), _) => url.path.startsWith(Path("test")) }
  )

  def app: HttpApp[Console with Clock with Logging, Throwable] = echo @@ log(
    request = requestLogger,
    response = responseLogger,
    options = options
  )
```

**Comment by tusharmath** [comment]
Closing this as ZIO 2 now contains built in support for logging.
