### ISSUE TITLE
Content Length Middleware

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#441]
Add support for a content-length middleware.

```scala
val app: HttpApp[Any, Nothing] = ???

val appWithContentLengthHeaders = app @@ contentLength 
```

This middleware should be able to attach a `content-length` header automatically to every response.

**Comment by atrianac** [comment]
@tusharmath Any info how to create a new middleware?

**Comment by ShrutiVerma97** [comment]
@atrianac For now you can check [HttpMiddleware.scala](https://github.com/dream11/zio-http/blob/release/next/zio-http/src/main/scala/zhttp/http/middleware/HttpMiddleware.scala), we have created two middleware `timeout` and `debug`. You can check usage in [HttpMiddlewareSpec.scala](https://github.com/dream11/zio-http/blob/release/next/zio-http/src/test/scala/zhttp/middleware/HttpMiddlewareSpec.scala)

**Comment by tusharmath** [comment]
This is set automatically. Middleware won't be required.
