### ISSUE TITLE
Move all the examples in an Example Package

### ISSUE THREAD

**Issue by amitksingh1490** [zio/zio-http#480]

**Comment by rysh** [comment]
Can I try this Issue?
Is the move targeted at the following?
- Simple Server
- Advanced Server
- WebSocket Server
- Streaming Response
- Simple Client
- File Streaming
- Authentication

**Comment by amitksingh1490** [comment]
@rysh This is already done and merged in the next release branch.
Sorry for not updating the issue with its status.

**Comment by dinojohn** [comment]
Included in the latest release. 
https://github.com/dream11/zio-http/releases
