### ISSUE TITLE
Multipart Requests

### ISSUE THREAD

**Issue by kaushik143** [zio/zio-http#503]

**Comment by kubinio123** [comment]
Hi, what's the status of multipart support?

**Comment by ShrutiVerma97** [comment]
> Hi, what's the status of multipart support?

 We are yet to create a decoder for multipart. Till that time you can use request streaming and create multipart decoder for your use-case.

**Comment by NavidJalali** [comment]
I would like to work on this, but I have absolutely no idea how to do it, so I might need some direction 🥺

**Comment by vigoo** [comment]
Closed by https://github.com/zio/zio-http/pull/1953
