### ISSUE TITLE
Consider encoding endpoints as data (not Partial Function)

### ISSUE THREAD

**Issue by V-Lamp** [zio/zio-http#524]
Hi,

I don't normally parachute to projects to throw my opinion, so apologies for this but given I believe ZIO will be the next default FP stack, I am interested to get the best out of it 🙂 

A partial function is opaque, while a DSL resulting in a data structure would enable further synergies, from post-processing to generating documentation etc. [This is an example of this](https://endpoints4s.github.io/), though a think there is another library with a similar approach that escapes my memory.
If this has been considered already, happy for you to close this.

Have a great day and thanks for the good work!

**Comment by tusharmath** [comment]
@V-Lamp Thanks for the feedback and I totally hear you :)

We want to support both on ZIO Http and you can see that some work has already started here https://github.com/dream11/zio-http/blob/release/next/example/src/main/scala/example/Endpoints.scala

```scala
 def h1 = GET / "a" / *[Int] / "b" / *[Boolean] to { a =>
    Response.text(a.params.toString)
  }
```

At the moment only route params are supported, but we will eventually support query params and what not :)
