### ISSUE TITLE
Add methods to `Status`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#573]
The following methods can be added to Status

- [x] `toResponse` which converts the `Status` to a `Response`
- [x] `toApp` which converts the `Status` to `HttpApp`

**Comment by jgoday** [comment]
> The following methods can be added to Status
> 
> * [ ]  `toResponse` which converts the `Status` to a `Response`
> * [ ]  `toApp` which converts the `Status` to `HttpApp`

Hi @tusharmath, just created PR #577,
I'm not sure if there are more implications or other considerations, feel free to discard it if's not valid.
