### ISSUE TITLE
Request: Add operator to replace the requestBody

### ISSUE THREAD

**Issue by amitksingh1490** [zio/zio-http#614]
**Is your feature request related to a problem? Please describe.**
There is no operator in on `Request` which can help me update the request body.

**Describe the solution you'd like**
Currently `Request` has operators to update `method`, `url` and `headers` but for updating the body there is no Operator for updating RequestBody.
we could add an operator
```scala
def setBody(body: HttpData[R, E]): Request = ???
```

**Describe alternatives you've considered**
We could create a new request for updating the body but we have to pass `headers` `method` and `url` even if we don't want any change in that.

**Comment by tusharmath** [comment]
Can you expand on why this operator is required @amitksingh1490

**Comment by amitksingh1490** [comment]
There is no realistic  Use case for this, However if needed new Request can be created
