### ISSUE TITLE
Improve benchmark comment

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#620]
**What is not easy to do right now?**
- The benchmark comment is a bit too noisy while reviewing PRs.
- There is no commit ID information.
- Use a bot account to publish the message instead of @amitksingh1490.

**Describe the solution you'd like**
One example could be — 

---
<details>
<summary>🚀 <b>Benchmark</b></summary>

Concurrency: **256**
Requests/sec: **439800.43**
</details>

---

**Why is it important?**
It will reduce the comment noise in PRs.

**Additional context**
- Comment on commit https://docs.github.com/en/rest/guides/working-with-comments#commit-comments

**Comment by amitksingh1490** [comment]
Should we run benchmark on demand maybe when a label is applied? Instead of every commit?

**Comment by tusharmath** [comment]
Until it becomes a problem and we aren't able to scale our benchmarking infrastructure we should keep it running on every commit.
