### ISSUE TITLE
Not able to create websocket multiple connections when Response is ZIO

### ISSUE THREAD

**Issue by ShrutiVerma97** [zio/zio-http#623]
**Describe the bug**
```scala
  private val socketApp = SocketApp.message(socket)
  private val webSocketApp = Http.collectM[Request] { case Method.GET -> !! / "subscriptions" =>
    ZIO(Response.socket(socketApp))
  }
  ```
  using the above code not able to make more than 5 connections

**To Reproduce**
1.  Create a websocketApp using below code
```scala
  private val socketApp = SocketApp.message(socket)
  private val webSocketApp = Http.collectM[Request] { case Method.GET -> !! / "subscriptions" =>
    ZIO(Response.socket(socketApp))
  }
  ```
2. Start server and make multiple websocket request. The request go in pending after couple of successful request.

**Expected behavior**
The socket request should upgrade to 101, till the time ports and file descriptors are available for client

**Comment by tusharmath** [comment]
Can you provide the steps to reproduce the issue.

**Comment by amitksingh1490** [comment]
This seems an Application level issue, Not reproducible in ZIO-Http Examples. However, We should add a Integration test for the scenario.

**Comment by tusharmath** [comment]
Is the handshakeTimeout required?

**Comment by amitksingh1490** [comment]
> Is the handshakeTimeout required?

Handshake timeout is not required. This bug can be reproduced without HandshakeTimeout
