### ISSUE TITLE
Add Integration tests for websocket

### ISSUE THREAD

**Issue by ShrutiVerma97** [zio/zio-http#640]
**What is not easy to do right now?**
Right now, there is no way to test WebSocket

**Describe the solution you'd like**
We can add functionality to the existing client to create WebSocket connections, meanwhile, we can use any other websocket client to implement integration test

**Comment by amitksingh1490** [comment]
Currently written using sttp client can be easily updated when Zhttp-client has websocket support. Fixed in #649
