### ISSUE TITLE
Encoding problem when using HttpData.fromText and multi byte characters

### ISSUE THREAD

**Issue by davidlar** [zio/zio-http#641]
HttpData.unsafeSize for Text returns number of characters and not bytes. This results in a bad content length and a broken response when using multi byte characters like e.g. `åäö`.

Current work around:

Instead of
`HttpData.fromText("åäö")` or `Response.text("åäö")`

do 
`HttpData.fromByteBuf(Unpooled.copiedBuffer("åäö", HTTP_CHARSET))`

Version: 1.0.0.0-RC18

**Comment by tusharmath** [comment]
Thanks for reporting @davidlar, we are looking into this issue.
