### ISSUE TITLE
WebSocket client

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#650]
**Is your feature request related to a problem? Please describe.**
I want to be able to use the http client for websocket connections

**Describe the solution you'd like**
We can start with a basic API that looks like this. Later on, add support for client configuration or potentially support `SocketApp` directly.

```scala
val fooBar = Socket.collect[WebSocketFrame] {
  case WebSocketFrame.Text("FOO") => ZStream.succeed(WebSocketFrame.text("BAR"))
  case WebSocketFrame.Text("BAR") => ZStream.succeed(WebSocketFrame.text("FOO"))
}

Client.socket(fooBar) // Task[Unit]
```

**Describe alternatives you've considered**
- None

**Comment by girdharshubham** [comment]
@tusharmath `Client.socket(socket)` would just give us a description for communication. I'm not sure how the Client should process this during execution. Do you think a seed is required on open?

**Comment by tusharmath** [comment]
I am not sure what do you mean by "description for communication".

**Comment by girdharshubham** [comment]
- [x] Unit test case for websocket client
- [x] queue internal for assertions
- [x] client socket handler
- [x] edit channel initializer
- [x] client api
- [ ] websocket client config generation
- [x] websocket client example
- [ ] general refactor

Note: The code for ClientSocketHandler takes heavy implementation from ServerSocketHandler which brings in some code duplication, maybe we could remove some duplication. The differentiator is the `userEventTriggered` method in both these handlers.
