### ISSUE TITLE
Update documentation for Request

### ISSUE THREAD

**Issue by dinojohn** [zio/zio-http#652]
**What is not easy to do right now?**
The doc is outdated in https://github.com/dream11/zio-http/blob/main/docs/index.md#accessing-the-request

**Describe the solution you'd like**
Update the code snippets as per RC18

**Why is it important?**
Docs and examples help developers understand how to use zhttp.

**Comment by Vipul-J** [comment]
Shall I work on this?

**Comment by amitksingh1490** [comment]
Sure go ahead

**Comment by ShrutiVerma97** [comment]
#926
