### ISSUE TITLE
Support any `Iterable` in `Http.addHeaders`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#657]
**Is your feature request related to a problem? Please describe.**
I want to be able to add/remove headers using any `Iterable[String]` instead of only `List`

**Describe the solution you'd like**
```scala
// Current
def addHeaders(headers: List[Header]) = ???

// Proposal
def addHeaders(headers: Iterable[Header]) = ???
```

**Comment by amitksingh1490** [comment]
Already fixed
