### ISSUE TITLE
Add file support in `HttpData`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#674]
**Is your feature request related to a problem? Please describe.**
Currently the only way to serve files is via `ZStream.fromFile`. This works, however is slow and uses a blocking thread pool.
```scala
Http.collect[Request] { 
 case Get -> !! / "file" => Response(data = HttpData.fromStream(ZStream.fromFile(Paths.get("README.md")))
}
```

**Describe the solution you'd like**
It would better to use a specialized constructor in HttpData that reads files efficiently.
```scala
Http.collect[Request] { 
 case Get -> !! / "file" => Response(data = HttpData.fromPath(Paths.get("README.md"))
}
```
Where `HttpData.fromPath` internally uses netty's `ChunkedFile` API.

- This solution will be significantly more performant since it's going to run on the same thread as the incoming request.
- Later the implementation can be used to build a static server eg: `Http.static("~/public")`
- Ideally the `content-size` should be set in the response header because files on disk typically have a finite size.

**Describe alternatives you've considered**
We create a new file reader that reads file in chunks using netty's `ChunkedFile` API and then use `HttpData.fromStream` to create an HttpData.
We need to still test how well it performs under load.

```scala
  final class ChunkedReader(file: ChunkedFile, alloc: ByteBufAllocator) {
    def read: ZIO[Any, Option[Throwable], ByteBuf] =
      ZIO.effectSuspendTotal {
        try {
          val data = file.readChunk(alloc)
          if (data == null) ZIO.fail(None)
          else UIO(data)
        } catch {
          case error: Throwable => ZIO.fail(Option(error))
        }
      }

    def toStream: ZStream[Clock, Throwable, ByteBuf] = ZStream.repeatEffectOption(read)
  }

  object ChunkedReader {
    def make(path: java.nio.file.Path, alloc: ByteBufAllocator = ByteBufAllocator.DEFAULT): ZIO[Any, Throwable, ZIOChunkedFile] = for {
      file  <- Task(path.toFile)
      cFile <- Task(new ChunkedFile(file, 128))
    } yield new ZIOChunkedFile(cFile, alloc)
  }

// Inside HttpData

  def fromFile(path: java.nio.file.Path): HttpData[Clock, Throwable] =
    HttpData.BinaryStream(ZStream.unwrap(ZIOChunkedFile.make(path).map(_.toStream)))
```

**Additional context**
- Will need to add a `ChunkedWriteHandler` in the pipeline if the response is a file
- Sample implementation: https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/file/FileServerHandler.java

**Comment by ashprakasan** [comment]
I'll take a stab at this.
