### ISSUE TITLE
Client default User Agent request header

### ISSUE THREAD

**Issue by gciuloaica** [zio/zio-http#685]
**Is your feature request related to a problem? Please describe.**
There are many REST APIs that are mandating http clients to provide a proper User Agent request header. 
One of those APIs is [Github API](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required) that reject the request that do not provide a valid User Agent request header with each request.

**Describe the solution you'd like**
ZIO Http client should provide a default value for User Agent request header, following the recommendations from [Http 1.1 Specification](https://httpwg.org/specs/rfc7231.html#header.user-agent)

**Comment by rajcspsg** [comment]
Can I take this?

**Comment by tusharmath** [comment]
Yes please!

**Comment by rajcspsg** [comment]
Hi @tusharmath 

I'm planning to set the default user-agent as `Zio-Http-Client ${zio-http-jar-version} Scala ${scala-version}`.

please let me know your feedback.

**Comment by amitksingh1490** [comment]
> Hi @tusharmath
> 
> I'm planning to set the default user-agent as `Zio-Http-Client ${zio-http-jar-version} Scala ${scala-version}`.
> 
> please let me know your feedback.

Looks good to me
