### ISSUE TITLE
Scala 3.1.0, RC19, throws netty warnings

### ISSUE THREAD

**Issue by jetaggart** [zio/zio-http#686]
**Describe the bug**
Every request throws a warning:
```

Dec 23, 2021 4:07:56 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

```

**To Reproduce**
Repro repo: https://github.com/bit-void/zio-http-fail

**Comment by tusharmath** [comment]
Hey @jetaggart !
Could you share some more details here. The error just means, that the connection was closed abruptly, which might not necessarily be a bug.

**Comment by jetaggart** [comment]
I don't know how much more I can provide outside the repro repo. It's a fairly simple case, not sure how I'd close the connection abruptly:

```

object HelloWorld extends App {
  val app = Http.collectM[Request] {
    case Method.GET -> !! / "text" => ZIO.succeed(Response.text("Hello World!"))
  }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
}
```

**Comment by tusharmath** [comment]
What tool are you using to make the request? Also what are the headers, http version etc.?
