### ISSUE TITLE
Use FullHttpResponse when possible

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#689]
**Is your feature request related to a problem? Please describe.**
Using `FullHttpResponse` is a lot more performant.

**Describe the solution you'd like**
For scenarios where the HttpData is a `ByteBuf` we can directly encode the data as FullHttpResponse and write the message only once.

**Describe alternatives you've considered**
-

**Additional context**
This is purely a performance focussed change. It won't have any impact on the usability of the library.

**Comment by girdharshubham** [comment]
Has been done in #713
