### ISSUE TITLE
Rename `HttpData.fromText` to `HttpData.fromString` 

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#693]
**Is your feature request related to a problem? Please describe.**
The naming convention needs to be flowed in HttpData.

**Describe the solution you'd like**
Since the data is being created from `String` and there is nothing like `text` in Scala, we should rename the function to `fromString`.

**Describe alternatives you've considered**

- NA

**Additional context**
- This would be a breaking change.
- We should not delete the current method, however add a `deprecated` tag on it.

**Comment by rajcspsg** [comment]
can I work on this simple issue?

**Comment by rajcspsg** [comment]
@tusharmath @amitksingh1490 I've [PR](https://github.com/dream11/zio-http/pull/704) for this issue

**Comment by tusharmath** [comment]
fixed in #704
