### ISSUE TITLE
Add documentation for all the server settings

### ISSUE THREAD

**Issue by kaushik143** [zio/zio-http#700]
**What is not easy to do right now?**
There is no easy way to find out all the configurable server settings.

**Describe the solution you'd like**
We should add the `Configuration` section in the readme.

Sample format
| Property | Description | Type | Default |

**Why is it important?**
Save developer time and use the full power of `zio-http`

**Additional context**
https://stackoverflow.com/questions/70475239/zio-http-configuration-for-max-request-size

**Comment by amitksingh1490** [comment]
I think the better approach would be, to create a documentation page for Server and explain each of the config's.
dream11.github.io/zio-http

**Comment by tusharmath** [comment]
Let's get the Scala docs right first. Then move on to the website, what do you think?

**Comment by amitksingh1490** [comment]
https://dream11.github.io/zio-http/docs/v1.x/dsl/server/index
this is fixed
