### ISSUE TITLE
Remove `Endpoint` from `Client.request`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#712]
**What is not easy to do right now?**
The `zhttp.endpoint.Endpoint` and `zhttp.service.Client.Endpoint` are two separate and confusing types. 

**Describe the solution you'd like**
Delete `zhttp.service.Client.Endpoint` and just simply use `Method` and `Path` where ever required eg: 

```scala

// Current
def request(endpoint: Endpoint, headers: Headers, content: HttpData[Any, Nothing]): ZIO[EventLoopGroup with ChannelFactory, Throwable, ClientResponse]

// Proposed
def request(method: Method, url: URL, headers: Headers, content: HttpData[Any, Nothing]): ZIO[EventLoopGroup with ChannelFactory, Throwable, ClientResponse]
```

**Why is it important?**
General cleanliness and hygiene.

**Additional context**

None

**Comment by brendo-m** [comment]
Happy to take this one

**Comment by amitksingh1490** [comment]
Thanks @brendo-m
