### ISSUE TITLE
Can I use custom pipeline instead of default 

### ISSUE THREAD

**Issue by rajcspsg** [zio/zio-http#715]
Hi,

This is the question - 

The examples for starting the server in this project always using [Server.make](https://github.com/dream11/zio-http/blob/main/zio-http/src/main/scala/zhttp/service/Server.scala#L101).
If I want to use some [custom http pipeline](https://github.com/rajcspsg/netty-mem-detect-demo/blob/master/core/src/main/java/com/myorg/netty/HttpServerPipelineFactory.java#L14-L22) , How can I achieve the same?

**Comment by rajcspsg** [comment]
Let me add more details to this issue - 

the client can send requests in payload compressed based on the content-encoding header. For example, if the contents are compressed in gzipped format, then the [content-encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) header would be `gzip`. Netty provides [HttpContentDecompressor](https://netty.io/4.1/api/io/netty/handler/codec/http/HttpContentDecompressor.html) channel handler for this feature.

Similarly the server can also send response in compressed format based on the [Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) header in the request. For this Netty provides [HttpContentCompressor](https://netty.io/4.1/api/io/netty/handler/codec/http/HttpContentCompressor.html) channelHandler for this feature.

I've an example [here](https://stackoverflow.com/questions/61031731/io-netty-handler-codec-compression-decompressionexception-unsupported-compressi). The code is on github [here](https://github.com/rajcspsg/netty-mem-detect-demo). you can run the project by using `gradle just-netty:runMain` to run the server. The example of client to call the server is [here](https://stackoverflow.com/a/61132190/2541276)

```scala
try(CloseableHttpClient httpclient = HttpClients.createDefault()) {
        HttpPost httppost = new HttpPost("http://localhost:5880/test");
        String payload = "{ \"test\" : 1 }";
        EntityBuilder builder = EntityBuilder.create().gzipCompress().setContentEncoding("gzip").chunked().setText(payload);
        HttpEntity entity = builder.build();
        httppost.setEntity(entity);
        System.out.println();
        httppost.setHeader("Accept-Encoding", "gzip,deflate");
        httppost.setHeader("Content-Encoding", "gzip");
        System.out.println("Executing request: " + httppost.getRequestLine());
        CloseableHttpResponse response = httpclient.execute(httppost);
        try {
            System.out.println("----------------------------------------");
            System.out.println(response.getStatusLine());
            System.out.println(EntityUtils.toString(response.getEntity()));
        } finally {
            response.close();
        }
    }
```

In my current organization we use HttpContentCompressor and HttpContentDecompressor in our server and also has some additional handler in pipeline. 

IMHO, zio-http should allow users to provide option for defining custom HttpPipeline. In cases if the users didn't provide additional pipeline , then `Server.make` should use default pipeline.

Please let me know if I'm not clear in this problem description.

**Comment by tusharmath** [comment]
This seems like something we should have in ZIO Http.
