### ISSUE TITLE
SSLSpec is flaky

### ISSUE THREAD

**Issue by dinojohn** [zio/zio-http#718]
**Describe the bug**
Sometimes SSLSPec time outs

**To Reproduce**
It happens without any pattern

**Comment by dinojohn** [comment]
SSLSPec is flaky. At times it get timed out. Thread dumps suggested a deadlock.   Separate HttpRuntimes were created for client and server to log `fiber failure`s . It suggests that the deadlocks are coming from a `fiber failure` from client.
Will be looking deeper into the client side implementation of SSL and Client in general.

> "main" #1 prio=5 os_prio=31 cpu=1666.09ms elapsed=15.63s tid=0x00007fbbed809000 nid=0x1803 in Object.wait()  [0x0000700004f38000]
>    java.lang.Thread.State: WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11.0.11/Native Method)
>         - waiting on <0x000000070063f200> (a zio.internal.OneShot)
>         at java.lang.Object.wait(java.base@11.0.11/Object.java:328)
>         at zio.internal.OneShot.get(OneShot.scala:81)
>         - waiting to re-lock in wait() <0x000000070063f200> (a zio.internal.OneShot)
>         at zio.Runtime.unsafeRunSync(Runtime.scala:86)
>         at zio.Runtime.unsafeRunSync$(Runtime.scala:81)
>         at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:288)
>         at zio.Runtime.unsafeRun(Runtime.scala:59)
>         at zio.Runtime.unsafeRun$(Runtime.scala:58)
>         at zio.Runtime$$anon$3.unsafeRun(Runtime.scala:288)
>         at zio.test.RunnableSpec.main(RunnableSpec.scala:48)
>         at zhttp.service.SSLSpec.main(SSLSpec.scala)

**Comment by jdegoes** [comment]
Closing, please re-open if still relevant.
