### ISSUE TITLE
Rate limiting middleware.

### ISSUE THREAD

**Issue by aposto** [zio/zio-http#738]
Do you have any plans to develop a late limiting middleware?

I think it's a very important feature.

Thanks.

**Comment by amitksingh1490** [comment]
@aposto Do you mean Rate Limiting? Could you please describe the behaviour of this middleware.

**Comment by tusharmath** [comment]
@aposto Have you tried — https://www.vroste.nl/rezilience/docs/ratelimiter ?

**Comment by aposto** [comment]
@tusharmath  https://www.vroste.nl/rezilience/docs/ratelimiter 
This is not bad, but it would be even better if it was integrated into middleware and implemented to control the speed per IP or Session.
- https://github.com/labstack/echo/blob/master/middleware/rate_limiter.go

**Comment by tusharmath** [comment]
Rate limiting can get really complex and contains a vast number cases to consider. I would recommend that it is created as a community package.
