### ISSUE TITLE
Add operators to create Http from `HExit`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#755]
**Is your feature request related to a problem? Please describe.**
It's not possible to create Http from `HExit`

**Describe the solution you'd like**
```scala

val exit = HExit.succeed(1)

// Add fromExit constructor
Http.fromExit(exit)

// Add collectExit constructor
Http.collectExit[Request] {
 case _ => HExit.fail("Error")
}

```

**Describe alternatives you've considered**
Currently you can achieve this behaviour using `Http.collect[Request] { ... => Http.succeed(1) } .flatten`. It's awkward and a bit slow in terms of performance.

**Additional context**
Should be possible after #739

**Comment by rajcspsg** [comment]
@tusharmath for `fromExit` function, do you think the below is correct way?

```
 /**
   * Converts a HExit to an Http type
   */
  def fromExit[R, A, E](exit: HExit[R, E, A]): Http[R, E, Any, A] = Http.fromEffect(exit.toEffect)
```

**Comment by tusharmath** [comment]
You should create a new primitive for this, ie. a new set of case classes eg: `FromExit`
