### ISSUE TITLE
<> to compose Http does not work

### ISSUE THREAD

**Issue by pmeheut** [zio/zio-http#780]
I wrote a very basic application in Scala 3.1.0 to test it using 1.0.0.0-RC21:

```
object WebServer extends App {
  val a = Http.collect[Request] { case Method.GET -> !! / "a"  => Response.text("in a") }
  val b = Http.collect[Request] { case Method.GET -> !! / "b"  => Response.text("in b") }

  val app = a <> b

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    Server.start(8080, app).exitCode
  }
}
```

`curl http://localhost:8080/a` returns `in a`.
`curl http://localhost:8080/b` returns nothing.

**Comment by amitksingh1490** [comment]
```scala 
a <> b
```
the above statement mean "a" `orElse` "b". "b"  will only get executed if "a" fails with `Some(error)`
for composing you should use
```scala
a ++ b
```

**Comment by pmeheut** [comment]
Thanks but this is not what the documentation states. See:
https://dream11.github.io/zio-http/docs/index#composition

**Comment by amitksingh1490** [comment]
We are Working on updating the doc. 
Sorry for the confusion

**Comment by pmeheut** [comment]
No problem. I like ZHttp but between this and the recent bug with Response.json fixed in your source code but not yet released, I lost a lot of time.
Keep up the good work till you are production ready.

**Comment by amitksingh1490** [comment]
Thanks, Please join our [discord](https://discord.gg/pfwk7t7Q). 
You can post your queries there we will answer them quickly.
