### ISSUE TITLE
Response.json produces invalid content-length header

### ISSUE THREAD

**Issue by willemvermeer** [zio/zio-http#787]
Hi, 

I think something's wrong with the content-length header in case of creating json Responses:

The following code:
```
val app = {
    Http.collectM[Request] {
      case Method.GET -> !! / "text" => ZIO.succeed(Response.json("{}"))
   }
}
```
Results in:
```
$ curl http://localhost:8090/text
curl: (8) Invalid Content-Length: value
```
Whereas:
```
curl http://localhost:8090/text
{}
```
produces the json string as expected.

Can you take a look what may be wrong? Thanks!

**Comment by amitksingh1490** [comment]
@willemvermeer  Thanks for reporting this bug, It duplicates #747 .
We will be releasing the fix next week. However you could use Snapshot version till then or use something like below to make this work
```scala
Response(data= HttpData.fromString("{}"), headers = Headers(HeaderNames.contentType, HeaderValues.applicationJson))
```

**Comment by willemvermeer** [comment]
Great! The workaround you provide works for the moment, thanks.
