### ISSUE TITLE
Add Integration tests when Http executes to `HExit.success`

### ISSUE THREAD

**Issue by amitksingh1490** [zio/zio-http#829]
**What is not easy to do right now?**
Current integration tests, not cover the scenarios when Http evaluates to `HExit.success`

**Describe the solution you'd like**
Add a static app with `Http.collect`
test for Get and Post requests for success, failure and Not found.

**Why is it important?**
It will help us catch regression issues

**Comment by zsfVishnu-d11** [comment]
Will pick this up.

**Comment by amitksingh1490** [comment]
Thanks @zsfVishnu-d11  Let me know incase you need any help
