### ISSUE TITLE
Enhancement : Build a static file server

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-http#830]
**Is your feature request related to a problem? Please describe.**

`Http.fromFile(file: java.io.File)` is currently incomplete. For anybody to be able to successfully use it out of the box, the following features need to be supported -

1. `BAD_REQUEST` response in case of invalid request
2. `METHOD_NOT_ALLOWED` response if `Http method` is not `GET`
3.  `NOT-FOUND` if the file does not exist
4. `FORBIDDEN` if there are permission issues on the file
5.  `INTERNAL SERVER ERROR` in case some other exception is thrown
6. Cache validation and correct handling of `IF_MODIFIED_SINCE` header.
  
**Describe the solution you'd like**

The following should be appropriately handled - 

1. `BAD_REQUEST` response in case of invalid request (This will apply to all requests, not just `Http.fromFile`)
2. `METHOD_NOT_ALLOWED` response if `Http method` is not `GET`
3.  `NOT-FOUND` if the file does not exist
4. `FORBIDDEN` if there are permission issues on the file
5.  `INTERNAL SERVER ERROR` in case some other exception is thrown
6. Cache validation and correct handling of `IF_MODIFIED_SINCE` header on request

**Describe alternatives you've considered**
The developer using `zio-http` will have to handle these scenarios explicitly, which does not provide great devx.

**Additional context**
Implementation of Static File Server on netty - https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/file

**Comment by tusharmath** [comment]
We could do something like this —

```scala
def config: StaticServerConfig = ???
def app = Http.fromPath("./public", config)
```

The `config` would contain a set of parameters such as `etag` `index` etc. 

ExpressJS has a really nice API to configure the static server — https://expressjs.com/en/4x/api.html#express.static

http://expressjs.com/en/starter/static-files.html

**Comment by guizmaii** [comment]
Really looking forward to using this feature! ❤️
