### ISSUE TITLE
Use template syntax to create internal server error pages

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#842]
**What is not easy to do right now?**
Internal server error page uses strings to create the HTML document. This is error prone and hard to maintain.

**Describe the solution you'd like**
Would like to use the templating syntax that is now available inside of `zhttp.html`.

**Additional context**
Look at `example.HtmlTemplating` to get learn more about the syntax.

**Comment by girdharshubham** [comment]
Hi @tusharmath 
The scope of this issue is just to switch from this string to the HTML template syntax?
```scala
  s"""
       |<html>
       |  <head>
       |  </head>
       |  <body>
       |   <h1>Internal Server Error</h1>
       |   <pre>${prettyPrint(throwable).split("\n").map(str => s"<div>${str}</div>").mkString("")}</pre>
       |  </body>
       |</html>
       |""".stripMargin
```

**Comment by tusharmath** [comment]
Yes.
