### ISSUE TITLE
Enhancement : Add `Options` to Static File server (`Http.serveFilesFrom`)

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-http#862]
**Is your feature request related to a problem? Please describe.**
The implementation of StaticFileServer does not support any `Config` or `Options`. It should be able to accept `Options` as an argument to modify its behavior.

**Describe the solution you'd like**
A few commonly supported options  -
```
-h, --help                 output usage information
-V, --version              output the version number
-p, --port <n>             the port to listen to for incoming HTTP connections
-i, --index <filename>     the default index file if not specified
-f, --follow-symlink       follow links, otherwise fail with file not found
-d, --debug                enable to show error messages
-n, --not-found <filename> the error 404 file
-c, --cors <pattern>       Cross Origin Pattern. Use "*" to allow all origins
-z, --no-nocache           disable cache (http 304) responses.
-o, --open                 open server in the local browser
```

**Describe alternatives you've considered**
 Currently, any alternate behavior will need to be implemented by dev.

**Additional context**
None.

**Comment by vigoo** [comment]
I think since then we no longer have a built-in static file server, only its building blocks (`Http.fromFile` etc) and an example `StaticServer`. I'm not sure the `StaticServer` code should be extended with these options, as it would just make it harder to understand as an example.
