### ISSUE TITLE
Enhancement : Use templating library for listing files as html in Static file server

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-http#863]
**Is your feature request related to a problem? Please describe.**
The static file server (`Http.serveFilesFrom(...)`) does not use templating library to list contents of the directory as `html`.

**Describe the solution you'd like**
A cleaner solution using templating library.

**Describe alternatives you've considered**
Current implementation constructs the `html` as `string`.

**Additional context**
 https://github.com/dream11/zio-http/blob/main/example/src/main/scala/example/HtmlTemplating.scala

**Comment by vigoo** [comment]
Seems like the `StaticServer` example currently already uses `Handler.template` to construct the HTML response.
