### ISSUE TITLE
HTTP requests contain malformed path

### ISSUE THREAD

**Issue by nguyenvietyen** [zio/zio-http#867]
**Describe the bug**
On 1.0.0.0-RC22, we noticed that HTTPS requests succeed, and that HTTP requests (non-secure) fail. By digging deeper, we found that the HTTP commands are malformed during a normal HTTP request.

**To Reproduce**
1. Run netcat `nc -l 9000`
2. Run 

```scala
import zhttp.service.{ChannelFactory, Client, EventLoopGroup}
import zio.{App, ExitCode, URIO, console}

object SimpleClient extends App {

  val program = for {
    res <- Client.request("http://localhost:9000/foo")
    data <- res.getBodyAsString
    _ <- console.putStrLn(data)
  } yield ()

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    program.exitCode.provideCustomLayer(ChannelFactory.auto ++ EventLoopGroup.auto())
}
```
3. Go back to netcat and see that it received `GET http://localhost:9000/foo HTTP/1.1`
4. Confirm that we see `http://localhost:9000/foo` (observed) for a path instead of `/foo` (expected)

**Expected behavior**
That a HTTP request does `GET /foo HTTP/1.1` instead of `GET http://localhost:9000/foo HTTP/1.1`

**Desktop (please complete the following information):**
 - OS: MacOS 11.6

**Comment by dgalichet** [comment]
I get exactly the same issue. Some web server are able to handle both uri, but other accept only 
`GET /foo HTTP/1.1` and will reject `GET http://localhost:9000/foo HTTP/1.1`
