### ISSUE TITLE
`CONTENT_TYPE` header gets incorrect values because of multiple bugs with `Files.probleFileContent` used in its implementation.

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-http#883]
**Describe the bug**
FileType detections using `Files.probeFileContent` is platform-specific and largely unreliable.
`CONTENT_TYPE` header is `null` (when serving files with extension '.mp4' ) on openJDK because Files.probleFileContent returns `null`.

File type detection is largely platform-specific and was not considered reliable.
**To Reproduce**
1. Run the example `FileStreaming.scala` on `Linux` os with `Open JDK11`
2. Request 'http://www.localhost:8090/video' throws an exception

**Expected behavior**
We should see a proper response with `CONTENT_TYPE` header set as 'video/mp4`

**Screenshots**

**Platform (please complete the following information):**
Ubuntu 11.04 + OpenJDK

**Additional context**
A few bugs being tracked with `Files.probeFileContent`

https://bugs.openjdk.java.net/browse/JDK-7142921
https://bugs.openjdk.java.net/browse/JDK-8186071
https://bugs.openjdk.java.net/browse/JDK-8129632

**Comment by girdharshubham** [comment]
Are you working on this bug, @ashprakasan ?

**Comment by girdharshubham** [comment]
Hi, @ashprakasan 

I was able to find this ticket that I think would be helpful:
* https://bugs.openjdk.java.net/browse/JDK-8162624


Are you still working on this?

**Comment by ashprakasan** [comment]
Hey, I've not started on this yet. 

I was thinking of taking a different approach here
 - Have a local file mapping `content-types` to `file-extensions`
 - Take some inspiration from`Http4s` and do something like [this](https://github.com/http4s/http4s/blob/main/core/shared/src/main/scala/org/http4s/StaticFile.scala#L275) 

Java content detection IFAIK is platform-dependent and largely unreliable even in the later versions. Even if this bug was taken care of in version 9, it would still fail your CI tests.
