### ISSUE TITLE
Use builder pattern to create URLs

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#889]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I create the URL data structure by hand :P 

**Describe the solution you'd like**
I would like to use the builder pattern as follows — 

```scala
val url = URL
  .empty
  .setPath(!! / "root")
  .setHost("www.zio-http.com")
  .setQueryParams(Map("A" -> "B))
  .setPort(8090)
  .setScheme(Scheme.HTTP)
```

**Comment by beem812** [comment]
I'd like to give this one a shot.

**Comment by tusharmath** [comment]
Thanks @beem812 !
