### ISSUE TITLE
Web socket frames concatenation

### ISSUE THREAD

**Issue by kubinio123** [zio/zio-http#892]
Hi, I wan't to do web sockets frames concatenation (I receive non final frames until I hit a final one) and I think it's not possible with the current API of `Socket` since factory methods - `collect` or `partialCollect` which give me access to received frame both require to return a new `Stream` in response, so I cannot perform any stateful accumulation.

```scala
object WebSockets extends App {
  private val socket =
    Socket.collect[WebSocketFrame] {
      case fr @ WebSocketFrame.Text(_) if !fr.isFinal   => ???
      case fr @ WebSocketFrame.Binary(_) if !fr.isFinal => ???
    }

  private val app = Http.collectZIO[Request] { case Method.GET -> !! / "concatenate" => socket.toResponse }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
```

Correct me I'f I am wrong please ;)

**Comment by tusharmath** [comment]
If I understand your question - You can use a `Ref[Chunk[WebSocketFrame]]` and keep adding value to it and return an `ZStream.empty` until you your conditions are met. After which you can send a `ZStream.succeed` or something with a meaningful value.

**Comment by kubinio123** [comment]
Thanks - yes that should work but keeping the state outside of `Socket` Is not what I would expect from w websocket API which is more natural and convenient to be described as a potentially endless stream

**Comment by kubinio123** [comment]
Sorry, closed by miss-click

**Comment by tusharmath** [comment]
I think the newer websocket API is a lot more powerful. You will be able to achieve your objective a lot more easily. Feel free to propose an alternative API if you think that still doesn't solve your usecase.
