### ISSUE TITLE
Encoding of application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by heksesang** [zio/zio-http#916]
It would be nice if with some built-in easy way to encode form data when using the `Client` to send requests, as you'll often want to post to some service that expects `application/x-www-form-urlencoded`.

For example this could be part of the `HttpData` class, that seems like a natural place for something like that.

**Comment by beem812** [comment]
I'd be interested in taking this one with some guidance. I think I see where things need to end up, but is the idea to take a generic piece of data that then gets turned in to the correct url form encoded string or is it enough to have the user provide something like what they've got going on over in http4s i.e.: `UrlForm("foo" -> "bar", "baz" -> "qux")` and encode that?

**Comment by vigoo** [comment]
This is now supported by #1953
