### ISSUE TITLE
ZIO 2 compilation issue

### ISSUE THREAD

**Issue by willemvermeer** [zio/zio-http#922]
Hi, I wanted to try the ZIO2 RCs and ran into a problem when starting a simple Web App. Details below. Thanks!

**Describe the bug**
Compilation error: Symbol 'type zio.Has' is missing from the classpath.
When running with ZIO 2.0.0-RC2 and zhttp 1.0.0.0-RC23

**To Reproduce**
Very simple setup:
```scala
object Main2 extends ZIOAppDefault {
  private val PORT = 8080

  private val fooBar: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "foo" => Response.text("bar")
  }

  private val server =
    Server.port(PORT) ++ Server.paranoidLeakDetection ++ Server.app(fooBar)

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    server.make
      .use(_ => ZIO.never)
      .provide(ServerChannelFactory.auto, EventLoopGroup.auto(2))
      .exitCode
}
```
**Expected behavior**
The server should start normally.

**Additional context**
Full compilation error:
[error] /Users/willem/zio2/Main.scala:19:12: Symbol 'type zio.Has' is missing from the classpath.
[error] This symbol is required by 'type zhttp.service.EventLoopGroup'.
[error] Make sure that type Has is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of zio.
[error]     server.make
[error]            ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed

**Comment by amitksingh1490** [comment]
Basically syntax and import are changed in both version of ZIO

ZIO 2.0
```scala
object Main2 extends ZIOAppDefault {
  private val PORT = 8080

  private val fooBar: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "foo" => Response.text("bar")
  }

  private val server =
    Server.port(PORT) ++ Server.paranoidLeakDetection ++ Server.app(fooBar)

  val run = ZIOAppArgs.getArgs.flatMap { args =>
    // Configure thread count using CLI
    val nThreads: Int = args.headOption.flatMap(x => Try(x.toInt).toOption).getOrElse(0)

    // Create a new server
    server.make
      .use(start =>
        // Waiting for the server to start
        Console.printLine(s"Server started on port ${start.port}")

        // Ensures the server doesn't die after printing
          *> ZIO.never,
      )
      .provideCustom(ServerChannelFactory.auto, EventLoopGroup.auto(nThreads))
  }
```
ZIO 1
```scala
object Main2 extends App {
  private val PORT = 8080

  private val fooBar: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "foo" => Response.text("bar")
  }

  private val server =
    Server.port(PORT) ++ Server.paranoidLeakDetection ++ Server.app(fooBar)

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    server.make
      .use(_ => ZIO.never)
      .provide(ServerChannelFactory.auto, EventLoopGroup.auto(2))
      .exitCode
}
```
Let me know if this helps.

**Comment by willemvermeer** [comment]
Thanks @amitksingh1490 but the problem persists even after copy pasting your ZIO2 code example.
Can you please show me which imports I should use? I have:
```
import zhttp.http._
import zhttp.service.{ EventLoopGroup, Server }
import zhttp.service.server.ServerChannelFactory
import zio._
```
Thanks, Willem

**Comment by willemvermeer** [comment]
Maybe it's caused by the import `zio.Has` in `zhttp.package.scala`?
```
package zhttp

import io.netty.channel.{Channel, ChannelFactory => JChannelFactory, EventLoopGroup => JEventLoopGroup, ServerChannel}
import zio.Has

package object service {

...

  type ChannelFactory       = Has[JChannelFactory[Channel]]
  type EventLoopGroup       = Has[JEventLoopGroup]
  type ServerChannelFactory = Has[JChannelFactory[ServerChannel]]
```

**Comment by amitksingh1490** [comment]
```scala
package example

import zhttp.http._
import zhttp.service.server.ServerChannelFactory
import zhttp.service.{EventLoopGroup, Server}
import zio._

import scala.util.Try

object HelloWorldAdvanced extends ZIOAppDefault {
  // Set a port
  private val PORT = 0

  private val fooBar: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "foo" => Response.text("bar")
    case Method.GET -> !! / "bar" => Response.text("foo")
  }

  private val app = Http.collectZIO[Request] {
    case Method.GET -> !! / "random" => Random.nextString(10).map(Response.text(_))
    case Method.GET -> !! / "utc"    => Clock.currentDateTime.map(s => Response.text(s.toString))
  }

  private val server =
    Server.port(PORT) ++              // Setup port
      Server.paranoidLeakDetection ++ // Paranoid leak detection (affects performance)
      Server.app(fooBar ++ app)       // Setup the Http app

  val run = ZIOAppArgs.getArgs.flatMap { args =>
    // Configure thread count using CLI
    val nThreads: Int = args.headOption.flatMap(x => Try(x.toInt).toOption).getOrElse(0)

    // Create a new server
    server.make
      .use(start =>
        // Waiting for the server to start
        Console.printLine(s"Server started on port ${start.port}")

        // Ensures the server doesn't die after printing
          *> ZIO.never,
      )
      .provideCustom(ServerChannelFactory.auto, EventLoopGroup.auto(nThreads))
  }
}

```
After changing the zio-http version(2.0.0-RC2) in build.sbt
based on the error it seems old version of zio is getting picked
run
`sbt "update; clean; cleanFiles; compile"`

**Comment by amitksingh1490** [comment]
> Maybe it's caused by the import `zio.Has` in `zhttp.package.scala`?
> 
> ```
> package zhttp
> 
> import io.netty.channel.{Channel, ChannelFactory => JChannelFactory, EventLoopGroup => JEventLoopGroup, ServerChannel}
> import zio.Has
> 
> package object service {
> 
> ...
> 
>   type ChannelFactory       = Has[JChannelFactory[Channel]]
>   type EventLoopGroup       = Has[JEventLoopGroup]
>   type ServerChannelFactory = Has[JChannelFactory[ServerChannel]]
> ```

Code in `main` branch belong to `zio vesion 1` however for for `zio version 2` we have a branch `zio-series/2.x` that branch doesn't have this code

**Comment by amitksingh1490** [comment]
[zhttp-service.zip](https://github.com/dream11/zio-http/files/7968884/zhttp-service.zip)
Here is a sample project, I have created with Zhttp `v2.0.0-RC2` let me know if this helps

**Comment by willemvermeer** [comment]
Thanks for the sample project, it works just fine. I found out what was
wrong: I was using the wrong zio-http release candidate :-( my bad! Thanks
for your help and keep up the good work!
