### ISSUE TITLE
`MimeDB.scala` which is the mapping of `file extension` to `Media Type` should be auto-generated.

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-http#934]
**What is not easy to do right now?**
[#889](https://github.com/dream11/zio-http/pull/899) introduces a file - `MimeDB.scala` which is the mapping of `file extension` to `Media Type`. It should be auto-generated.

If a new `Media-Type` is added to master `Mime db` at https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json, it will have to be added manually to the `zio-http` codebase.

**Describe the solution you'd like**
There should be a way to either (1) automatically generate 'MimeDB.scala' from https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json` or (2) detection and addition of `Content-Type` header should be possible by directly using the mappings at https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json 

**Why is it important?**
Future maintenance overhead will be high if this is not done.

**Additional context**
A few options for generating `MimeDB.scala` are -

As I understand, there are a few different options for auto-generating `MimeDB.scala`

1. Generating code using string templates ([Twirl](https://github.com/playframework/twirl)).

     **Pros** : This seems to have the easiest learning curve of all the approaches. 
                Twirl works very well with scala. The syntax is `scala-ish`
                Code is easy to read and understand.

     **Cons** : Can produce code that doesn't compile.

2. Generating code from an abstract syntax tree ([treehugger](http://eed3si9n.com/treehugger/)).

      **Pros** : Uncompilable code cannot be generated.
                        Uses scala syntax.

      **Cons** : Steep learning curve. Will take me some time to do this.
                        Not much IDE support.
                        Code looks complex, reader might take some time to understand what is happening.
                         
3. Building an abstract syntax tree and sending it directly to the compiler ([Scala macros](https://scalamacros.org/)).
      
      **Pros** : Directly passes bytecode of AST to next phase of compilation without generating `.scala` file
                       Syntactically invalid code will not be generated.

      **Cons** : Steep learning curve. Will take me some time to complete this.
                        Not much IDE support.
                        Code can be complex. Reader needs to know macros to understand what is happening.

4. Skip generating case classes entirely, by directly parsing json into a Map. 

    **Concern** : There’s a 4kb limit on the size of a map in jvm afaik, so the Map will have to be split. Also, handling all edge-cases
     might get complicated.

**Comment by jdegoes** [comment]
/bounty $500

For a clean solution that requires no third-party dependencies and is easy to update.

**Comment by kitlangton** [comment]
/attempt #934
🥳 

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/kitlangton) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @kitlangton | 1 ZIO bounty | <div align="center">Scala, Ruby, <br />Haskell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx182j8x0002l709e90ok08t/cancel-attempt) |

**Comment by kyri-petrou** [comment]
@kitlangton just wanted to check-in with you if you're still working or planning to work on this issue. I'm also happy to collaborate on it if you like
