### ISSUE TITLE
`Response.json` should accept `CharSequence`

### ISSUE THREAD

**Issue by dinojohn** [zio/zio-http#935]
**Describe the solution you'd like**
`Response.json` should accept `CharSequence`

**Additional context**
it will be more optimized in terms of memory when used with `ZIO-json`

**Comment by yisraelU** [comment]
I submitted PR for this
https://github.com/dream11/zio-http/pull/914

**Comment by ShrutiVerma97** [comment]
closing this in favour of https://github.com/dream11/zio-http/pull/1142
