### ISSUE TITLE
Add `mapError` operator in Middleware Domain

### ISSUE THREAD

**Issue by dinojohn** [zio/zio-http#938]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a `mapError` operator for MIddleware

**Describe the solution you'd like**

```scala
final def mapError[E1](ee: E => E1): Middleware[R, E1, AIn, BIn, AOut, BOut] = ???
```

**Comment by vigoo** [comment]
In #1916 we intentionally removed most of these generic combinators on middlewares so I'm closing this for now. 

Please reopen if necessary.
