### ISSUE TITLE
Make `Request` an abstract case class

### ISSUE THREAD

**Issue by girdharshubham** [zio/zio-http#947]
**Describe the solution you'd like**
`Request` is a trait right now and is rather verbose. It could be made into an `abstract case class`, this is mostly for convenience and would simplify the overall design. The class could be better described as follows -
```scala
abstract case class Request(
  method: Method,
  url: URL,
  headers: Headers,
) extends HeaderExtension[Request] {
  private[zhttp] def getBodyAsByteBuf: Task[ByteBuf]
}
```

**Comment by yisraelU** [comment]
@girdharshubham I would like to take this
Clarifying question if Request is **abstract** one loses the copy method of a case class , how would one be able to get rid of the existing copy method or a similar implementation

**Comment by girdharshubham** [comment]
@yisraelU  Yes, The current implementation for copy would change - instead of removing it.

**Comment by tusharmath** [comment]
This isn't required anymore
