### ISSUE TITLE
Create `Version` type to encode `HttpVersion`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#954]
**Is your feature request related to a problem? Please describe.**
We should be able to specify `Version` via `ClientRequest`. This is currently supported only via `HttpVersion`

**Describe the solution you'd like**
A sum type should be created for `Version` with `Http_1_1` and `Http_1_2` and `Http_2` as it's specialized types.

**Comment by girdharshubham** [comment]
I'll take it on.
